import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    type: "user-input",
    key: "N_Ed_N",
    valueType: { type: "number" },
    id: "N_Ed_N",
    name: "Design compression force",
    symbol: "N_{Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    type: "user-input",
    key: "A_mm2",
    valueType: { type: "number" },
    id: "A_mm2",
    name: "Cross-sectional area",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    type: "user-input",
    key: "fy_MPa",
    valueType: { type: "number" },
    id: "fy_MPa",
    name: "Yield strength",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    type: "user-input",
    key: "E_MPa",
    valueType: { type: "number" },
    id: "E_MPa",
    name: "Elastic modulus",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    type: "user-input",
    key: "G_MPa",
    valueType: { type: "number" },
    id: "G_MPa",
    name: "Shear modulus",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    type: "user-input",
    key: "Iy_mm4",
    valueType: { type: "number" },
    id: "Iy_mm4",
    name: "Second moment of area y-y",
    unit: "\\mathrm{mm^{4}}",
    children: [],
  },
  {
    type: "user-input",
    key: "Iz_mm4",
    valueType: { type: "number" },
    id: "Iz_mm4",
    name: "Second moment of area z-z",
    unit: "\\mathrm{mm^{4}}",
    children: [],
  },
  {
    type: "user-input",
    key: "It_mm4",
    valueType: { type: "number" },
    id: "It_mm4",
    name: "St. Venant torsion constant",
    unit: "\\mathrm{mm^{4}}",
    children: [],
  },
  {
    type: "user-input",
    key: "Iw_mm6",
    valueType: { type: "number" },
    id: "Iw_mm6",
    name: "Warping constant",
    unit: "\\mathrm{mm^{6}}",
    children: [],
  },
  {
    type: "user-input",
    key: "L_mm",
    valueType: { type: "number" },
    id: "L_mm",
    name: "Member length",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    type: "user-input",
    key: "k_T",
    valueType: { type: "number" },
    id: "k_T",
    name: "Buckling length factor for torsional buckling",
    children: [],
  },
  {
    type: "user-input",
    key: "k_z",
    valueType: { type: "number" },
    id: "k_z",
    name: "Fallback buckling length factor z",
    children: [],
  },
  {
    type: "user-input",
    key: "torsional_deformations",
    valueType: { type: "string" },
    id: "torsional_deformations",
    name: "Member susceptible to torsional deformations (yes/no)",
    children: [],
  },
  {
    type: "user-input",
    key: "section_shape",
    valueType: { type: "string", oneOf: ["I", "RHS", "CHS"] },
    id: "section_shape",
    name: "Section shape family (I, RHS, CHS)",
    children: [],
  },
  {
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    id: "section_class",
    name: "Section class (1, 2, 3, 4)",
    children: [],
  },
  {
    type: "user-input",
    key: "alpha_z",
    valueType: { type: "number" },
    id: "alpha_z",
    name: "Imperfection factor (z-axis curve)",
    symbol: "\\alpha",
    children: [],
  },
  {
    type: "coefficient",
    key: "gamma_M1",
    valueType: { type: "number" },
    id: "gamma_M1",
    name: "Partial safety factor",
    symbol: "\\gamma_{M1}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
  {
    type: "constant",
    key: "pi",
    valueType: { type: "number" },
    id: "pi",
    name: "Pi",
    symbol: "\\pi",
    children: [],
  },
  {
    type: "derived",
    key: "ip2_mm2",
    valueType: { type: "number" },
    id: "ip2_mm2",
    name: "Polar radius term",
    expression: "\\frac{I_y+I_z}{A_mm2}",
    children: [{ nodeId: "Iy_mm4" }, { nodeId: "Iz_mm4" }, { nodeId: "A_mm2" }],
  },
  {
    type: "derived",
    key: "N_cr_T_N",
    valueType: { type: "number" },
    id: "N_cr_T_N",
    name: "Elastic torsional critical force",
    symbol: "N_{cr,T}",
    expression:
      "\\frac{1}{i_p^2}\\left(G_MPa I_t + \\frac{\\pi^2 E_MPa I_w}{L_{cr,T}^2}\\right)",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.3.1.4", paragraphRef: "(2)" },
    children: [
      { nodeId: "ip2_mm2" },
      { nodeId: "G_MPa" },
      { nodeId: "It_mm4" },
      { nodeId: "pi" },
      { nodeId: "E_MPa" },
      { nodeId: "Iw_mm6" },
      { nodeId: "L_mm" },
      { nodeId: "k_T" },
      { nodeId: "k_z" },
    ],
  },
  {
    type: "derived",
    key: "N_cr_governing_N",
    valueType: { type: "number" },
    id: "N_cr_governing_N",
    name: "Selected critical force for torsional/torsional-flexural slenderness",
    symbol: "N_{cr}",
    expression: "N_{cr,T}=N_{cr,TF}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.3.1.4", paragraphRef: "(2)" },
    children: [{ nodeId: "N_cr_T_N" }],
  },
  {
    type: "derived",
    key: "lambda_bar_TF",
    valueType: { type: "number" },
    id: "lambda_bar_TF",
    name: "Non-dimensional slenderness (torsional-flexural)",
    symbol: "\\bar{\\lambda}_{TF}",
    expression: "\\sqrt{\\frac{Af_y}{N_{cr}}}",
    meta: { sectionRef: "6.3.1.4", paragraphRef: "(2)" },
    children: [
      { nodeId: "A_mm2" },
      { nodeId: "fy_MPa" },
      { nodeId: "N_cr_governing_N" },
    ],
  },
  {
    type: "derived",
    key: "phi_TF",
    valueType: { type: "number" },
    id: "phi_TF",
    name: "Buckling parameter (torsional-flexural)",
    symbol: "\\Phi_{TF}",
    expression:
      "0.5(1 + \\alpha(\\bar{\\lambda}_{TF}-0.2) + \\bar{\\lambda}_{TF}^2)",
    children: [{ nodeId: "alpha_z" }, { nodeId: "lambda_bar_TF" }],
  },
  {
    type: "derived",
    key: "chi_TF",
    valueType: { type: "number" },
    id: "chi_TF",
    name: "Capped torsional-flexural reduction factor",
    expression: "\\min(1,\\chi_{TF,base})",
    children: [{ nodeId: "phi_TF" }, { nodeId: "lambda_bar_TF" }],
  },
  {
    type: "formula",
    key: "N_b_TF_Rd_N",
    valueType: { type: "number" },
    id: "N_b_TF_Rd_N",
    name: "Torsional-flexural buckling resistance",
    symbol: "N_{b_mm,TF,Rd}",
    expression: "\\frac{\\chi_{TF} A_mm2 f_y}{\\gamma_{M1}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.3.1.1", formulaRef: "(6.47)" },
    children: [
      { nodeId: "chi_TF" },
      { nodeId: "A_mm2" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M1" },
    ],
  },
  {
    type: "derived",
    key: "abs_N_Ed_N",
    valueType: { type: "number" },
    id: "abs_N_Ed_N",
    name: "Absolute design axial force",
    expression: "\\left|N_{Ed}\\right|",
    children: [{ nodeId: "N_Ed_N" }],
  },
  {
    type: "check",
    key: "torsional_buckling_check",
    valueType: { type: "number" },
    id: "torsional_buckling_check",
    name: "Torsional-flexural buckling check",
    verificationExpression: "\\frac{N_{Ed}}{N_{b_mm,TF,Rd}} \\leq 1.0",
    meta: { sectionRef: "6.3.1.1", verificationRef: "(6.46)" },
    children: [{ nodeId: "abs_N_Ed_N" }, { nodeId: "N_b_TF_Rd_N" }],
  },
]);

export type Nodes = typeof nodes;
