import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "bending_y_axial_shear_check",
    type: "check",
    key: "bending_y_axial_shear_check",
    valueType: { type: "number" },
    name: "Bending, axial-force, and shear resistance check about y-y",
    verificationExpression:
      "\\text{class 1/2: }\\frac{\\left|M_{y,Ed}\\right|}{M_{NV,y,Rd}}\\leq1.0\\ ;\\ \\text{class 3: }\\frac{\\sigma_{v,Ed}}{f_y/\\gamma_{M0}}\\leq1.0",
    meta: { sectionRef: "6.2.10", verificationRef: "(6.45),(6.42)" },
    children: [
      {
        nodeId: "utilization_class12",
        when: {
          or: [{ eq: ["section_class", 1] }, { eq: ["section_class", 2] }],
        },
      },
      {
        nodeId: "utilization_class3",
        when: { eq: ["section_class", 3] },
      },
    ],
  },
  {
    id: "utilization_class12",
    type: "derived",
    key: "utilization_class12",
    valueType: { type: "number" },
    name: "Class 1/2 utilization ratio about y-y",
    expression: "\\left|M_{y,Ed}\\right|/M_{NV,y,Rd}",
    children: [{ nodeId: "abs_M_y_Ed" }, { nodeId: "M_NV_y_Rd" }],
  },
  {
    id: "M_NV_y_Rd",
    type: "formula",
    key: "M_NV_y_Rd",
    valueType: { type: "number" },
    name: "Reduced bending resistance about y-y under axial force and shear",
    symbol: "M_{NV,y,Rd}",
    expression: "M_{y,V,Rd} \\cdot \\min\\left(1,\\frac{1-n}{1-0.5a_w}\\right)",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.10", formulaRef: "(6.36)" },
    children: [{ nodeId: "M_y_V_Rd" }, { nodeId: "k_y" }],
  },
  {
    id: "M_y_V_Rd",
    type: "formula",
    key: "M_y_V_Rd",
    valueType: { type: "number" },
    name: "Reduced bending resistance about y-y under shear",
    symbol: "M_{y,V,Rd}",
    expression: "\\frac{W_{pl,y,eff} \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.10", formulaRef: "(6.45)" },
    children: [{ nodeId: "Wpl_y_eff" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "Wpl_y_eff",
    type: "derived",
    key: "Wpl_y_eff",
    valueType: { type: "number" },
    name: "Effective plastic section modulus about y-y under shear",
    expression: "\\text{shape branch value}",
    unit: "\\mathrm{mm^{3}}",
    children: [
      { nodeId: "section_shape" },
      {
        nodeId: "Wpl_y_eff_i",
        when: { eq: ["section_shape", "I"] },
      },
      {
        nodeId: "Wpl_y_eff_rhs",
        when: { eq: ["section_shape", "RHS"] },
      },
      {
        nodeId: "Wpl_y_eff_chs",
        when: { eq: ["section_shape", "CHS"] },
      },
    ],
  },
  {
    id: "Wpl_y_eff_i",
    type: "derived",
    key: "Wpl_y_eff_i",
    valueType: { type: "number" },
    name: "I-section effective plastic modulus about y-y",
    expression: "\\text{reduced-thickness model (EC3 6.2.10(3))}",
    unit: "\\mathrm{mm^{3}}",
    children: [
      { nodeId: "Wpl_y" },
      { nodeId: "b" },
      { nodeId: "h" },
      { nodeId: "tf" },
      { nodeId: "tw" },
      { nodeId: "rho_y" },
      { nodeId: "rho_z" },
    ],
  },
  {
    id: "Wpl_y_eff_rhs",
    type: "derived",
    key: "Wpl_y_eff_rhs",
    valueType: { type: "number" },
    name: "RHS section effective plastic modulus about y-y",
    expression: "W_{pl,y} - \\rho_z \\frac{A_{v,z}^2}{4 t_w}",
    unit: "\\mathrm{mm^{3}}",
    children: [{ nodeId: "Wpl_y" }, { nodeId: "rho_z" }, { nodeId: "Av_z" }, { nodeId: "tw" }],
  },
  {
    id: "Wpl_y_eff_chs",
    type: "derived",
    key: "Wpl_y_eff_chs",
    valueType: { type: "number" },
    name: "CHS section effective plastic modulus about y-y",
    expression: "W_{pl,y} - \\rho_z \\frac{A_{v,z}^2}{4 t_w}",
    unit: "\\mathrm{mm^{3}}",
    children: [{ nodeId: "Wpl_y" }, { nodeId: "rho_z" }, { nodeId: "Av_z" }, { nodeId: "tw" }],
  },
  {
    id: "k_y",
    type: "derived",
    key: "k_y",
    valueType: { type: "number" },
    name: "Axial reduction factor",
    expression: "n \\leq 0.5a_w ? 1 : \\min\\left(1,\\frac{1-n}{1-0.5a_w}\\right)",
    children: [
      { nodeId: "is_n_le_half_a_w" },
      { nodeId: "n" },
      { nodeId: "a_w" },
    ],
  },
  {
    id: "is_n_le_half_a_w",
    type: "derived",
    key: "is_n_le_half_a_w",
    valueType: { type: "number" },
    name: "Threshold indicator for n <= 0.5a_w",
    expression: "n \\leq 0.5a_w",
    children: [{ nodeId: "n" }, { nodeId: "a_w" }],
  },
  {
    id: "a_w",
    type: "derived",
    key: "a_w",
    valueType: { type: "number" },
    name: "Limited area ratio for y-y branch",
    expression: "\\min(a_w,0.5)",
    children: [
      { nodeId: "section_shape" },
      {
        nodeId: "a_w_i",
        when: { eq: ["section_shape", "I"] },
      },
      {
        nodeId: "a_w_rhs",
        when: { eq: ["section_shape", "RHS"] },
      },
      {
        nodeId: "a_w_chs",
        when: { eq: ["section_shape", "CHS"] },
      },
    ],
  },
  {
    id: "a_w_i",
    type: "derived",
    key: "a_w_i",
    valueType: { type: "number" },
    name: "I-section area ratio for y-y branch",
    expression: "(A-2b t_f)/A",
    children: [{ nodeId: "A" }, { nodeId: "b" }, { nodeId: "tf" }],
  },
  {
    id: "a_w_rhs",
    type: "derived",
    key: "a_w_rhs",
    valueType: { type: "number" },
    name: "RHS section area ratio for y-y branch",
    expression: "(A-2b t_w)/A",
    children: [{ nodeId: "A" }, { nodeId: "b" }, { nodeId: "tw" }],
  },
  {
    id: "a_w_chs",
    type: "derived",
    key: "a_w_chs",
    valueType: { type: "number" },
    name: "CHS section area ratio for y-y branch",
    expression: "0.5",
    children: [{ nodeId: "section_shape" }],
  },
  {
    id: "n",
    type: "derived",
    key: "n",
    valueType: { type: "number" },
    name: "Axial force ratio",
    symbol: "n",
    expression: "\\frac{\\left|N_{Ed}\\right|}{N_{pl,Rd}}",
    children: [{ nodeId: "N_c_Ed" }, { nodeId: "N_pl_Rd" }],
  },
  {
    id: "N_c_Ed",
    type: "derived",
    key: "N_c_Ed",
    valueType: { type: "number" },
    name: "Design axial force magnitude",
    expression: "\\left|N_{Ed}\\right|",
    unit: "\\mathrm{N}",
    children: [{ nodeId: "N_Ed" }],
  },
  {
    id: "N_pl_Rd",
    type: "formula",
    key: "N_pl_Rd",
    valueType: { type: "number" },
    name: "Plastic resistance to normal force",
    symbol: "N_{pl,Rd}",
    expression: "\\frac{A \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.4", formulaRef: "(6.10)" },
    children: [{ nodeId: "A" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "rho_z",
    type: "derived",
    key: "rho_z",
    valueType: { type: "number" },
    name: "Shear reduction factor about z-z",
    expression:
      "\\left(\\frac{2\\left|V_{z,Ed}\\right|}{V_{pl,z,Rd}} - 1\\right)^2 \\text{ for } \\frac{\\left|V_{z,Ed}\\right|}{V_{pl,z,Rd}} > 0.5, \\text{ else } 0",
    symbol: "\\rho_z",
    children: [{ nodeId: "abs_V_z_Ed" }, { nodeId: "V_pl_z_Rd" }],
  },
  {
    id: "rho_y",
    type: "derived",
    key: "rho_y",
    valueType: { type: "number" },
    name: "Shear reduction factor about y-y",
    expression:
      "\\left(\\frac{2\\left|V_{y,Ed}\\right|}{V_{pl,y,Rd}} - 1\\right)^2 \\text{ for } \\frac{\\left|V_{y,Ed}\\right|}{V_{pl,y,Rd}} > 0.5, \\text{ else } 0",
    symbol: "\\rho_y",
    children: [{ nodeId: "abs_V_y_Ed" }, { nodeId: "V_pl_y_Rd" }],
  },
  {
    id: "V_pl_z_Rd",
    type: "formula",
    key: "V_pl_z_Rd",
    valueType: { type: "number" },
    name: "Plastic shear resistance about z-z",
    symbol: "V_{pl,z,Rd}",
    expression: "\\dfrac{A_{v,z} \\cdot f_y}{\\sqrt{3}\\,\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.6", formulaRef: "(6.18)" },
    children: [{ nodeId: "Av_z" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "V_pl_y_Rd",
    type: "formula",
    key: "V_pl_y_Rd",
    valueType: { type: "number" },
    name: "Plastic shear resistance about y-y",
    symbol: "V_{pl,y,Rd}",
    expression: "\\dfrac{A_{v,y} \\cdot f_y}{\\sqrt{3}\\,\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.6", formulaRef: "(6.18)" },
    children: [{ nodeId: "Av_y" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "utilization_class3",
    type: "derived",
    key: "utilization_class3",
    valueType: { type: "number" },
    name: "Class 3 Von Mises utilization ratio",
    expression: "\\sigma_{v,Ed}/(f_y/\\gamma_{M0})",
    children: [{ nodeId: "sigma_v_class3" }, { nodeId: "sigma_limit" }],
  },
  {
    id: "sigma_v_class3",
    type: "derived",
    key: "sigma_v_class3",
    valueType: { type: "number" },
    name: "Equivalent Von Mises stress for class 3",
    expression: "\\sqrt{\\sigma_x^2+3(\\tau_y^2+\\tau_z^2)}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "sigma_x_class3" }, { nodeId: "tau_y" }, { nodeId: "tau_z" }],
  },
  {
    id: "sigma_x_class3",
    type: "derived",
    key: "sigma_x_class3",
    valueType: { type: "number" },
    name: "Longitudinal normal stress for class 3",
    expression: "\\sigma_N+\\sigma_{M,y}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "sigma_N" }, { nodeId: "sigma_M_y" }],
  },
  {
    id: "sigma_N",
    type: "derived",
    key: "sigma_N",
    valueType: { type: "number" },
    name: "Axial stress contribution",
    expression: "\\left|N_{Ed}\\right|/A",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_N_Ed" }, { nodeId: "A" }],
  },
  {
    id: "sigma_M_y",
    type: "derived",
    key: "sigma_M_y",
    valueType: { type: "number" },
    name: "Bending stress contribution about y-y",
    expression: "\\left|M_{y,Ed}\\right|/W_{el,y}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_M_y_Ed" }, { nodeId: "Wel_y" }],
  },
  {
    id: "tau_y",
    type: "derived",
    key: "tau_y",
    valueType: { type: "number" },
    name: "Average shear stress from V_y",
    expression: "\\left|V_{y,Ed}\\right|/A_{v,y}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_V_y_Ed" }, { nodeId: "Av_y" }],
  },
  {
    id: "tau_z",
    type: "derived",
    key: "tau_z",
    valueType: { type: "number" },
    name: "Average shear stress from V_z",
    expression: "\\left|V_{z,Ed}\\right|/A_{v,z}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_V_z_Ed" }, { nodeId: "Av_z" }],
  },
  {
    id: "sigma_limit",
    type: "formula",
    key: "sigma_limit",
    valueType: { type: "number" },
    name: "Class 3 stress limit",
    symbol: "f_y/\\gamma_{M0}",
    expression: "\\frac{f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{MPa}",
    meta: { sectionRef: "6.2.10", formulaRef: "(6.42)" },
    children: [{ nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "abs_M_y_Ed",
    type: "derived",
    key: "abs_M_y_Ed",
    valueType: { type: "number" },
    name: "Design bending moment magnitude about y-y",
    expression: "\\left|M_{y,Ed}\\right|",
    unit: "\\mathrm{N\\cdot mm}",
    children: [{ nodeId: "M_y_Ed" }],
  },
  {
    id: "abs_N_Ed",
    type: "derived",
    key: "abs_N_Ed",
    valueType: { type: "number" },
    name: "Design axial force magnitude",
    expression: "\\left|N_{Ed}\\right|",
    unit: "\\mathrm{N}",
    children: [{ nodeId: "N_Ed" }],
  },
  {
    id: "abs_V_z_Ed",
    type: "derived",
    key: "abs_V_z_Ed",
    valueType: { type: "number" },
    name: "Design shear force magnitude about z-z",
    expression: "\\left|V_{z,Ed}\\right|",
    unit: "\\mathrm{N}",
    children: [{ nodeId: "V_z_Ed" }],
  },
  {
    id: "abs_V_y_Ed",
    type: "derived",
    key: "abs_V_y_Ed",
    valueType: { type: "number" },
    name: "Design shear force magnitude about y-y",
    expression: "\\left|V_{y,Ed}\\right|",
    unit: "\\mathrm{N}",
    children: [{ nodeId: "V_y_Ed" }],
  },
  {
    id: "M_y_Ed",
    type: "user-input",
    key: "M_y_Ed",
    valueType: { type: "number" },
    name: "Design bending moment about y-y",
    symbol: "M_{y,Ed}",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "N_Ed",
    type: "user-input",
    key: "N_Ed",
    valueType: { type: "number" },
    name: "Design axial force",
    symbol: "N_{Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "V_z_Ed",
    type: "user-input",
    key: "V_z_Ed",
    valueType: { type: "number" },
    name: "Design shear force about z-z",
    symbol: "V_{z,Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "V_y_Ed",
    type: "user-input",
    key: "V_y_Ed",
    valueType: { type: "number" },
    name: "Design shear force about y-y",
    symbol: "V_{y,Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "section_shape",
    type: "user-input",
    key: "section_shape",
    valueType: { type: "string", literal: ["I", "RHS", "CHS"] },
    name: "Section shape family",
    symbol: "\\text{shape}",
    children: [],
  },
  {
    id: "section_class",
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    name: "Section class",
    symbol: "\\text{class}",
    children: [],
  },
  {
    id: "A",
    type: "user-input",
    key: "A",
    valueType: { type: "number" },
    name: "Cross-sectional area",
    symbol: "A",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "Av_y",
    type: "user-input",
    key: "Av_y",
    valueType: { type: "number" },
    name: "Shear area about y-y",
    symbol: "A_{v,y}",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "Av_z",
    type: "user-input",
    key: "Av_z",
    valueType: { type: "number" },
    name: "Shear area about z-z",
    symbol: "A_{v,z}",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "b",
    type: "user-input",
    key: "b",
    valueType: { type: "number" },
    name: "Section width",
    symbol: "b",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "h",
    type: "user-input",
    key: "h",
    valueType: { type: "number" },
    name: "Section depth",
    symbol: "h",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tf",
    type: "user-input",
    key: "tf",
    valueType: { type: "number" },
    name: "Flange thickness",
    symbol: "t_f",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tw",
    type: "user-input",
    key: "tw",
    valueType: { type: "number" },
    name: "Web or wall thickness",
    symbol: "t_w",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "Wpl_y",
    type: "user-input",
    key: "Wpl_y",
    valueType: { type: "number" },
    name: "Plastic section modulus about y-y",
    symbol: "W_{pl,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wel_y",
    type: "user-input",
    key: "Wel_y",
    valueType: { type: "number" },
    name: "Elastic section modulus about y-y",
    symbol: "W_{el,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "fy",
    type: "user-input",
    key: "fy",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
