import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "biaxial_axial_shear_check",
    type: "check",
    key: "biaxial_axial_shear_check",
    valueType: { type: "number" },
    name: "Biaxial bending + axial + shear check",
    verificationExpression:
      "\\left(\\frac{\\left|M_{y,Ed}\\right|}{M_{NV,y,Rd}}\\right)^\\alpha + \\left(\\frac{\\left|M_{z,Ed}\\right|}{M_{NV,z,Rd}}\\right)^\\beta \\leq 1.0",
    meta: { sectionRef: "6.2.10", verificationRef: "(6.41)" },
    children: [
      { nodeId: "abs_M_y_Ed" },
      { nodeId: "M_NV_y_Rd" },
      { nodeId: "alpha_biax" },
      { nodeId: "abs_M_z_Ed" },
      { nodeId: "M_NV_z_Rd" },
      { nodeId: "beta_biax" },
    ],
  },
  {
    id: "M_y_Ed",
    type: "user-input",
    key: "M_y_Ed",
    valueType: { type: "number" },
    name: "Design bending moment y-y",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "M_z_Ed",
    type: "user-input",
    key: "M_z_Ed",
    valueType: { type: "number" },
    name: "Design bending moment z-z",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "N_Ed",
    type: "user-input",
    key: "N_Ed",
    valueType: { type: "number" },
    name: "Design axial force",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "V_z_Ed",
    type: "user-input",
    key: "V_z_Ed",
    valueType: { type: "number" },
    name: "Design shear force z",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "V_y_Ed",
    type: "user-input",
    key: "V_y_Ed",
    valueType: { type: "number" },
    name: "Design shear force y",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "A",
    type: "user-input",
    key: "A",
    valueType: { type: "number" },
    name: "Cross-sectional area",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "b",
    type: "user-input",
    key: "b",
    valueType: { type: "number" },
    name: "Section width",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "h",
    type: "user-input",
    key: "h",
    valueType: { type: "number" },
    name: "Section depth",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tf",
    type: "user-input",
    key: "tf",
    valueType: { type: "number" },
    name: "Flange thickness",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tw",
    type: "user-input",
    key: "tw",
    valueType: { type: "number" },
    name: "Web/wall thickness",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "Wpl_y",
    type: "user-input",
    key: "Wpl_y",
    valueType: { type: "number" },
    name: "Plastic section modulus y-y",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wpl_z",
    type: "user-input",
    key: "Wpl_z",
    valueType: { type: "number" },
    name: "Plastic section modulus z-z",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wel_z",
    type: "user-input",
    key: "Wel_z",
    valueType: { type: "number" },
    name: "Elastic section modulus z-z",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Av_z",
    type: "user-input",
    key: "Av_z",
    valueType: { type: "number" },
    name: "Shear area z",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "Av_y",
    type: "user-input",
    key: "Av_y",
    valueType: { type: "number" },
    name: "Shear area y",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "section_shape",
    type: "user-input",
    key: "section_shape",
    valueType: { type: "string", literal: ["I", "RHS", "CHS"] },
    name: "Section shape family",
    children: [],
  },
  {
    id: "section_class",
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    name: "Section class",
    children: [],
  },
  {
    id: "fy",
    type: "user-input",
    key: "fy",
    valueType: { type: "number" },
    name: "Yield strength",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
  {
    id: "V_pl_z_Rd",
    type: "formula",
    key: "V_pl_z_Rd",
    valueType: { type: "number" },
    name: "Plastic shear resistance z",
    symbol: "V_{pl,z,Rd}",
    expression: "A_{v,z} f_y / (\\sqrt{3} \\gamma_{M0})",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.6", formulaRef: "(6.18)" },
    children: [{ nodeId: "Av_z" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "V_pl_y_Rd",
    type: "formula",
    key: "V_pl_y_Rd",
    valueType: { type: "number" },
    name: "Plastic shear resistance y",
    symbol: "V_{pl,y,Rd}",
    expression: "A_{v,y} f_y / (\\sqrt{3} \\gamma_{M0})",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.6", formulaRef: "(6.18)" },
    children: [{ nodeId: "Av_y" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "abs_V_z_Ed",
    type: "derived",
    key: "abs_V_z_Ed",
    valueType: { type: "number" },
    name: "Absolute design shear force z",
    children: [{ nodeId: "V_z_Ed" }],
  },
  {
    id: "abs_V_y_Ed",
    type: "derived",
    key: "abs_V_y_Ed",
    valueType: { type: "number" },
    name: "Absolute design shear force y",
    children: [{ nodeId: "V_y_Ed" }],
  },
  {
    id: "rho_z",
    type: "derived",
    key: "rho_z",
    valueType: { type: "number" },
    name: "Shear interaction z",
    expression: "|V_z|/V_pl_z<=0.5?0:(2|V_z|/V_pl_z-1)^2",
    children: [{ nodeId: "abs_V_z_Ed" }, { nodeId: "V_pl_z_Rd" }],
  },
  {
    id: "rho_y",
    type: "derived",
    key: "rho_y",
    valueType: { type: "number" },
    name: "Shear interaction y",
    expression: "|V_y|/V_pl_y<=0.5?0:(2|V_y|/V_pl_y-1)^2",
    children: [{ nodeId: "abs_V_y_Ed" }, { nodeId: "V_pl_y_Rd" }],
  },
  {
    id: "N_pl_Rd",
    type: "formula",
    key: "N_pl_Rd",
    valueType: { type: "number" },
    name: "Plastic resistance",
    symbol: "N_{pl,Rd}",
    expression: "A f_y / \\gamma_{M0}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.4", formulaRef: "(6.6)" },
    children: [{ nodeId: "A" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "abs_N_Ed",
    type: "derived",
    key: "abs_N_Ed",
    valueType: { type: "number" },
    name: "Absolute design axial force",
    children: [{ nodeId: "N_Ed" }],
  },
  {
    id: "n",
    type: "derived",
    key: "n",
    valueType: { type: "number" },
    name: "Axial force ratio",
    expression: "|N_{Ed}|/N_{pl,Rd}",
    children: [{ nodeId: "abs_N_Ed" }, { nodeId: "N_pl_Rd" }],
  },
  {
    id: "a_w",
    type: "derived",
    key: "a_w",
    valueType: { type: "number" },
    name: "Limited area ratio for y-branch",
    expression: "min(a_w,0.5)",
    children: [
      { nodeId: "section_shape" },
      { nodeId: "a_w_i", when: { eq: ["section_shape", "I"] } },
      { nodeId: "a_w_rhs", when: { eq: ["section_shape", "RHS"] } },
      { nodeId: "a_w_chs", when: { eq: ["section_shape", "CHS"] } },
    ],
  },
  {
    id: "a_w_i",
    type: "derived",
    key: "a_w_i",
    valueType: { type: "number" },
    name: "I-section y-branch area ratio",
    expression: "(A-2b t_f)/A",
    children: [{ nodeId: "A" }, { nodeId: "b" }, { nodeId: "tf" }],
  },
  {
    id: "a_w_rhs",
    type: "derived",
    key: "a_w_rhs",
    valueType: { type: "number" },
    name: "RHS y-branch area ratio",
    expression: "(A-2b t_w)/A",
    children: [{ nodeId: "A" }, { nodeId: "b" }, { nodeId: "tw" }],
  },
  {
    id: "a_w_chs",
    type: "derived",
    key: "a_w_chs",
    valueType: { type: "number" },
    name: "CHS y-branch area ratio",
    expression: "0.5",
    children: [{ nodeId: "section_shape" }],
  },
  {
    id: "a_f",
    type: "derived",
    key: "a_f",
    valueType: { type: "number" },
    name: "Limited area ratio for z-branch",
    expression: "min(a_f,0.5)",
    children: [
      { nodeId: "section_shape" },
      { nodeId: "a_f_i", when: { eq: ["section_shape", "I"] } },
      { nodeId: "a_f_rhs", when: { eq: ["section_shape", "RHS"] } },
      { nodeId: "a_f_chs", when: { eq: ["section_shape", "CHS"] } },
    ],
  },
  {
    id: "a_f_i",
    type: "derived",
    key: "a_f_i",
    valueType: { type: "number" },
    name: "I-section z-branch area ratio",
    expression: "(A-2b t_f)/A",
    children: [{ nodeId: "A" }, { nodeId: "b" }, { nodeId: "tf" }],
  },
  {
    id: "a_f_rhs",
    type: "derived",
    key: "a_f_rhs",
    valueType: { type: "number" },
    name: "RHS z-branch area ratio",
    expression: "(A-2h t_w)/A",
    children: [{ nodeId: "A" }, { nodeId: "h" }, { nodeId: "tw" }],
  },
  {
    id: "a_f_chs",
    type: "derived",
    key: "a_f_chs",
    valueType: { type: "number" },
    name: "CHS z-branch area ratio",
    expression: "0.5",
    children: [{ nodeId: "section_shape" }],
  },
  {
    id: "is_n_le_half_a_w",
    type: "derived",
    key: "is_n_le_half_a_w",
    valueType: { type: "number" },
    name: "Threshold indicator n <= 0.5 a_w",
    children: [{ nodeId: "n" }, { nodeId: "a_w" }],
  },
  {
    id: "k_y",
    type: "derived",
    key: "k_y",
    valueType: { type: "number" },
    name: "Axial reduction factor for y-branch",
    expression: "n <= 0.5 a_w ? 1 : min(1,(1-n)/(1-0.5 a_w))",
    children: [{ nodeId: "is_n_le_half_a_w" }, { nodeId: "n" }, { nodeId: "a_w" }],
  },
  {
    id: "Wpl_y_eff",
    type: "derived",
    key: "Wpl_y_eff",
    valueType: { type: "number" },
    name: "Effective plastic modulus y",
    expression: "Shape branch reduced-thickness model",
    children: [
      { nodeId: "section_shape" },
      { nodeId: "Wpl_y_eff_i", when: { eq: ["section_shape", "I"] } },
      { nodeId: "Wpl_y_eff_rhs", when: { eq: ["section_shape", "RHS"] } },
      { nodeId: "Wpl_y_eff_chs", when: { eq: ["section_shape", "CHS"] } },
    ],
  },
  {
    id: "Wpl_y_eff_i",
    type: "derived",
    key: "Wpl_y_eff_i",
    valueType: { type: "number" },
    name: "I-section effective plastic modulus y",
    children: [
      { nodeId: "Wpl_y" },
      { nodeId: "b" },
      { nodeId: "h" },
      { nodeId: "tf" },
      { nodeId: "tw" },
      { nodeId: "rho_y" },
      { nodeId: "rho_z" },
    ],
  },
  {
    id: "Wpl_y_eff_rhs",
    type: "derived",
    key: "Wpl_y_eff_rhs",
    valueType: { type: "number" },
    name: "RHS effective plastic modulus y",
    children: [{ nodeId: "Wpl_y" }, { nodeId: "rho_z" }, { nodeId: "Av_z" }, { nodeId: "tw" }],
  },
  {
    id: "Wpl_y_eff_chs",
    type: "derived",
    key: "Wpl_y_eff_chs",
    valueType: { type: "number" },
    name: "CHS effective plastic modulus y",
    children: [{ nodeId: "Wpl_y" }, { nodeId: "rho_z" }, { nodeId: "Av_z" }, { nodeId: "tw" }],
  },
  {
    id: "M_y_V_Rd",
    type: "formula",
    key: "M_y_V_Rd",
    valueType: { type: "number" },
    name: "Reduced plastic moment y-y allowing for shear",
    symbol: "M_{y,V,Rd}",
    expression: "W_{pl,y,eff}f_y/\\gamma_{M0}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.10", formulaRef: "(6.45)" },
    children: [{ nodeId: "Wpl_y_eff" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "M_NV_y_Rd",
    type: "formula",
    key: "M_NV_y_Rd",
    valueType: { type: "number" },
    name: "Reduced plastic moment y-y (axial + shear)",
    symbol: "M_{NV,y,Rd}",
    expression: "M_{y,V,Rd}*k_y",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.36)" },
    children: [{ nodeId: "M_y_V_Rd" }, { nodeId: "k_y" }],
  },
  {
    id: "Wpl_z_web",
    type: "derived",
    key: "Wpl_z_web",
    valueType: { type: "number" },
    name: "Web contribution to plastic modulus about z-z",
    expression: "A_{v,z} t_w / 4",
    children: [{ nodeId: "Av_z" }, { nodeId: "tw" }],
  },
  {
    id: "W_z_res",
    type: "derived",
    key: "W_z_res",
    valueType: { type: "number" },
    name: "Class-dependent section modulus for z bending",
    expression: "class 3 ? W_el,z : W_pl,z",
    children: [
      { nodeId: "section_class" },
      {
        nodeId: "W_z_res_class12",
        when: {
          or: [{ eq: ["section_class", 1] }, { eq: ["section_class", 2] }],
        },
      },
      { nodeId: "W_z_res_class3", when: { eq: ["section_class", 3] } },
    ],
  },
  {
    id: "W_z_res_class12",
    type: "derived",
    key: "W_z_res_class12",
    valueType: { type: "number" },
    name: "Class 1/2 resistance modulus about z-z",
    children: [{ nodeId: "Wpl_z" }],
  },
  {
    id: "W_z_res_class3",
    type: "derived",
    key: "W_z_res_class3",
    valueType: { type: "number" },
    name: "Class 3 resistance modulus about z-z",
    children: [{ nodeId: "Wel_z" }],
  },
  {
    id: "Wpl_z_eff",
    type: "derived",
    key: "Wpl_z_eff",
    valueType: { type: "number" },
    name: "Effective plastic modulus z",
    expression: "W_{z,res}-\\rho_y(W_{z,res}-W_{pl,z,web})",
    children: [{ nodeId: "W_z_res" }, { nodeId: "rho_y" }, { nodeId: "Wpl_z_web" }],
  },
  {
    id: "M_z_V_Rd",
    type: "formula",
    key: "M_z_V_Rd",
    valueType: { type: "number" },
    name: "Reduced plastic moment z-z allowing for shear",
    symbol: "M_{z,V,Rd}",
    expression: "W_{pl,z,eff}f_y/\\gamma_{M0}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.8", formulaRef: "(6.30)" },
    children: [{ nodeId: "Wpl_z_eff" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "is_n_le_a_f",
    type: "derived",
    key: "is_n_le_a_f",
    valueType: { type: "number" },
    name: "Threshold indicator n <= a_f",
    children: [{ nodeId: "n" }, { nodeId: "a_f" }],
  },
  {
    id: "k_z",
    type: "derived",
    key: "k_z",
    valueType: { type: "number" },
    name: "Axial reduction factor for z-branch",
    expression: "n <= a_f ? 1 : 1-((n-a_f)/(1-a_f))^2",
    children: [{ nodeId: "is_n_le_a_f" }, { nodeId: "n" }, { nodeId: "a_f" }],
  },
  {
    id: "M_NV_z_Rd",
    type: "formula",
    key: "M_NV_z_Rd",
    valueType: { type: "number" },
    name: "Reduced plastic moment z-z (axial + shear)",
    symbol: "M_{NV,z,Rd}",
    expression: "M_{z,V,Rd}*k_z",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.38)" },
    children: [{ nodeId: "M_z_V_Rd" }, { nodeId: "k_z" }],
  },
  {
    id: "alpha_biax",
    type: "derived",
    key: "alpha_biax",
    valueType: { type: "number" },
    name: "Biaxial exponent alpha",
    children: [{ nodeId: "section_shape" }, { nodeId: "n" }],
  },
  {
    id: "beta_biax",
    type: "derived",
    key: "beta_biax",
    valueType: { type: "number" },
    name: "Biaxial exponent beta",
    children: [{ nodeId: "section_shape" }, { nodeId: "n" }],
  },
  {
    id: "abs_M_y_Ed",
    type: "derived",
    key: "abs_M_y_Ed",
    valueType: { type: "number" },
    name: "Absolute design moment y",
    children: [{ nodeId: "M_y_Ed" }],
  },
  {
    id: "abs_M_z_Ed",
    type: "derived",
    key: "abs_M_z_Ed",
    valueType: { type: "number" },
    name: "Absolute design moment z",
    children: [{ nodeId: "M_z_Ed" }],
  },
]);

export type Nodes = typeof nodes;
