import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "compression_check",
    type: "check",
    key: "compression_check",
    valueType: { type: "number" },
    name: "Compression resistance check",
    verificationExpression: "\\frac{\\left|N_{Ed}\\right|}{N_{c,Rd}} \\leq 1.0",
    meta: { sectionRef: "6.2.4", verificationRef: "(6.9)" },
    children: [{ nodeId: "abs_N_Ed" }, { nodeId: "N_c_Rd" }],
  },
  {
    id: "abs_N_Ed",
    type: "derived",
    key: "abs_N_Ed",
    valueType: { type: "number" },
    name: "Design compression force magnitude",
    expression: "\\left|N_{Ed}\\right|",
    unit: "\\mathrm{N}",
    children: [{ nodeId: "N_Ed" }],
  },
  {
    id: "N_Ed",
    type: "user-input",
    key: "N_Ed",
    valueType: { type: "number" },
    name: "Design compression force",
    symbol: "N_{Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "N_c_Rd",
    type: "formula",
    key: "N_c_Rd",
    valueType: { type: "number" },
    name: "Design resistance to normal forces",
    symbol: "N_{c,Rd}",
    expression: "\\frac{A \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.4", formulaRef: "(6.10)" },
    children: [{ nodeId: "A" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "A",
    type: "user-input",
    key: "A",
    valueType: { type: "number" },
    name: "Cross-sectional area",
    symbol: "A",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "fy",
    type: "user-input",
    key: "fy",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
