import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "ratio",
    type: "check",
    key: "ratio",
    valueType: { type: "number" },
    name: "Bending and shear resistance check about z-z",
    verificationExpression:
      "\\frac{\\left|M_{z,Ed}\\right|}{M_{z,V,Rd}} \\leq 1.0",
    meta: { sectionRef: "6.2.8", verificationRef: "(6.29)" },
    children: [{ nodeId: "M_z_Ed_Nmm" }, { nodeId: "M_z_V_Rd_Nmm" }],
  },
  {
    id: "M_z_Ed_Nmm",
    type: "user-input",
    key: "M_z_Ed_Nmm",
    valueType: { type: "number" },
    name: "Design bending moment about z-z",
    symbol: "M_{z,Ed}",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "M_z_V_Rd_Nmm",
    type: "derived",
    key: "M_z_V_Rd_Nmm",
    valueType: { type: "number" },
    name: "Reduced bending resistance about z-z under shear",
    symbol: "M_{z,V,Rd}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.8", paragraphRef: "(3)" },
    children: [
      { nodeId: "M_z_V_Rd_i_Nmm", when: { eq: ["shape", { value: "I" }] } },
      {
        nodeId: "M_z_V_Rd_rhs_chs_Nmm",
        when: {
          or: [
            { eq: ["shape", { value: "RHS" }] },
            { eq: ["shape", { value: "CHS" }] },
          ],
        },
      },
    ],
  },
  {
    id: "M_z_V_Rd_i_Nmm",
    type: "derived",
    key: "M_z_V_Rd_i_Nmm",
    valueType: { type: "number" },
    name: "I-section reduced bending resistance about z-z under shear",
    symbol: "M_{z,V,Rd,i}",
    expression:
      "\\frac{\\left(W_{z,res} - \\rho_y\\left(W_{z,res} - W_{z,web}\\right)\\right) \\cdot f_y}{\\gamma_{M0}} \\leq M_{c,z,Rd}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.8", paragraphRef: "(3)" },
    children: [
      { nodeId: "W_z_res_mm3" },
      { nodeId: "W_z_web_mm3" },
      { nodeId: "rho_y" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "M_z_V_Rd_rhs_chs_Nmm",
    type: "derived",
    key: "M_z_V_Rd_rhs_chs_Nmm",
    valueType: { type: "number" },
    name: "RHS/CHS reduced bending resistance about z-z under shear",
    symbol: "M_{z,V,Rd,RHS/CHS}",
    expression:
      "\\frac{\\left(W_{z,res}(1-\\rho_y)\\right) \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.8", paragraphRef: "(3)" },
    children: [
      { nodeId: "W_z_res_mm3" },
      { nodeId: "rho_y" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "W_z_res_mm3",
    type: "derived",
    key: "W_z_res_mm3",
    valueType: { type: "number" },
    name: "Class-dependent resistance modulus about z-z",
    symbol: "W_{z,res}",
    unit: "\\mathrm{mm^{3}}",
    children: [
      {
        nodeId: "Wpl_z_mm3",
        when: {
          or: [
            { eq: ["section_class", { value: 1 }] },
            { eq: ["section_class", { value: 2 }] },
          ],
        },
      },
      { nodeId: "Wel_z_mm3", when: { eq: ["section_class", { value: 3 }] } },
    ],
  },
  {
    id: "W_z_web_mm3",
    type: "derived",
    key: "W_z_web_mm3",
    valueType: { type: "number" },
    name: "Web contribution to plastic modulus about z-z",
    symbol: "W_{z,web}",
    expression: "\\frac{t_w^2(h_mm-2t_f)}{4}",
    unit: "\\mathrm{mm^{3}}",
    children: [{ nodeId: "tw_mm" }, { nodeId: "h_mm" }, { nodeId: "tf_mm" }],
  },
  {
    id: "Wpl_z_mm3",
    type: "user-input",
    key: "Wpl_z_mm3",
    valueType: { type: "number" },
    name: "Plastic section modulus about z-z",
    symbol: "W_{pl,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wel_z_mm3",
    type: "user-input",
    key: "Wel_z_mm3",
    valueType: { type: "number" },
    name: "Elastic section modulus about z-z",
    symbol: "W_{el,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "tw_mm",
    type: "user-input",
    key: "tw_mm",
    valueType: { type: "number" },
    name: "Web thickness",
    symbol: "t_w",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "h_mm",
    type: "user-input",
    key: "h_mm",
    valueType: { type: "number" },
    name: "Section depth",
    symbol: "h_mm",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tf_mm",
    type: "user-input",
    key: "tf_mm",
    valueType: { type: "number" },
    name: "Flange thickness",
    symbol: "t_f",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "rho_y",
    type: "derived",
    key: "rho_y",
    valueType: { type: "number" },
    name: "Shear reduction factor",
    symbol: "\\rho_y",
    children: [
      { nodeId: "rho_y_1", when: { lte: ["u_y", { value: 0.5 }] } },
      { nodeId: "rho_y_2", when: { gt: ["u_y", { value: 0.5 }] } },
    ],
  },
  {
    id: "rho_y_1",
    type: "derived",
    key: "rho_y_1",
    valueType: { type: "number" },
    name: "Shear reduction factor for low-shear branch",
    symbol: "\\rho_{y,1}",
    expression: "0",
    children: [],
  },
  {
    id: "rho_y_2",
    type: "derived",
    key: "rho_y_2",
    valueType: { type: "number" },
    name: "Shear reduction factor for high-shear branch",
    symbol: "\\rho_{y,2}",
    expression: "\\left(2u_y - 1\\right)^2",
    children: [{ nodeId: "u_y" }],
  },
  {
    id: "V_y_Ed_N",
    type: "user-input",
    key: "V_y_Ed_N",
    valueType: { type: "number" },
    name: "Design shear force about y-y",
    symbol: "V_{y,Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "V_pl_y_Rd_N",
    type: "formula",
    key: "V_pl_y_Rd_N",
    valueType: { type: "number" },
    name: "Plastic shear resistance about y-y",
    symbol: "V_{pl,y,Rd}",
    expression: "\\frac{A_{v,y} \\cdot f_y}{\\sqrt{3}\\,\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.6", formulaRef: "(6.18)" },
    children: [
      { nodeId: "Av_y_mm2" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "u_y",
    type: "derived",
    key: "u_y",
    valueType: { type: "number" },
    name: "Shear utilization about y-y",
    symbol: "u_y",
    expression: "\\left|V_{y,Ed}\\right| / V_{pl,y,Rd}",
    children: [{ nodeId: "V_y_Ed_N" }, { nodeId: "V_pl_y_Rd_N" }],
  },
  {
    id: "Av_y_mm2",
    type: "user-input",
    key: "Av_y_mm2",
    valueType: { type: "number" },
    name: "Shear area about y-y",
    symbol: "A_{v,y}",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "fy_MPa",
    type: "user-input",
    key: "fy_MPa",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
