import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "bending_y_check",
    type: "check",
    key: "bending_y_check",
    valueType: { type: "number" },
    name: "Bending resistance check about y-y",
    verificationExpression:
      "\\frac{\\left|M_{y,Ed}\\right|}{M_{c,y,Rd}} \\leq 1.0",
    meta: { sectionRef: "6.2.5", verificationRef: "(6.12)" },
    children: [{ nodeId: "abs_M_y_Ed" }, { nodeId: "M_c_y_Rd" }],
  },
  {
    id: "abs_M_y_Ed",
    type: "derived",
    key: "abs_M_y_Ed",
    valueType: { type: "number" },
    name: "Design bending moment magnitude about y-y",
    expression: "\\left|M_{y,Ed}\\right|",
    unit: "N·mm",
    children: [{ nodeId: "M_y_Ed" }],
  },
  {
    id: "M_y_Ed",
    type: "user-input",
    key: "M_y_Ed",
    valueType: { type: "number" },
    name: "Design bending moment about y-y",
    symbol: "M_{y,Ed}",
    unit: "N·mm",
    children: [],
  },
  {
    id: "M_c_y_Rd",
    type: "formula",
    key: "M_c_y_Rd",
    valueType: { type: "number" },
    name: "Design resistance moment about y-y",
    symbol: "M_{c,y,Rd}",
    expression: "\\frac{W_{y,res} \\cdot f_y}{\\gamma_{M0}}",
    unit: "N·mm",
    meta: { sectionRef: "6.2.5", formulaRef: "(6.13)" },
    children: [{ nodeId: "W_y_res" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "W_y_res",
    type: "derived",
    key: "W_y_res",
    valueType: { type: "number" },
    name: "Class-dependent resistance modulus about y-y",
    expression: "\\text{class 1/2 ? }W_{pl,y}:W_{el,y}",
    unit: "\\mathrm{mm}^3",
    children: [
      { nodeId: "section_class" },
      {
        nodeId: "W_y_res_class12",
        when: {
          or: [{ eq: ["section_class", 1] }, { eq: ["section_class", 2] }],
        },
      },
      {
        nodeId: "W_y_res_class3",
        when: { eq: ["section_class", 3] },
      },
    ],
  },
  {
    id: "W_y_res_class12",
    type: "derived",
    key: "W_y_res_class12",
    valueType: { type: "number" },
    name: "Class 1/2 resistance modulus about y-y",
    expression: "W_{pl,y}",
    unit: "\\mathrm{mm}^3",
    children: [{ nodeId: "Wpl_y" }],
  },
  {
    id: "W_y_res_class3",
    type: "derived",
    key: "W_y_res_class3",
    valueType: { type: "number" },
    name: "Class 3 resistance modulus about y-y",
    expression: "W_{el,y}",
    unit: "\\mathrm{mm}^3",
    children: [{ nodeId: "Wel_y" }],
  },
  {
    id: "section_class",
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    name: "Section class",
    symbol: "\\text{class}",
    children: [],
  },
  {
    id: "Wpl_y",
    type: "user-input",
    key: "Wpl_y",
    valueType: { type: "number" },
    name: "Plastic section modulus about y-y",
    symbol: "W_{pl,y}",
    unit: "\\mathrm{mm}^3",
    children: [],
  },
  {
    id: "Wel_y",
    type: "user-input",
    key: "Wel_y",
    valueType: { type: "number" },
    name: "Elastic section modulus about y-y",
    symbol: "W_{el,y}",
    unit: "\\mathrm{mm}^3",
    children: [],
  },
  {
    id: "fy",
    type: "user-input",
    key: "fy",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "MPa",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
