import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "bending_z_shear_check",
    type: "check",
    key: "bending_z_shear_check",
    valueType: { type: "number" },
    name: "Bending and shear resistance check about z-z",
    verificationExpression:
      "\\frac{\\left|M_{z,Ed}\\right|}{M_{z,V,Rd}} \\leq 1.0",
    meta: { sectionRef: "6.2.8", verificationRef: "(6.29)" },
    children: [{ nodeId: "abs_M_z_Ed" }, { nodeId: "M_z_V_Rd" }],
  },
  {
    id: "abs_M_z_Ed",
    type: "derived",
    key: "abs_M_z_Ed",
    valueType: { type: "number" },
    name: "Design bending moment magnitude about z-z",
    expression: "\\left|M_{z,Ed}\\right|",
    unit: "N·mm",
    children: [{ nodeId: "M_z_Ed" }],
  },
  {
    id: "M_z_Ed",
    type: "user-input",
    key: "M_z_Ed",
    valueType: { type: "number" },
    name: "Design bending moment about z-z",
    symbol: "M_{z,Ed}",
    unit: "N·mm",
    children: [],
  },
  {
    id: "M_z_V_Rd",
    type: "formula",
    key: "M_z_V_Rd",
    valueType: { type: "number" },
    name: "Reduced bending resistance about z-z under shear",
    symbol: "M_{z,V,Rd}",
    expression: "\\frac{W_{z,eff} \\cdot f_y}{\\gamma_{M0}}",
    unit: "N·mm",
    meta: { sectionRef: "6.2.8", formulaRef: "(6.30)" },
    children: [{ nodeId: "W_z_eff" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "section_class",
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    name: "Section class",
    symbol: "\\text{class}",
    children: [],
  },
  {
    id: "W_z_eff",
    type: "derived",
    key: "W_z_eff",
    valueType: { type: "number" },
    name: "Effective resistance modulus about z-z under shear",
    expression: "W_{z,res} - \\rho_y\\left(W_{z,res} - W_{z,web}\\right)",
    unit: "\\mathrm{mm}^3",
    children: [
      { nodeId: "section_shape" },
      {
        nodeId: "W_z_eff_i",
        when: { eq: ["section_shape", "I"] },
      },
      {
        nodeId: "W_z_eff_rhs",
        when: { eq: ["section_shape", "RHS"] },
      },
      {
        nodeId: "W_z_eff_chs",
        when: { eq: ["section_shape", "CHS"] },
      },
    ],
  },
  {
    id: "W_z_eff_i",
    type: "derived",
    key: "W_z_eff_i",
    valueType: { type: "number" },
    name: "I-section effective resistance modulus about z-z under shear",
    expression: "W_{z,res} - \\rho_y\\left(W_{z,res} - W_{z,web}\\right)",
    unit: "\\mathrm{mm}^3",
    children: [{ nodeId: "W_z_res" }, { nodeId: "W_z_web" }, { nodeId: "rho_y" }],
  },
  {
    id: "W_z_eff_rhs",
    type: "derived",
    key: "W_z_eff_rhs",
    valueType: { type: "number" },
    name: "RHS section effective resistance modulus about z-z under shear",
    expression: "W_{z,res}(1-\\rho_y)",
    unit: "\\mathrm{mm}^3",
    children: [{ nodeId: "W_z_res" }, { nodeId: "rho_y" }],
  },
  {
    id: "W_z_eff_chs",
    type: "derived",
    key: "W_z_eff_chs",
    valueType: { type: "number" },
    name: "CHS section effective resistance modulus about z-z under shear",
    expression: "W_{z,res}(1-\\rho_y)",
    unit: "\\mathrm{mm}^3",
    children: [{ nodeId: "W_z_res" }, { nodeId: "rho_y" }],
  },
  {
    id: "W_z_res",
    type: "derived",
    key: "W_z_res",
    valueType: { type: "number" },
    name: "Class-dependent resistance modulus about z-z",
    expression: "\\text{class 1/2 ? }W_{pl,z}:W_{el,z}",
    unit: "\\mathrm{mm}^3",
    children: [
      { nodeId: "section_class" },
      {
        nodeId: "W_z_res_class12",
        when: {
          or: [{ eq: ["section_class", 1] }, { eq: ["section_class", 2] }],
        },
      },
      {
        nodeId: "W_z_res_class3",
        when: { eq: ["section_class", 3] },
      },
    ],
  },
  {
    id: "W_z_res_class12",
    type: "derived",
    key: "W_z_res_class12",
    valueType: { type: "number" },
    name: "Class 1/2 resistance modulus about z-z",
    expression: "W_{pl,z}",
    unit: "\\mathrm{mm}^3",
    children: [{ nodeId: "Wpl_z" }],
  },
  {
    id: "W_z_res_class3",
    type: "derived",
    key: "W_z_res_class3",
    valueType: { type: "number" },
    name: "Class 3 resistance modulus about z-z",
    expression: "W_{el,z}",
    unit: "\\mathrm{mm}^3",
    children: [{ nodeId: "Wel_z" }],
  },
  {
    id: "W_z_web",
    type: "derived",
    key: "W_z_web",
    valueType: { type: "number" },
    name: "Web contribution to plastic modulus about z-z",
    expression: "\\frac{t_w^2(h-2t_f)}{4}",
    unit: "\\mathrm{mm}^3",
    children: [{ nodeId: "tw" }, { nodeId: "h" }, { nodeId: "tf" }],
  },
  {
    id: "Wpl_z",
    type: "user-input",
    key: "Wpl_z",
    valueType: { type: "number" },
    name: "Plastic section modulus about z-z",
    symbol: "W_{pl,z}",
    unit: "\\mathrm{mm}^3",
    children: [],
  },
  {
    id: "Wel_z",
    type: "user-input",
    key: "Wel_z",
    valueType: { type: "number" },
    name: "Elastic section modulus about z-z",
    symbol: "W_{el,z}",
    unit: "\\mathrm{mm}^3",
    children: [],
  },
  {
    id: "section_shape",
    type: "user-input",
    key: "section_shape",
    valueType: { type: "string", literal: ["I", "RHS", "CHS"] },
    name: "Section shape family",
    symbol: "\\text{shape}",
    children: [],
  },
  {
    id: "tw",
    type: "user-input",
    key: "tw",
    valueType: { type: "number" },
    name: "Web thickness",
    symbol: "t_w",
    unit: "mm",
    children: [],
  },
  {
    id: "h",
    type: "user-input",
    key: "h",
    valueType: { type: "number" },
    name: "Section depth",
    symbol: "h",
    unit: "mm",
    children: [],
  },
  {
    id: "tf",
    type: "user-input",
    key: "tf",
    valueType: { type: "number" },
    name: "Flange thickness",
    symbol: "t_f",
    unit: "mm",
    children: [],
  },
  {
    id: "rho_y",
    type: "derived",
    key: "rho_y",
    valueType: { type: "number" },
    name: "Shear reduction factor",
    expression:
      "\\left(\\frac{2\\left|V_{y,Ed}\\right|}{V_{pl,y,Rd}} - 1\\right)^2 \\text{ for } \\frac{\\left|V_{y,Ed}\\right|}{V_{pl,y,Rd}} > 0.5, \\text{ else } 0",
    symbol: "\\rho_y",
    children: [{ nodeId: "rho_ratio" }],
  },
  {
    id: "rho_ratio",
    type: "derived",
    key: "rho_ratio",
    valueType: { type: "number" },
    name: "Shear utilization ratio about y-y",
    expression: "\\dfrac{\\left|V_{y,Ed}\\right|}{V_{pl,y,Rd}}",
    children: [{ nodeId: "abs_V_y_Ed" }, { nodeId: "V_pl_y_Rd" }],
  },
  {
    id: "abs_V_y_Ed",
    type: "derived",
    key: "abs_V_y_Ed",
    valueType: { type: "number" },
    name: "Design shear force magnitude about y-y",
    expression: "\\left|V_{y,Ed}\\right|",
    unit: "N",
    children: [{ nodeId: "V_y_Ed" }],
  },
  {
    id: "V_y_Ed",
    type: "user-input",
    key: "V_y_Ed",
    valueType: { type: "number" },
    name: "Design shear force about y-y",
    symbol: "V_{y,Ed}",
    unit: "N",
    children: [],
  },
  {
    id: "V_pl_y_Rd",
    type: "formula",
    key: "V_pl_y_Rd",
    valueType: { type: "number" },
    name: "Plastic shear resistance about y-y",
    symbol: "V_{pl,y,Rd}",
    expression: "\\frac{A_{v,y} \\cdot f_y}{\\sqrt{3}\\,\\gamma_{M0}}",
    unit: "N",
    meta: { sectionRef: "6.2.6", formulaRef: "(6.18)" },
    children: [
      { nodeId: "Av_y" },
      { nodeId: "fy" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "Av_y",
    type: "user-input",
    key: "Av_y",
    valueType: { type: "number" },
    name: "Shear area about y-y",
    symbol: "A_{v,y}",
    unit: "\\mathrm{mm}^2",
    children: [],
  },
  {
    id: "fy",
    type: "user-input",
    key: "fy",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "MPa",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
