import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "bending_z_shear_check",
    type: "check",
    key: "bending_z_shear_check",
    valueType: { type: "number" },
    name: "Bending and shear resistance check about z-z",
    verificationExpression:
      "\\frac{\\left|M_{z,Ed}\\right|}{M_{z,V,Rd}} \\leq 1.0",
    meta: { sectionRef: "6.2.8", verificationRef: "(6.29)" },
    children: [{ nodeId: "M_z_Ed" }, { nodeId: "M_z_V_Rd" }],
  },
  {
    id: "M_z_Ed",
    type: "user-input",
    key: "M_z_Ed",
    valueType: { type: "number" },
    name: "Design bending moment about z-z",
    symbol: "M_{z,Ed}",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "M_z_V_Rd",
    type: "derived",
    key: "M_z_V_Rd",
    valueType: { type: "number" },
    name: "Reduced bending resistance about z-z under shear",
    symbol: "M_{z,V,Rd}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.8", paragraphRef: "(3)" },
    children: [
      {
        nodeId: "M_z_V_Rd_i",
        when: { eq: ["section_shape", { value: "I" }] },
      },
      {
        nodeId: "M_z_V_Rd_rhs_chs",
        when: {
          or: [
            { eq: ["section_shape", { value: "RHS" }] },
            { eq: ["section_shape", { value: "CHS" }] },
          ],
        },
      },
    ],
  },
  {
    id: "M_z_V_Rd_i",
    type: "derived",
    key: "M_z_V_Rd_i",
    valueType: { type: "number" },
    name: "I-section reduced bending resistance about z-z under shear",
    symbol: "M_{z,V,Rd,i}",
    expression:
      "\\frac{\\left(W_{z,res} - \\rho_y\\left(W_{z,res} - W_{z,web}\\right)\\right) \\cdot f_y}{\\gamma_{M0}} \\leq M_{c,z,Rd}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.8", paragraphRef: "(3)" },
    children: [
      { nodeId: "W_z_res" },
      { nodeId: "W_z_web" },
      { nodeId: "rho_y" },
      { nodeId: "fy" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "M_z_V_Rd_rhs_chs",
    type: "derived",
    key: "M_z_V_Rd_rhs_chs",
    valueType: { type: "number" },
    name: "RHS/CHS reduced bending resistance about z-z under shear",
    symbol: "M_{z,V,Rd,RHS/CHS}",
    expression:
      "\\frac{\\left(W_{z,res}(1-\\rho_y)\\right) \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.8", paragraphRef: "(3)" },
    children: [
      { nodeId: "W_z_res" },
      { nodeId: "rho_y" },
      { nodeId: "fy" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "W_z_res",
    type: "derived",
    key: "W_z_res",
    valueType: { type: "number" },
    name: "Class-dependent resistance modulus about z-z",
    symbol: "W_{z,res}",
    unit: "\\mathrm{mm^{3}}",
    children: [
      {
        nodeId: "Wpl_z",
        when: {
          or: [{ eq: ["section_class", { value: 1 }] }, { eq: ["section_class", { value: 2 }] }],
        },
      },
      {
        nodeId: "Wel_z",
        when: { eq: ["section_class", { value: 3 }] },
      },
    ],
  },
  {
    id: "W_z_web",
    type: "derived",
    key: "W_z_web",
    valueType: { type: "number" },
    name: "Web contribution to plastic modulus about z-z",
    symbol: "W_{z,web}",
    expression: "\\frac{t_w^2(h-2t_f)}{4}",
    unit: "\\mathrm{mm^{3}}",
    children: [{ nodeId: "tw" }, { nodeId: "h" }, { nodeId: "tf" }],
  },
  {
    id: "Wpl_z",
    type: "user-input",
    key: "Wpl_z",
    valueType: { type: "number" },
    name: "Plastic section modulus about z-z",
    symbol: "W_{pl,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wel_z",
    type: "user-input",
    key: "Wel_z",
    valueType: { type: "number" },
    name: "Elastic section modulus about z-z",
    symbol: "W_{el,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "tw",
    type: "user-input",
    key: "tw",
    valueType: { type: "number" },
    name: "Web thickness",
    symbol: "t_w",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "h",
    type: "user-input",
    key: "h",
    valueType: { type: "number" },
    name: "Section depth",
    symbol: "h",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tf",
    type: "user-input",
    key: "tf",
    valueType: { type: "number" },
    name: "Flange thickness",
    symbol: "t_f",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "rho_y",
    type: "derived",
    key: "rho_y",
    valueType: { type: "number" },
    name: "Shear reduction factor",
    symbol: "\\rho_y",
    children: [
      {
        nodeId: "rho_y_1",
        when: { lte: ["u_y", { value: 0.5 }] },
      },
      {
        nodeId: "rho_y_2",
        when: { gt: ["u_y", { value: 0.5 }] },
      },
    ],
  },
  {
    id: "rho_y_1",
    type: "derived",
    key: "rho_y_1",
    valueType: { type: "number" },
    name: "Shear reduction factor for low-shear branch",
    symbol: "\\rho_{y,1}",
    expression: "0",
    children: [],
  },
  {
    id: "rho_y_2",
    type: "derived",
    key: "rho_y_2",
    valueType: { type: "number" },
    name: "Shear reduction factor for high-shear branch",
    symbol: "\\rho_{y,2}",
    expression: "\\left(2u_y - 1\\right)^2",
    children: [{ nodeId: "u_y" }],
  },
  {
    id: "V_y_Ed",
    type: "user-input",
    key: "V_y_Ed",
    valueType: { type: "number" },
    name: "Design shear force about y-y",
    symbol: "V_{y,Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "V_pl_y_Rd",
    type: "formula",
    key: "V_pl_y_Rd",
    valueType: { type: "number" },
    name: "Plastic shear resistance about y-y",
    symbol: "V_{pl,y,Rd}",
    expression: "\\frac{A_{v,y} \\cdot f_y}{\\sqrt{3}\\,\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.6", formulaRef: "(6.18)" },
    children: [
      { nodeId: "Av_y" },
      { nodeId: "fy" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "u_y",
    type: "derived",
    key: "u_y",
    valueType: { type: "number" },
    name: "Shear utilization about y-y",
    symbol: "u_y",
    expression: "\\left|V_{y,Ed}\\right| / V_{pl,y,Rd}",
    children: [{ nodeId: "V_y_Ed" }, { nodeId: "V_pl_y_Rd" }],
  },
  {
    id: "Av_y",
    type: "user-input",
    key: "Av_y",
    valueType: { type: "number" },
    name: "Shear area about y-y",
    symbol: "A_{v,y}",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "fy",
    type: "user-input",
    key: "fy",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
