import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "bending_z_axial_check",
    type: "check",
    key: "bending_z_axial_check",
    valueType: { type: "number" },
    name: "Bending and axial resistance check about z-z",
    verificationExpression:
      "\\text{class 1/2: }\\frac{\\left|M_{z,Ed}\\right|}{M_{N,z,Rd}}\\leq1.0\\ ;\\ \\text{class 3: }\\frac{\\sigma_{x,Ed}}{f_y/\\gamma_{M0}}\\leq1.0",
    meta: { sectionRef: "6.2.9", verificationRef: "(6.31),(6.42)" },
    children: [
      {
        nodeId: "utilization_class12",
        when: {
          or: [{ eq: ["section_class", { value: 1 }] }, { eq: ["section_class", { value: 2 }] }],
        },
      },
      {
        nodeId: "utilization_class3",
        when: { eq: ["section_class", { value: 3 }] },
      },
    ],
  },
  {
    id: "utilization_class12",
    type: "derived",
    key: "utilization_class12",
    valueType: { type: "number" },
    name: "Class 1/2 utilization ratio about z-z",
    expression: "\\left|M_{z,Ed}\\right|/M_{N,z,Rd}",
    children: [{ nodeId: "abs_M_z_Ed" }, { nodeId: "M_N_z_Rd" }],
  },
  {
    id: "M_N_z_Rd",
    type: "formula",
    key: "M_N_z_Rd",
    valueType: { type: "number" },
    name: "Reduced bending resistance about z-z under axial force",
    symbol: "M_{N,z,Rd}",
    expression: "M_{pl,z,Rd} \\cdot k_z",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.38)" },
    children: [{ nodeId: "M_pl_z_Rd" }, { nodeId: "k_z" }],
  },
  {
    id: "M_pl_z_Rd",
    type: "formula",
    key: "M_pl_z_Rd",
    valueType: { type: "number" },
    name: "Design bending resistance about z-z",
    symbol: "M_{pl,z,Rd}",
    expression: "\\frac{W_{pl,z} \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.5", formulaRef: "(6.13)" },
    children: [{ nodeId: "Wpl_z" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "k_z",
    type: "derived",
    key: "k_z",
    valueType: { type: "number" },
    name: "Axial reduction factor for z-z branch",
    expression: "n \\leq a_f ? 1 : 1-((n-a_f)/(1-a_f))^2",
    children: [{ nodeId: "is_n_le_a_f" }, { nodeId: "n" }, { nodeId: "a_f" }],
  },
  {
    id: "is_n_le_a_f",
    type: "derived",
    key: "is_n_le_a_f",
    valueType: { type: "number" },
    name: "Threshold indicator for n <= a_f",
    expression: "n \\leq a_f",
    children: [{ nodeId: "n" }, { nodeId: "a_f" }],
  },
  {
    id: "a_f",
    type: "derived",
    key: "a_f",
    valueType: { type: "number" },
    name: "Limited reduction parameter for z-z branch",
    expression: "\\min(a_f,0.5)",
    children: [
      { nodeId: "section_shape" },
      { nodeId: "a_f_i", when: { eq: ["section_shape", { value: "I" }] } },
      { nodeId: "a_f_rhs", when: { eq: ["section_shape", { value: "RHS" }] } },
      { nodeId: "a_f_chs", when: { eq: ["section_shape", { value: "CHS" }] } },
    ],
  },
  {
    id: "a_f_i",
    type: "derived",
    key: "a_f_i",
    valueType: { type: "number" },
    name: "I-section reduction parameter for z-z branch",
    expression: "(A-2b t_f)/A",
    children: [{ nodeId: "A" }, { nodeId: "b" }, { nodeId: "tf" }],
  },
  {
    id: "a_f_rhs",
    type: "derived",
    key: "a_f_rhs",
    valueType: { type: "number" },
    name: "RHS section reduction parameter for z-z branch",
    expression: "(A-2ht)/A",
    children: [{ nodeId: "A" }, { nodeId: "h" }, { nodeId: "t" }],
  },
  {
    id: "a_f_chs",
    type: "derived",
    key: "a_f_chs",
    valueType: { type: "number" },
    name: "CHS section reduction parameter for z-z branch",
    expression: "0.5",
    children: [{ nodeId: "section_shape" }],
  },
  {
    id: "n",
    type: "derived",
    key: "n",
    valueType: { type: "number" },
    name: "Axial force ratio",
    symbol: "n",
    expression: "\\frac{\\left|N_{Ed}\\right|}{N_{pl,Rd}}",
    children: [{ nodeId: "abs_N_Ed" }, { nodeId: "N_pl_Rd" }],
  },
  {
    id: "abs_N_Ed",
    type: "derived",
    key: "abs_N_Ed",
    valueType: { type: "number" },
    name: "Design axial force magnitude",
    expression: "\\left|N_{Ed}\\right|",
    unit: "\\mathrm{N}",
    children: [{ nodeId: "N_Ed" }],
  },
  {
    id: "N_Ed",
    type: "user-input",
    key: "N_Ed",
    valueType: { type: "number" },
    name: "Design axial force",
    symbol: "N_{Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "N_pl_Rd",
    type: "formula",
    key: "N_pl_Rd",
    valueType: { type: "number" },
    name: "Plastic resistance to normal force",
    symbol: "N_{pl,Rd}",
    expression: "\\frac{A \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.4", formulaRef: "(6.10)" },
    children: [{ nodeId: "A" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "utilization_class3",
    type: "derived",
    key: "utilization_class3",
    valueType: { type: "number" },
    name: "Class 3 stress utilization ratio",
    expression: "\\sigma_{x,Ed}/(f_y/\\gamma_{M0})",
    children: [{ nodeId: "sigma_x_class3" }, { nodeId: "sigma_limit" }],
  },
  {
    id: "sigma_x_class3",
    type: "derived",
    key: "sigma_x_class3",
    valueType: { type: "number" },
    name: "Maximum longitudinal stress for class 3",
    expression: "\\sigma_N+\\sigma_{M,z}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "sigma_N" }, { nodeId: "sigma_M_z" }],
  },
  {
    id: "sigma_N",
    type: "derived",
    key: "sigma_N",
    valueType: { type: "number" },
    name: "Axial stress contribution",
    expression: "\\left|N_{Ed}\\right|/A",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_N_Ed" }, { nodeId: "A" }],
  },
  {
    id: "sigma_M_z",
    type: "derived",
    key: "sigma_M_z",
    valueType: { type: "number" },
    name: "z-z bending stress contribution",
    expression: "\\left|M_{z,Ed}\\right|/W_{el,z}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_M_z_Ed" }, { nodeId: "Wel_z" }],
  },
  {
    id: "abs_M_z_Ed",
    type: "derived",
    key: "abs_M_z_Ed",
    valueType: { type: "number" },
    name: "Design bending moment magnitude about z-z",
    expression: "\\left|M_{z,Ed}\\right|",
    unit: "\\mathrm{N\\cdot mm}",
    children: [{ nodeId: "M_z_Ed" }],
  },
  {
    id: "M_z_Ed",
    type: "user-input",
    key: "M_z_Ed",
    valueType: { type: "number" },
    name: "Design bending moment about z-z",
    symbol: "M_{z,Ed}",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "sigma_limit",
    type: "formula",
    key: "sigma_limit",
    valueType: { type: "number" },
    name: "Class 3 stress limit",
    symbol: "f_y/\\gamma_{M0}",
    expression: "\\frac{f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{MPa}",
    meta: { sectionRef: "6.2.9.2", formulaRef: "(6.42)" },
    children: [{ nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "section_class",
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    name: "Section class",
    symbol: "\\text{class}",
    children: [],
  },
  {
    id: "section_shape",
    type: "user-input",
    key: "section_shape",
    valueType: { type: "string", oneOf: ["I", "RHS", "CHS"] },
    name: "Section shape family",
    symbol: "\\text{shape}",
    children: [],
  },
  {
    id: "A",
    type: "user-input",
    key: "A",
    valueType: { type: "number" },
    name: "Cross-sectional area",
    symbol: "A",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "h",
    type: "user-input",
    key: "h",
    valueType: { type: "number" },
    name: "Section depth",
    symbol: "h",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "b",
    type: "user-input",
    key: "b",
    valueType: { type: "number" },
    name: "Section width",
    symbol: "b",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tf",
    type: "user-input",
    key: "tf",
    valueType: { type: "number" },
    name: "Flange thickness",
    symbol: "t_f",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "t",
    type: "user-input",
    key: "t",
    valueType: { type: "number" },
    name: "Wall thickness",
    symbol: "t",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "Wpl_z",
    type: "user-input",
    key: "Wpl_z",
    valueType: { type: "number" },
    name: "Plastic section modulus about z-z",
    symbol: "W_{pl,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wel_z",
    type: "user-input",
    key: "Wel_z",
    valueType: { type: "number" },
    name: "Elastic section modulus about z-z",
    symbol: "W_{el,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "fy",
    type: "user-input",
    key: "fy",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
