import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "utilisation",
    type: "check",
    key: "utilisation",
    valueType: { type: "number" },
    name: "Bending and axial resistance check about z-z",
    verificationExpression:
      "\\text{class 1/2: }\\frac{\\left|M_{z,Ed}\\right|}{M_{N,z,Rd}}\\leq1.0\\ ;\\ \\text{class 3: }\\frac{\\sigma_{x,Ed}}{f_y/\\gamma_{M0}}\\leq1.0",
    meta: { sectionRef: "6.2.9", verificationRef: "(6.38),(6.42)" },
    children: [
      {
        nodeId: "utilization_class12",
        when: {
          or: [
            { eq: ["section_class", { value: 1 }] },
            { eq: ["section_class", { value: 2 }] },
          ],
        },
      },
      {
        nodeId: "utilization_class3",
        when: { eq: ["section_class", { value: 3 }] },
      },
    ],
  },
  {
    id: "utilization_class12",
    type: "formula",
    key: "utilization_class12",
    valueType: { type: "number" },
    name: "Class 1/2 utilization ratio about z-z",
    expression: "\\left|M_{z,Ed}\\right|/M_{N,z,Rd}",
    children: [{ nodeId: "M_z_Ed_Nmm" }, { nodeId: "M_N_z_Rd_Nmm" }],
  },
  {
    id: "M_N_z_Rd_Nmm",
    type: "formula",
    key: "M_N_z_Rd_Nmm",
    valueType: { type: "number" },
    name: "Reduced bending resistance about z-z under axial force",
    symbol: "M_{N,z,Rd}",
    expression: "M_{pl,z,Rd} \\cdot k_z",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.38)" },
    children: [{ nodeId: "M_pl_z_Rd_Nmm" }, { nodeId: "k_z" }],
  },
  {
    id: "M_pl_z_Rd_Nmm",
    type: "formula",
    key: "M_pl_z_Rd_Nmm",
    valueType: { type: "number" },
    name: "Design bending resistance about z-z",
    symbol: "M_{pl,z,Rd}",
    expression: "\\frac{W_{pl,z} \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.5", formulaRef: "(6.13)" },
    children: [
      { nodeId: "Wpl_z_mm3" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "k_z",
    type: "formula",
    key: "k_z",
    valueType: { type: "number" },
    name: "Axial reduction factor for z-z branch",
    children: [
      { nodeId: "k_z_i", when: { eq: ["shape", { value: "I" }] } },
      {
        nodeId: "k_z_rhs_chs",
        when: {
          or: [
            { eq: ["shape", { value: "RHS" }] },
            { eq: ["shape", { value: "CHS" }] },
          ],
        },
      },
    ],
  },
  {
    id: "k_z_i",
    type: "formula",
    key: "k_z_i",
    valueType: { type: "number" },
    name: "I-section axial reduction factor for z-z",
    expression:
      "n \\leq a_f \\Rightarrow 1,\\ \\text{else}\\ 1-\\left(\\frac{n-a_f}{1-a_f}\\right)^2",
    children: [{ nodeId: "n" }, { nodeId: "a_f" }],
  },
  {
    id: "k_z_rhs_chs",
    type: "formula",
    key: "k_z_rhs_chs",
    valueType: { type: "number" },
    name: "RHS/CHS axial reduction factor for z-z",
    expression: "\\min\\left(1,\\frac{1-n}{1-0.5a_f}\\right)",
    children: [{ nodeId: "n" }, { nodeId: "a_f" }],
  },
  {
    id: "a_f",
    type: "formula",
    key: "a_f",
    valueType: { type: "number" },
    name: "Limited reduction parameter for z-z branch",
    children: [
      { nodeId: "a_f_i", when: { eq: ["shape", { value: "I" }] } },
      { nodeId: "a_f_rhs", when: { eq: ["shape", { value: "RHS" }] } },
      { nodeId: "a_f_chs", when: { eq: ["shape", { value: "CHS" }] } },
    ],
  },
  {
    id: "a_f_i",
    type: "formula",
    key: "a_f_i",
    valueType: { type: "number" },
    name: "I-section reduction parameter for z-z branch",
    expression: "(A_mm2-2b t_f)/A_mm2",
    children: [{ nodeId: "A_mm2" }, { nodeId: "b_mm" }, { nodeId: "tf_mm" }],
  },
  {
    id: "a_f_rhs",
    type: "formula",
    key: "a_f_rhs",
    valueType: { type: "number" },
    name: "RHS section reduction parameter for z-z branch",
    expression: "(A_mm2-2ht)/A_mm2",
    children: [{ nodeId: "A_mm2" }, { nodeId: "h_mm" }, { nodeId: "t_mm" }],
  },
  {
    id: "a_f_chs",
    type: "formula",
    key: "a_f_chs",
    valueType: { type: "number" },
    name: "CHS section reduction parameter for z-z branch",
    expression: "0.5",
    children: [],
  },
  {
    id: "n",
    type: "formula",
    key: "n",
    valueType: { type: "number" },
    name: "Axial force ratio",
    symbol: "n",
    expression: "\\frac{\\left|N_{Ed}\\right|}{N_{pl,Rd}}",
    children: [{ nodeId: "N_Ed_N" }, { nodeId: "N_pl_Rd_N" }],
  },
  {
    id: "N_Ed_N",
    type: "user-input",
    key: "N_Ed_N",
    valueType: { type: "number" },
    name: "Design axial force",
    symbol: "N_{Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "N_pl_Rd_N",
    type: "formula",
    key: "N_pl_Rd_N",
    valueType: { type: "number" },
    name: "Plastic resistance to normal force",
    symbol: "N_{pl,Rd}",
    expression: "\\frac{A_mm2 \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.4", formulaRef: "(6.10)" },
    children: [
      { nodeId: "A_mm2" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "utilization_class3",
    type: "formula",
    key: "utilization_class3",
    valueType: { type: "number" },
    name: "Class 3 stress utilization ratio",
    expression: "\\sigma_{x,Ed}/(f_y/\\gamma_{M0})",
    children: [{ nodeId: "sigma_x_class3_MPa" }, { nodeId: "sigma_limit_MPa" }],
  },
  {
    id: "sigma_x_class3_MPa",
    type: "formula",
    key: "sigma_x_class3_MPa",
    valueType: { type: "number" },
    name: "Maximum longitudinal stress for class 3",
    expression: "\\sigma_N_MPa+\\sigma_{M,z}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "sigma_N_MPa" }, { nodeId: "sigma_M_z_MPa" }],
  },
  {
    id: "sigma_N_MPa",
    type: "formula",
    key: "sigma_N_MPa",
    valueType: { type: "number" },
    name: "Axial stress contribution",
    expression: "\\left|N_{Ed}\\right|/A_mm2",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "N_Ed_N" }, { nodeId: "A_mm2" }],
  },
  {
    id: "sigma_M_z_MPa",
    type: "formula",
    key: "sigma_M_z_MPa",
    valueType: { type: "number" },
    name: "z-z bending stress contribution",
    expression: "\\left|M_{z,Ed}\\right|/W_{el,z}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "M_z_Ed_Nmm" }, { nodeId: "Wel_z_mm3" }],
  },
  {
    id: "M_z_Ed_Nmm",
    type: "user-input",
    key: "M_z_Ed_Nmm",
    valueType: { type: "number" },
    name: "Design bending moment about z-z",
    symbol: "M_{z,Ed}",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "sigma_limit_MPa",
    type: "formula",
    key: "sigma_limit_MPa",
    valueType: { type: "number" },
    name: "Class 3 stress limit",
    symbol: "f_y/\\gamma_{M0}",
    expression: "\\frac{f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{MPa}",
    meta: { sectionRef: "6.2.9.2", formulaRef: "(6.42)" },
    children: [{ nodeId: "fy_MPa" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "section_class",
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    name: "Section class",
    symbol: "\\text{class}",
    children: [],
  },
  {
    id: "shape",
    type: "user-input",
    key: "shape",
    valueType: { type: "string", oneOf: ["I", "RHS", "CHS"] },
    name: "Section shape family",
    symbol: "\\text{shape}",
    children: [],
  },
  {
    id: "A_mm2",
    type: "user-input",
    key: "A_mm2",
    valueType: { type: "number" },
    name: "Cross-sectional area",
    symbol: "A_mm2",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "h_mm",
    type: "user-input",
    key: "h_mm",
    valueType: { type: "number" },
    name: "Section depth",
    symbol: "h_mm",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "b_mm",
    type: "user-input",
    key: "b_mm",
    valueType: { type: "number" },
    name: "Section width",
    symbol: "b_mm",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tf_mm",
    type: "user-input",
    key: "tf_mm",
    valueType: { type: "number" },
    name: "Flange thickness",
    symbol: "t_f",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "t_mm",
    type: "user-input",
    key: "t_mm",
    valueType: { type: "number" },
    name: "Wall thickness",
    symbol: "t_mm",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "Wpl_z_mm3",
    type: "user-input",
    key: "Wpl_z_mm3",
    valueType: { type: "number" },
    name: "Plastic section modulus about z-z",
    symbol: "W_{pl,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wel_z_mm3",
    type: "user-input",
    key: "Wel_z_mm3",
    valueType: { type: "number" },
    name: "Elastic section modulus about z-z",
    symbol: "W_{el,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "fy_MPa",
    type: "user-input",
    key: "fy_MPa",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
