import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "bending_z_axial_shear_check",
    type: "check",
    key: "bending_z_axial_shear_check",
    valueType: { type: "number" },
    name: "Bending, axial-force, and shear resistance check about z-z",
    verificationExpression:
      "\\text{class 1/2: }\\frac{\\left|M_{z,Ed}\\right|}{M_{NV,z,Rd}}\\leq1.0\\ ;\\ \\text{class 3: }\\frac{\\sigma_{v,Ed}}{f_y/\\gamma_{M0}}\\leq1.0",
    meta: { sectionRef: "6.2.10", verificationRef: "(6.38),(6.42)" },
    children: [
      {
        nodeId: "utilization_class12",
        when: {
          or: [{ eq: ["section_class", 1] }, { eq: ["section_class", 2] }],
        },
      },
      { nodeId: "utilization_class3", when: { eq: ["section_class", 3] } },
    ],
  },
  {
    id: "utilization_class12",
    type: "derived",
    key: "utilization_class12",
    valueType: { type: "number" },
    name: "Class 1/2 utilization ratio about z-z",
    expression: "\\left|M_{z,Ed}\\right|/M_{NV,z,Rd}",
    children: [{ nodeId: "abs_M_z_Ed" }, { nodeId: "M_NV_z_Rd" }],
  },
  {
    id: "M_NV_z_Rd",
    type: "formula",
    key: "M_NV_z_Rd",
    valueType: { type: "number" },
    name: "Reduced bending resistance about z-z under axial force and shear",
    symbol: "M_{NV,z,Rd}",
    expression: "M_{z,V,Rd} \\cdot k_z",
    unit: "N·mm",
    meta: { sectionRef: "6.2.10", formulaRef: "(6.38)" },
    children: [{ nodeId: "M_z_V_Rd" }, { nodeId: "k_z" }],
  },
  {
    id: "M_z_V_Rd",
    type: "formula",
    key: "M_z_V_Rd",
    valueType: { type: "number" },
    name: "Reduced bending resistance about z-z under shear",
    symbol: "M_{z,V,Rd}",
    expression: "\\frac{W_{pl,z,eff} \\cdot f_y}{\\gamma_{M0}}",
    unit: "N·mm",
    meta: { sectionRef: "6.2.8", formulaRef: "(6.30)" },
    children: [{ nodeId: "Wpl_z_eff" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "Wpl_z_eff",
    type: "derived",
    key: "Wpl_z_eff",
    valueType: { type: "number" },
    name: "Effective plastic section modulus about z-z under shear",
    expression: "W_{pl,z} - \\rho_y (W_{pl,z} - W_{pl,z,web})",
    unit: "\\mathrm{mm}^3",
    children: [{ nodeId: "Wpl_z" }, { nodeId: "rho_y" }, { nodeId: "Wpl_z_web" }],
  },
  {
    id: "Wpl_z_web",
    type: "derived",
    key: "Wpl_z_web",
    valueType: { type: "number" },
    name: "Web contribution to plastic section modulus about z-z",
    expression: "A_{v,z} t_w / 4",
    unit: "\\mathrm{mm}^3",
    children: [{ nodeId: "Av_z" }, { nodeId: "tw" }],
  },
  {
    id: "k_z",
    type: "derived",
    key: "k_z",
    valueType: { type: "number" },
    name: "Axial reduction factor",
    expression: "n \\leq a_f ? 1 : 1-((n-a_f)/(1-a_f))^2",
    children: [
      { nodeId: "is_n_le_a_f" },
      { nodeId: "n" },
      { nodeId: "a_f" },
    ],
  },
  {
    id: "is_n_le_a_f",
    type: "derived",
    key: "is_n_le_a_f",
    valueType: { type: "number" },
    name: "Threshold indicator for n <= a_f",
    expression: "n \\leq a_f",
    children: [{ nodeId: "n" }, { nodeId: "a_f" }],
  },
  {
    id: "a_f",
    type: "derived",
    key: "a_f",
    valueType: { type: "number" },
    name: "Limited reduction parameter",
    expression: "min(a_f,0.5)",
    children: [
      { nodeId: "section_shape" },
      { nodeId: "a_f_i", when: { eq: ["section_shape", "I"] } },
      { nodeId: "a_f_rhs", when: { eq: ["section_shape", "RHS"] } },
      { nodeId: "a_f_chs", when: { eq: ["section_shape", "CHS"] } },
    ],
  },
  {
    id: "a_f_i",
    type: "derived",
    key: "a_f_i",
    valueType: { type: "number" },
    name: "I-section reduction parameter for z-z branch",
    expression: "(A-2b t_f)/A",
    children: [{ nodeId: "A" }, { nodeId: "b" }, { nodeId: "tf" }],
  },
  {
    id: "a_f_rhs",
    type: "derived",
    key: "a_f_rhs",
    valueType: { type: "number" },
    name: "RHS section reduction parameter for z-z branch",
    expression: "(A-2ht)/A",
    children: [{ nodeId: "A" }, { nodeId: "h" }, { nodeId: "t" }],
  },
  {
    id: "a_f_chs",
    type: "derived",
    key: "a_f_chs",
    valueType: { type: "number" },
    name: "CHS section reduction parameter for z-z branch",
    expression: "0.5",
    children: [{ nodeId: "section_shape" }],
  },
  {
    id: "n",
    type: "derived",
    key: "n",
    valueType: { type: "number" },
    name: "Axial force ratio",
    symbol: "n",
    expression: "\\frac{\\left|N_{Ed}\\right|}{N_{pl,Rd}}",
    children: [{ nodeId: "abs_N_Ed" }, { nodeId: "N_pl_Rd" }],
  },
  {
    id: "N_pl_Rd",
    type: "formula",
    key: "N_pl_Rd",
    valueType: { type: "number" },
    name: "Plastic resistance to normal force",
    symbol: "N_{pl,Rd}",
    expression: "\\frac{A \\cdot f_y}{\\gamma_{M0}}",
    unit: "N",
    meta: { sectionRef: "6.2.4", formulaRef: "(6.10)" },
    children: [{ nodeId: "A" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "rho_y",
    type: "derived",
    key: "rho_y",
    valueType: { type: "number" },
    name: "Shear reduction factor about y-y",
    expression:
      "\\left(\\frac{2\\left|V_{y,Ed}\\right|}{V_{pl,y,Rd}} - 1\\right)^2 \\text{ for } \\frac{\\left|V_{y,Ed}\\right|}{V_{pl,y,Rd}} > 0.5, \\text{ else } 0",
    symbol: "\\rho_y",
    children: [{ nodeId: "abs_V_y_Ed" }, { nodeId: "V_pl_y_Rd" }],
  },
  {
    id: "V_pl_y_Rd",
    type: "formula",
    key: "V_pl_y_Rd",
    valueType: { type: "number" },
    name: "Plastic shear resistance about y-y",
    symbol: "V_{pl,y,Rd}",
    expression: "\\dfrac{A_{v,y} \\cdot f_y}{\\sqrt{3}\\,\\gamma_{M0}}",
    unit: "N",
    meta: { sectionRef: "6.2.6", formulaRef: "(6.18)" },
    children: [{ nodeId: "Av_y" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "utilization_class3",
    type: "derived",
    key: "utilization_class3",
    valueType: { type: "number" },
    name: "Class 3 Von Mises utilization ratio",
    expression: "\\sigma_{v,Ed}/(f_y/\\gamma_{M0})",
    children: [{ nodeId: "sigma_v_class3" }, { nodeId: "sigma_limit" }],
  },
  {
    id: "sigma_v_class3",
    type: "derived",
    key: "sigma_v_class3",
    valueType: { type: "number" },
    name: "Equivalent Von Mises stress for class 3",
    expression: "\\sqrt{\\sigma_x^2+3\\tau_y^2}",
    unit: "MPa",
    children: [{ nodeId: "sigma_x_class3" }, { nodeId: "tau_y" }],
  },
  {
    id: "sigma_x_class3",
    type: "derived",
    key: "sigma_x_class3",
    valueType: { type: "number" },
    name: "Longitudinal normal stress for class 3",
    expression: "\\sigma_N+\\sigma_{M,z}",
    unit: "MPa",
    children: [{ nodeId: "sigma_N" }, { nodeId: "sigma_M_z" }],
  },
  {
    id: "sigma_N",
    type: "derived",
    key: "sigma_N",
    valueType: { type: "number" },
    name: "Axial stress contribution",
    expression: "\\left|N_{Ed}\\right|/A",
    unit: "MPa",
    children: [{ nodeId: "abs_N_Ed" }, { nodeId: "A" }],
  },
  {
    id: "sigma_M_z",
    type: "derived",
    key: "sigma_M_z",
    valueType: { type: "number" },
    name: "Bending stress contribution about z-z",
    expression: "\\left|M_{z,Ed}\\right|/W_{el,z}",
    unit: "MPa",
    children: [{ nodeId: "abs_M_z_Ed" }, { nodeId: "Wel_z" }],
  },
  {
    id: "tau_y",
    type: "derived",
    key: "tau_y",
    valueType: { type: "number" },
    name: "Average shear stress from V_y",
    expression: "\\left|V_{y,Ed}\\right|/A_{v,y}",
    unit: "MPa",
    children: [{ nodeId: "abs_V_y_Ed" }, { nodeId: "Av_y" }],
  },
  {
    id: "sigma_limit",
    type: "formula",
    key: "sigma_limit",
    valueType: { type: "number" },
    name: "Class 3 stress limit",
    symbol: "f_y/\\gamma_{M0}",
    expression: "\\frac{f_y}{\\gamma_{M0}}",
    unit: "MPa",
    meta: { sectionRef: "6.2.10", formulaRef: "(6.42)" },
    children: [{ nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "abs_M_z_Ed",
    type: "derived",
    key: "abs_M_z_Ed",
    valueType: { type: "number" },
    name: "Design bending moment magnitude about z-z",
    expression: "\\left|M_{z,Ed}\\right|",
    unit: "N·mm",
    children: [{ nodeId: "M_z_Ed" }],
  },
  {
    id: "abs_N_Ed",
    type: "derived",
    key: "abs_N_Ed",
    valueType: { type: "number" },
    name: "Design axial force magnitude",
    expression: "\\left|N_{Ed}\\right|",
    unit: "N",
    children: [{ nodeId: "N_Ed" }],
  },
  {
    id: "abs_V_y_Ed",
    type: "derived",
    key: "abs_V_y_Ed",
    valueType: { type: "number" },
    name: "Design shear force magnitude about y-y",
    expression: "\\left|V_{y,Ed}\\right|",
    unit: "N",
    children: [{ nodeId: "V_y_Ed" }],
  },
  {
    id: "M_z_Ed",
    type: "user-input",
    key: "M_z_Ed",
    valueType: { type: "number" },
    name: "Design bending moment about z-z",
    symbol: "M_{z,Ed}",
    unit: "N·mm",
    children: [],
  },
  {
    id: "N_Ed",
    type: "user-input",
    key: "N_Ed",
    valueType: { type: "number" },
    name: "Design axial force",
    symbol: "N_{Ed}",
    unit: "N",
    children: [],
  },
  {
    id: "V_y_Ed",
    type: "user-input",
    key: "V_y_Ed",
    valueType: { type: "number" },
    name: "Design shear force about y-y",
    symbol: "V_{y,Ed}",
    unit: "N",
    children: [],
  },
  {
    id: "section_shape",
    type: "user-input",
    key: "section_shape",
    valueType: { type: "string", literal: ["I", "RHS", "CHS"] },
    name: "Section shape family",
    symbol: "\\text{shape}",
    children: [],
  },
  {
    id: "section_class",
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    name: "Section class",
    symbol: "\\text{class}",
    children: [],
  },
  {
    id: "A",
    type: "user-input",
    key: "A",
    valueType: { type: "number" },
    name: "Cross-sectional area",
    symbol: "A",
    unit: "\\mathrm{mm}^2",
    children: [],
  },
  {
    id: "b",
    type: "user-input",
    key: "b",
    valueType: { type: "number" },
    name: "Section width",
    symbol: "b",
    unit: "mm",
    children: [],
  },
  {
    id: "h",
    type: "user-input",
    key: "h",
    valueType: { type: "number" },
    name: "Section depth",
    symbol: "h",
    unit: "mm",
    children: [],
  },
  {
    id: "tf",
    type: "user-input",
    key: "tf",
    valueType: { type: "number" },
    name: "Flange thickness",
    symbol: "t_f",
    unit: "mm",
    children: [],
  },
  {
    id: "t",
    type: "user-input",
    key: "t",
    valueType: { type: "number" },
    name: "Wall thickness",
    symbol: "t",
    unit: "mm",
    children: [],
  },
  {
    id: "Wel_z",
    type: "user-input",
    key: "Wel_z",
    valueType: { type: "number" },
    name: "Elastic section modulus about z-z",
    symbol: "W_{el,z}",
    unit: "\\mathrm{mm}^3",
    children: [],
  },
  {
    id: "Wpl_z",
    type: "user-input",
    key: "Wpl_z",
    valueType: { type: "number" },
    name: "Plastic section modulus about z-z",
    symbol: "W_{pl,z}",
    unit: "\\mathrm{mm}^3",
    children: [],
  },
  {
    id: "Av_y",
    type: "user-input",
    key: "Av_y",
    valueType: { type: "number" },
    name: "Shear area about y-y",
    symbol: "A_{v,y}",
    unit: "\\mathrm{mm}^2",
    children: [],
  },
  {
    id: "Av_z",
    type: "user-input",
    key: "Av_z",
    valueType: { type: "number" },
    name: "Shear area about z-z",
    symbol: "A_{v,z}",
    unit: "\\mathrm{mm}^2",
    children: [],
  },
  {
    id: "tw",
    type: "user-input",
    key: "tw",
    valueType: { type: "number" },
    name: "Web or wall thickness",
    symbol: "t_w",
    unit: "mm",
    children: [],
  },
  {
    id: "fy",
    type: "user-input",
    key: "fy",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "MPa",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
