import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    type: "user-input",
    key: "N_Ed_N",
    valueType: { type: "number" },
    id: "N_Ed_N",
    name: "Design compression force",
    symbol: "N_{Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    id: "section_class",
    name: "Section class (1, 2, 3, 4)",
    children: [],
  },
  {
    type: "user-input",
    key: "A_mm2",
    valueType: { type: "number" },
    id: "A_mm2",
    name: "Cross-sectional area",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    type: "user-input",
    key: "fy_MPa",
    valueType: { type: "number" },
    id: "fy_MPa",
    name: "Yield strength",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    type: "user-input",
    key: "E_MPa",
    valueType: { type: "number" },
    id: "E_MPa",
    name: "Elastic modulus",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    type: "user-input",
    key: "Iz_mm4",
    valueType: { type: "number" },
    id: "Iz_mm4",
    name: "Second moment of area z-z",
    unit: "\\mathrm{mm^{4}}",
    children: [],
  },
  {
    type: "user-input",
    key: "L_mm",
    valueType: { type: "number" },
    id: "L_mm",
    name: "Member length",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    type: "user-input",
    key: "k_z",
    valueType: { type: "number" },
    id: "k_z",
    name: "Buckling length factor z",
    children: [],
  },
  {
    type: "user-input",
    key: "alpha_z",
    valueType: { type: "number" },
    id: "alpha_z",
    name: "Imperfection factor z-z",
    symbol: "\\alpha_z",
    children: [],
  },
  {
    type: "coefficient",
    key: "gamma_M1",
    valueType: { type: "number" },
    id: "gamma_M1",
    name: "Partial safety factor",
    symbol: "\\gamma_{M1}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
  {
    type: "constant",
    key: "pi",
    valueType: { type: "number" },
    id: "pi",
    name: "Pi",
    symbol: "\\pi",
    children: [],
  },
  {
    type: "derived",
    key: "N_cr_z_N",
    valueType: { type: "number" },
    id: "N_cr_z_N",
    name: "Elastic critical force z-z",
    symbol: "N_{cr,z}",
    expression: "\\frac{\\pi^2EI_z}{(k_zL)^2}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.3.1.2" },
    children: [
      { nodeId: "pi" },
      { nodeId: "E_MPa" },
      { nodeId: "Iz_mm4" },
      { nodeId: "L_mm" },
      { nodeId: "k_z" },
    ],
  },
  {
    type: "derived",
    key: "lambda_bar_z",
    valueType: { type: "number" },
    id: "lambda_bar_z",
    name: "Non-dimensional slenderness z-z",
    symbol: "\\bar{\\lambda}_z",
    expression: "\\sqrt{\\frac{Af_y}{N_{cr,z}}}",
    children: [
      { nodeId: "A_mm2" },
      { nodeId: "fy_MPa" },
      { nodeId: "N_cr_z_N" },
    ],
  },
  {
    type: "derived",
    key: "phi_z",
    valueType: { type: "number" },
    id: "phi_z",
    name: "Buckling parameter z-z",
    symbol: "\\Phi_z",
    expression:
      "0.5\\left(1+\\alpha_z(\\bar{\\lambda}_z-0.2)+\\bar{\\lambda}_z^2\\right)",
    children: [{ nodeId: "alpha_z" }, { nodeId: "lambda_bar_z" }],
  },
  {
    type: "formula",
    key: "chi_z",
    valueType: { type: "number" },
    id: "chi_z",
    name: "Reduction factor z-z",
    symbol: "\\chi_z",
    expression: "\\frac{1}{\\Phi_z + \\sqrt{\\Phi_z^2 - \\bar{\\lambda}_z^2}}",
    meta: { sectionRef: "6.3.1.2", formulaRef: "(6.49)" },
    children: [{ nodeId: "phi_z" }, { nodeId: "lambda_bar_z" }],
  },
  {
    type: "formula",
    key: "N_b_z_Rd_N",
    valueType: { type: "number" },
    id: "N_b_z_Rd_N",
    name: "Buckling resistance z-z",
    symbol: "N_{b_mm,z,Rd}",
    expression: "\\frac{\\chi_z A_mm2 f_y}{\\gamma_{M1}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.3.1.1", formulaRef: "(6.47)" },
    children: [
      { nodeId: "chi_z" },
      { nodeId: "A_mm2" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M1" },
    ],
  },
  {
    type: "derived",
    key: "abs_N_Ed_N",
    valueType: { type: "number" },
    id: "abs_N_Ed_N",
    name: "Absolute design axial force",
    expression: "\\left|N_{Ed}\\right|",
    unit: "\\mathrm{N}",
    children: [{ nodeId: "N_Ed_N" }],
  },
  {
    type: "check",
    key: "buckling_z_check",
    valueType: { type: "number" },
    id: "buckling_z_check",
    name: "Flexural buckling check z-z",
    verificationExpression: "\\frac{N_{Ed}}{N_{b_mm,z,Rd}} \\leq 1.0",
    meta: { sectionRef: "6.3.1.1", verificationRef: "(6.46)" },
    children: [{ nodeId: "abs_N_Ed_N" }, { nodeId: "N_b_z_Rd_N" }],
  },
]);

export type Nodes = typeof nodes;
