import type { VerificationDefinition } from "@ndg/ndg-core";

/** §6.3.1 — Flexural buckling about z-z: N_Ed / N_b_z_Rd ≤ 1.0 */

const nodes = [
  {
    type: "user-input",
    key: "N_Ed",
    valueType: "number",
    id: "bz-N-Ed",
    name: "Design compression force",
    symbol: "N_{Ed}",
    unit: "N",
    children: [],
  },
  {
    type: "user-input",
    key: "A",
    valueType: "number",
    id: "bz-A",
    name: "Cross-sectional area",
    unit: "mm²",
    children: [],
  },
  {
    type: "user-input",
    key: "fy",
    valueType: "number",
    id: "bz-fy",
    name: "Yield strength",
    unit: "MPa",
    children: [],
  },
  {
    type: "user-input",
    key: "E",
    valueType: "number",
    id: "bz-E",
    name: "Elastic modulus",
    unit: "MPa",
    children: [],
  },
  {
    type: "user-input",
    key: "Iz",
    valueType: "number",
    id: "bz-Iz",
    name: "Second moment of area z-z",
    unit: "mm⁴",
    children: [],
  },
  {
    type: "user-input",
    key: "Lcr_z",
    valueType: "number",
    id: "bz-Lcr-z",
    name: "Buckling length about z-z",
    symbol: "L_{cr,z}",
    unit: "mm",
    children: [],
  },
  {
    type: "user-input",
    key: "alpha_z",
    valueType: "number",
    id: "bz-alpha-z",
    name: "Imperfection factor z-z",
    symbol: "\\alpha_z",
    children: [],
  },
  {
    type: "coefficient",
    key: "gamma_M1",
    valueType: "number",
    id: "bz-gamma-M1",
    name: "Partial safety factor",
    symbol: "\\gamma_{M1}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
  {
    type: "formula",
    key: "N_cr_z",
    valueType: "number",
    id: "bz-N-cr-z",
    name: "Elastic critical force z-z",
    symbol: "N_{cr,z}",
    expression: "\\frac{\\pi^2 E I_z}{L_{cr,z}^2}",
    unit: "N",
    meta: { sectionRef: "6.3.1.2", formulaRef: "(6.49)" },
    children: [{ nodeId: "bz-E" }, { nodeId: "bz-Iz" }, { nodeId: "bz-Lcr-z" }],
  },
  {
    type: "derived",
    key: "lambda_bar_z",
    valueType: "number",
    id: "bz-lambda-bar-z",
    name: "Non-dimensional slenderness z-z",
    symbol: "\\bar{\\lambda}_z",
    children: [{ nodeId: "bz-A" }, { nodeId: "bz-fy" }, { nodeId: "bz-N-cr-z" }],
  },
  {
    type: "derived",
    key: "phi_z",
    valueType: "number",
    id: "bz-phi-z",
    name: "Buckling parameter z-z",
    symbol: "\\Phi_z",
    children: [{ nodeId: "bz-alpha-z" }, { nodeId: "bz-lambda-bar-z" }],
  },
  {
    type: "formula",
    key: "chi_z",
    valueType: "number",
    id: "bz-chi-z",
    name: "Reduction factor z-z",
    symbol: "\\chi_z",
    expression: "\\frac{1}{\\Phi_z + \\sqrt{\\Phi_z^2 - \\bar{\\lambda}_z^2}}",
    meta: { sectionRef: "6.3.1.2", formulaRef: "(6.49)" },
    children: [{ nodeId: "bz-phi-z" }, { nodeId: "bz-lambda-bar-z" }],
  },
  {
    type: "formula",
    key: "N_b_z_Rd",
    valueType: "number",
    id: "bz-N-b-z-Rd",
    name: "Buckling resistance z-z",
    symbol: "N_{b,z,Rd}",
    expression: "\\frac{\\chi_z A f_y}{\\gamma_{M1}}",
    unit: "N",
    meta: { sectionRef: "6.3.1.1", formulaRef: "(6.47)" },
    children: [
      { nodeId: "bz-chi-z" }, { nodeId: "bz-A" },
      { nodeId: "bz-fy" }, { nodeId: "bz-gamma-M1" },
    ],
  },
  {
    type: "check",
    key: "buckling_z_check",
    valueType: "number",
    id: "bz-check",
    name: "Flexural buckling check z-z",
    verificationExpression: "\\frac{N_{Ed}}{N_{b,z,Rd}} \\leq 1.0",
    meta: { sectionRef: "6.3.1.1", verificationRef: "(6.46)" },
    children: [{ nodeId: "bz-N-Ed" }, { nodeId: "bz-N-b-z-Rd" }],
  },
] as const;

export const ulsBucklingZ: VerificationDefinition<typeof nodes> = {
  nodes,
  evaluate: {
    N_cr_z: ({ E, Iz, Lcr_z }) =>
      (Math.PI ** 2 * E * Iz) / Lcr_z ** 2,
    lambda_bar_z: ({ A, fy, N_cr_z }) =>
      Math.sqrt((A * fy) / N_cr_z),
    phi_z: ({ alpha_z, lambda_bar_z }) =>
      0.5 * (1 + alpha_z * (lambda_bar_z - 0.2) + lambda_bar_z ** 2),
    chi_z: ({ phi_z, lambda_bar_z }) =>
      Math.min(1, 1 / (phi_z + Math.sqrt(phi_z ** 2 - lambda_bar_z ** 2))),
    N_b_z_Rd: ({ chi_z, A, fy, gamma_M1 }) =>
      (chi_z * A * fy) / gamma_M1,
    buckling_z_check: ({ N_Ed, N_b_z_Rd }) =>
      Math.abs(N_Ed) / N_b_z_Rd,
  },
};
