import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "biaxial_axial_shear_check",
    type: "check",
    key: "biaxial_axial_shear_check",
    valueType: { type: "number" },
    name: "Biaxial bending + axial + shear check",
    verificationExpression:
      "\\left(\\frac{\\left|M_{y,Ed}\\right|}{M_{NV,y,Rd}}\\right)^\\alpha + \\left(\\frac{\\left|M_{z,Ed}\\right|}{M_{NV,z,Rd}}\\right)^\\beta \\leq 1.0",
    meta: { sectionRef: "6.2.10", verificationRef: "(6.45),(6.41),(6.42)" },
    children: [
      { nodeId: "abs_M_y_Ed_Nmm" },
      { nodeId: "M_NV_y_Rd_Nmm" },
      { nodeId: "alpha_biax" },
      { nodeId: "abs_M_z_Ed_Nmm" },
      { nodeId: "M_NV_z_Rd_Nmm" },
      { nodeId: "beta_biax" },
    ],
  },
  {
    id: "M_y_Ed_Nmm",
    type: "user-input",
    key: "M_y_Ed_Nmm",
    valueType: { type: "number" },
    name: "Design bending moment y-y",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "M_z_Ed_Nmm",
    type: "user-input",
    key: "M_z_Ed_Nmm",
    valueType: { type: "number" },
    name: "Design bending moment z-z",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "N_Ed_N",
    type: "user-input",
    key: "N_Ed_N",
    valueType: { type: "number" },
    name: "Design axial force",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "V_z_Ed_N",
    type: "user-input",
    key: "V_z_Ed_N",
    valueType: { type: "number" },
    name: "Design shear force z",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "V_y_Ed_N",
    type: "user-input",
    key: "V_y_Ed_N",
    valueType: { type: "number" },
    name: "Design shear force y",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "A_mm2",
    type: "user-input",
    key: "A_mm2",
    valueType: { type: "number" },
    name: "Cross-sectional area",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "b_mm",
    type: "user-input",
    key: "b_mm",
    valueType: { type: "number" },
    name: "Section width",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "h_mm",
    type: "user-input",
    key: "h_mm",
    valueType: { type: "number" },
    name: "Section depth",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tf_mm",
    type: "user-input",
    key: "tf_mm",
    valueType: { type: "number" },
    name: "Flange thickness",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tw_mm",
    type: "user-input",
    key: "tw_mm",
    valueType: { type: "number" },
    name: "Web/wall thickness",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "Wpl_y_mm3",
    type: "user-input",
    key: "Wpl_y_mm3",
    valueType: { type: "number" },
    name: "Plastic section modulus y-y",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wpl_z_mm3",
    type: "user-input",
    key: "Wpl_z_mm3",
    valueType: { type: "number" },
    name: "Plastic section modulus z-z",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wel_z_mm3",
    type: "user-input",
    key: "Wel_z_mm3",
    valueType: { type: "number" },
    name: "Elastic section modulus z-z",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Av_z_mm2",
    type: "user-input",
    key: "Av_z_mm2",
    valueType: { type: "number" },
    name: "Shear area z",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "Av_y_mm2",
    type: "user-input",
    key: "Av_y_mm2",
    valueType: { type: "number" },
    name: "Shear area y",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "section_shape",
    type: "user-input",
    key: "section_shape",
    valueType: { type: "string", oneOf: ["I", "RHS", "CHS"] },
    name: "Section shape family",
    children: [],
  },
  {
    id: "section_class",
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    name: "Section class",
    children: [],
  },
  {
    id: "fy_MPa",
    type: "user-input",
    key: "fy_MPa",
    valueType: { type: "number" },
    name: "Yield strength",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
  {
    id: "V_pl_z_Rd_N",
    type: "formula",
    key: "V_pl_z_Rd_N",
    valueType: { type: "number" },
    name: "Plastic shear resistance z",
    symbol: "V_{pl,z,Rd}",
    expression: "A_{v,z} f_y / (\\sqrt{3} \\gamma_{M0})",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.6", formulaRef: "(6.18)" },
    children: [
      { nodeId: "Av_z_mm2" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "V_pl_y_Rd_N",
    type: "formula",
    key: "V_pl_y_Rd_N",
    valueType: { type: "number" },
    name: "Plastic shear resistance y",
    symbol: "V_{pl,y,Rd}",
    expression: "A_{v,y} f_y / (\\sqrt{3} \\gamma_{M0})",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.6", formulaRef: "(6.18)" },
    children: [
      { nodeId: "Av_y_mm2" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "abs_V_z_Ed_N",
    type: "derived",
    key: "abs_V_z_Ed_N",
    valueType: { type: "number" },
    name: "Absolute design shear force z",
    children: [{ nodeId: "V_z_Ed_N" }],
  },
  {
    id: "abs_V_y_Ed_N",
    type: "derived",
    key: "abs_V_y_Ed_N",
    valueType: { type: "number" },
    name: "Absolute design shear force y",
    children: [{ nodeId: "V_y_Ed_N" }],
  },
  {
    id: "rho_z",
    type: "derived",
    key: "rho_z",
    valueType: { type: "number" },
    name: "Shear interaction z",
    expression: "|V_z|/V_pl_z<=0.5?0:(2|V_z|/V_pl_z-1)^2",
    children: [{ nodeId: "abs_V_z_Ed_N" }, { nodeId: "V_pl_z_Rd_N" }],
  },
  {
    id: "rho_y",
    type: "derived",
    key: "rho_y",
    valueType: { type: "number" },
    name: "Shear interaction y",
    expression: "|V_y|/V_pl_y<=0.5?0:(2|V_y|/V_pl_y-1)^2",
    children: [{ nodeId: "abs_V_y_Ed_N" }, { nodeId: "V_pl_y_Rd_N" }],
  },
  {
    id: "N_pl_Rd_N",
    type: "formula",
    key: "N_pl_Rd_N",
    valueType: { type: "number" },
    name: "Plastic resistance",
    symbol: "N_{pl,Rd}",
    expression: "A_mm2 f_y / \\gamma_{M0}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.4", formulaRef: "(6.10)" },
    children: [
      { nodeId: "A_mm2" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "abs_N_Ed_N",
    type: "derived",
    key: "abs_N_Ed_N",
    valueType: { type: "number" },
    name: "Absolute design axial force",
    children: [{ nodeId: "N_Ed_N" }],
  },
  {
    id: "n",
    type: "derived",
    key: "n",
    valueType: { type: "number" },
    name: "Axial force ratio",
    expression: "|N_{Ed}|/N_{pl,Rd}",
    children: [{ nodeId: "abs_N_Ed_N" }, { nodeId: "N_pl_Rd_N" }],
  },
  {
    id: "a_w",
    type: "derived",
    key: "a_w",
    valueType: { type: "number" },
    name: "Limited area ratio for y-branch",
    children: [
      { nodeId: "a_w_i", when: { eq: ["section_shape", { value: "I" }] } },
      { nodeId: "a_w_rhs", when: { eq: ["section_shape", { value: "RHS" }] } },
      { nodeId: "a_w_chs", when: { eq: ["section_shape", { value: "CHS" }] } },
    ],
  },
  {
    id: "a_w_i",
    type: "derived",
    key: "a_w_i",
    valueType: { type: "number" },
    name: "I-section y-branch area ratio",
    expression: "(A_mm2-2b t_f)/A_mm2",
    children: [{ nodeId: "A_mm2" }, { nodeId: "b_mm" }, { nodeId: "tf_mm" }],
  },
  {
    id: "a_w_rhs",
    type: "derived",
    key: "a_w_rhs",
    valueType: { type: "number" },
    name: "RHS y-branch area ratio",
    expression: "(A_mm2-2b t_w)/A_mm2",
    children: [{ nodeId: "A_mm2" }, { nodeId: "b_mm" }, { nodeId: "tw_mm" }],
  },
  {
    id: "a_w_chs",
    type: "derived",
    key: "a_w_chs",
    valueType: { type: "number" },
    name: "CHS y-branch area ratio",
    expression: "0.5",
    children: [],
  },
  {
    id: "a_f",
    type: "derived",
    key: "a_f",
    valueType: { type: "number" },
    name: "Limited area ratio for z-branch",
    children: [
      { nodeId: "a_f_i", when: { eq: ["section_shape", { value: "I" }] } },
      { nodeId: "a_f_rhs", when: { eq: ["section_shape", { value: "RHS" }] } },
      { nodeId: "a_f_chs", when: { eq: ["section_shape", { value: "CHS" }] } },
    ],
  },
  {
    id: "a_f_i",
    type: "derived",
    key: "a_f_i",
    valueType: { type: "number" },
    name: "I-section z-branch area ratio",
    expression: "(A_mm2-2b t_f)/A_mm2",
    children: [{ nodeId: "A_mm2" }, { nodeId: "b_mm" }, { nodeId: "tf_mm" }],
  },
  {
    id: "a_f_rhs",
    type: "derived",
    key: "a_f_rhs",
    valueType: { type: "number" },
    name: "RHS z-branch area ratio",
    expression: "(A_mm2-2h t_w)/A_mm2",
    children: [{ nodeId: "A_mm2" }, { nodeId: "h_mm" }, { nodeId: "tw_mm" }],
  },
  {
    id: "a_f_chs",
    type: "derived",
    key: "a_f_chs",
    valueType: { type: "number" },
    name: "CHS z-branch area ratio",
    expression: "0.5",
    children: [],
  },
  {
    id: "a_w_half",
    type: "derived",
    key: "a_w_half",
    valueType: { type: "number" },
    name: "Half of limited area ratio",
    symbol: "0.5a_w",
    expression: "0.5a_w",
    children: [{ nodeId: "a_w" }],
  },
  {
    id: "k_y",
    type: "derived",
    key: "k_y",
    valueType: { type: "number" },
    name: "Axial reduction factor for y-branch",
    symbol: "k_y",
    children: [
      { nodeId: "k_y_1", when: { lte: ["n", { key: "a_w_half" }] } },
      { nodeId: "k_y_2", when: { gt: ["n", { key: "a_w_half" }] } },
    ],
  },
  {
    id: "k_y_1",
    type: "derived",
    key: "k_y_1",
    valueType: { type: "number" },
    name: "Axial reduction factor for low-axial branch",
    symbol: "k_{y,1}",
    expression: "1",
    children: [],
  },
  {
    id: "k_y_2",
    type: "derived",
    key: "k_y_2",
    valueType: { type: "number" },
    name: "Axial reduction factor for high-axial branch",
    symbol: "k_{y,2}",
    expression: "1-\\left(\\frac{n-0.5a_w}{1-0.5a_w}\\right)^2",
    children: [{ nodeId: "n" }, { nodeId: "a_w" }],
  },
  {
    id: "Wpl_y_eff_mm3",
    type: "derived",
    key: "Wpl_y_eff_mm3",
    valueType: { type: "number" },
    name: "Effective plastic modulus y",
    children: [
      { nodeId: "section_shape" },
      {
        nodeId: "Wpl_y_eff_i_mm3",
        when: { eq: ["section_shape", { value: "I" }] },
      },
      {
        nodeId: "Wpl_y_eff_rhs_mm3",
        when: { eq: ["section_shape", { value: "RHS" }] },
      },
      {
        nodeId: "Wpl_y_eff_chs_mm3",
        when: { eq: ["section_shape", { value: "CHS" }] },
      },
    ],
  },
  {
    id: "Wpl_y_eff_i_mm3",
    type: "derived",
    key: "Wpl_y_eff_i_mm3",
    valueType: { type: "number" },
    name: "I-section effective plastic modulus y",
    children: [
      { nodeId: "Wpl_y_mm3" },
      { nodeId: "b_mm" },
      { nodeId: "h_mm" },
      { nodeId: "tf_mm" },
      { nodeId: "tw_mm" },
      { nodeId: "rho_y" },
      { nodeId: "rho_z" },
    ],
  },
  {
    id: "Wpl_y_eff_rhs_mm3",
    type: "derived",
    key: "Wpl_y_eff_rhs_mm3",
    valueType: { type: "number" },
    name: "RHS effective plastic modulus y",
    children: [
      { nodeId: "Wpl_y_mm3" },
      { nodeId: "rho_z" },
      { nodeId: "Av_z_mm2" },
      { nodeId: "tw_mm" },
    ],
  },
  {
    id: "Wpl_y_eff_chs_mm3",
    type: "derived",
    key: "Wpl_y_eff_chs_mm3",
    valueType: { type: "number" },
    name: "CHS effective plastic modulus y",
    children: [
      { nodeId: "Wpl_y_mm3" },
      { nodeId: "rho_z" },
      { nodeId: "Av_z_mm2" },
      { nodeId: "tw_mm" },
    ],
  },
  {
    id: "M_y_V_Rd_Nmm",
    type: "formula",
    key: "M_y_V_Rd_Nmm",
    valueType: { type: "number" },
    name: "Reduced plastic moment y-y allowing for shear",
    symbol: "M_{y,V,Rd}",
    expression: "W_{pl,y,eff}f_y/\\gamma_{M0}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.10", formulaRef: "(6.45)" },
    children: [
      { nodeId: "Wpl_y_eff_mm3" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "M_NV_y_Rd_Nmm",
    type: "formula",
    key: "M_NV_y_Rd_Nmm",
    valueType: { type: "number" },
    name: "Reduced plastic moment y-y (axial + shear)",
    symbol: "M_{NV,y,Rd}",
    expression: "M_{y,V,Rd}*k_y",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.36)" },
    children: [{ nodeId: "M_y_V_Rd_Nmm" }, { nodeId: "k_y" }],
  },
  {
    id: "Wpl_z_web_mm3",
    type: "derived",
    key: "Wpl_z_web_mm3",
    valueType: { type: "number" },
    name: "Web contribution to plastic modulus about z-z",
    expression: "A_{v,z} t_w / 4",
    children: [{ nodeId: "Av_z_mm2" }, { nodeId: "tw_mm" }],
  },
  {
    id: "W_z_res_mm3",
    type: "derived",
    key: "W_z_res_mm3",
    valueType: { type: "number" },
    name: "Class-dependent section modulus for z bending",
    children: [
      { nodeId: "section_class" },
      {
        nodeId: "W_z_res_class12_mm3",
        when: {
          or: [
            { eq: ["section_class", { value: 1 }] },
            { eq: ["section_class", { value: 2 }] },
          ],
        },
      },
      {
        nodeId: "W_z_res_class3_mm3",
        when: { eq: ["section_class", { value: 3 }] },
      },
    ],
  },
  {
    id: "W_z_res_class12_mm3",
    type: "derived",
    key: "W_z_res_class12_mm3",
    valueType: { type: "number" },
    name: "Class 1/2 resistance modulus about z-z",
    children: [{ nodeId: "Wpl_z_mm3" }],
  },
  {
    id: "W_z_res_class3_mm3",
    type: "derived",
    key: "W_z_res_class3_mm3",
    valueType: { type: "number" },
    name: "Class 3 resistance modulus about z-z",
    children: [{ nodeId: "Wel_z_mm3" }],
  },
  {
    id: "Wpl_z_eff_mm3",
    type: "derived",
    key: "Wpl_z_eff_mm3",
    valueType: { type: "number" },
    name: "Effective plastic modulus z",
    expression: "W_{z,res}-\\rho_y(W_{z,res}-W_{pl,z,web})",
    children: [
      { nodeId: "W_z_res_mm3" },
      { nodeId: "rho_y" },
      { nodeId: "Wpl_z_web_mm3" },
    ],
  },
  {
    id: "M_z_V_Rd_Nmm",
    type: "formula",
    key: "M_z_V_Rd_Nmm",
    valueType: { type: "number" },
    name: "Reduced plastic moment z-z allowing for shear",
    symbol: "M_{z,V,Rd}",
    expression: "W_{pl,z,eff}f_y/\\gamma_{M0}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.8", formulaRef: "(6.30)" },
    children: [
      { nodeId: "Wpl_z_eff_mm3" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "k_z",
    type: "derived",
    key: "k_z",
    valueType: { type: "number" },
    name: "Axial reduction factor for z-branch",
    children: [
      { nodeId: "k_z_i", when: { eq: ["section_shape", { value: "I" }] } },
      {
        nodeId: "k_z_rhs_chs",
        when: {
          or: [
            { eq: ["section_shape", { value: "RHS" }] },
            { eq: ["section_shape", { value: "CHS" }] },
          ],
        },
      },
    ],
  },
  {
    id: "k_z_i",
    type: "derived",
    key: "k_z_i",
    valueType: { type: "number" },
    name: "I-section axial reduction factor for z-z",
    expression:
      "n \\leq a_f \\Rightarrow 1,\\ \\text{else}\\ 1-\\left(\\frac{n-a_f}{1-a_f}\\right)^2",
    children: [{ nodeId: "n" }, { nodeId: "a_f" }],
  },
  {
    id: "k_z_rhs_chs",
    type: "derived",
    key: "k_z_rhs_chs",
    valueType: { type: "number" },
    name: "RHS/CHS axial reduction factor for z-z",
    expression: "\\min\\left(1,\\frac{1-n}{1-0.5a_f}\\right)",
    children: [{ nodeId: "n" }, { nodeId: "a_f" }],
  },
  {
    id: "M_NV_z_Rd_Nmm",
    type: "formula",
    key: "M_NV_z_Rd_Nmm",
    valueType: { type: "number" },
    name: "Reduced plastic moment z-z (axial + shear)",
    symbol: "M_{NV,z,Rd}",
    expression: "M_{z,V,Rd}*k_z",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.38)" },
    children: [{ nodeId: "M_z_V_Rd_Nmm" }, { nodeId: "k_z" }],
  },
  {
    id: "alpha_biax",
    type: "derived",
    key: "alpha_biax",
    valueType: { type: "number" },
    name: "Biaxial exponent alpha",
    symbol: "\\alpha",
    children: [
      {
        nodeId: "alpha_biax_i",
        when: { eq: ["section_shape", { value: "I" }] },
      },
      {
        nodeId: "alpha_biax_rhs",
        when: { eq: ["section_shape", { value: "RHS" }] },
      },
      {
        nodeId: "alpha_biax_chs",
        when: { eq: ["section_shape", { value: "CHS" }] },
      },
    ],
  },
  {
    id: "alpha_biax_i",
    type: "derived",
    key: "alpha_biax_i",
    valueType: { type: "number" },
    name: "I-section alpha exponent",
    expression: "2",
    children: [],
  },
  {
    id: "alpha_biax_rhs",
    type: "derived",
    key: "alpha_biax_rhs",
    valueType: { type: "number" },
    name: "RHS alpha exponent",
    expression: "rhs\\_exp",
    children: [{ nodeId: "rhs_exp" }],
  },
  {
    id: "alpha_biax_chs",
    type: "derived",
    key: "alpha_biax_chs",
    valueType: { type: "number" },
    name: "CHS alpha exponent",
    expression: "2",
    children: [],
  },
  {
    id: "beta_biax",
    type: "derived",
    key: "beta_biax",
    valueType: { type: "number" },
    name: "Biaxial exponent beta",
    symbol: "\\beta",
    children: [
      {
        nodeId: "beta_biax_i",
        when: { eq: ["section_shape", { value: "I" }] },
      },
      {
        nodeId: "beta_biax_rhs",
        when: { eq: ["section_shape", { value: "RHS" }] },
      },
      {
        nodeId: "beta_biax_chs",
        when: { eq: ["section_shape", { value: "CHS" }] },
      },
    ],
  },
  {
    id: "beta_biax_i",
    type: "derived",
    key: "beta_biax_i",
    valueType: { type: "number" },
    name: "I-section beta exponent",
    expression: "\\max(1, 5n)",
    children: [{ nodeId: "n" }],
  },
  {
    id: "beta_biax_rhs",
    type: "derived",
    key: "beta_biax_rhs",
    valueType: { type: "number" },
    name: "RHS beta exponent",
    expression: "rhs\\_exp",
    children: [{ nodeId: "rhs_exp" }],
  },
  {
    id: "beta_biax_chs",
    type: "derived",
    key: "beta_biax_chs",
    valueType: { type: "number" },
    name: "CHS beta exponent",
    expression: "2",
    children: [],
  },
  {
    id: "rhs_exp",
    type: "derived",
    key: "rhs_exp",
    valueType: { type: "number" },
    name: "RHS exponent with cap",
    expression: "\\min(1.66/(1-1.13n^2), 6)",
    children: [{ nodeId: "n" }],
  },
  {
    id: "abs_M_y_Ed_Nmm",
    type: "derived",
    key: "abs_M_y_Ed_Nmm",
    valueType: { type: "number" },
    name: "Absolute design moment y",
    children: [{ nodeId: "M_y_Ed_Nmm" }],
  },
  {
    id: "abs_M_z_Ed_Nmm",
    type: "derived",
    key: "abs_M_z_Ed_Nmm",
    valueType: { type: "number" },
    name: "Absolute design moment z",
    children: [{ nodeId: "M_z_Ed_Nmm" }],
  },
]);

export type Nodes = typeof nodes;
