import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "ratio",
    type: "check",
    key: "ratio",
    valueType: { type: "number" },
    name: "Bending and axial resistance check about y-y",
    verificationExpression:
      "\\text{class 1/2: }\\frac{\\left|M_{y,Ed}\\right|}{M_{N,y,Rd}}\\leq1.0\\ ;\\ \\text{class 3: }\\frac{\\sigma_{x,Ed}}{f_y/\\gamma_{M0}}\\leq1.0",
    meta: { sectionRef: "6.2.9", verificationRef: "(6.36),(6.42)" },
    children: [
      {
        nodeId: "utilization_class12",
        when: {
          or: [
            { eq: ["section_class", { value: 1 }] },
            { eq: ["section_class", { value: 2 }] },
          ],
        },
      },
      {
        nodeId: "utilization_class3",
        when: { eq: ["section_class", { value: 3 }] },
      },
    ],
  },
  {
    id: "utilization_class12",
    type: "derived",
    key: "utilization_class12",
    valueType: { type: "number" },
    name: "Class 1/2 utilization ratio about y-y",
    symbol: "u_{12}",
    expression: "\\left|M_{y,Ed}\\right|/M_{N,y,Rd}",
    children: [{ nodeId: "M_y_Ed" }, { nodeId: "M_N_y_Rd" }],
  },
  {
    id: "M_N_y_Rd",
    type: "formula",
    key: "M_N_y_Rd",
    valueType: { type: "number" },
    name: "Reduced bending resistance about y-y under axial force",
    symbol: "M_{N,y,Rd}",
    expression: "M_{pl,y,Rd} \\cdot k_y",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.36)" },
    children: [{ nodeId: "M_pl_y_Rd" }, { nodeId: "k_y" }],
  },
  {
    id: "M_pl_y_Rd",
    type: "formula",
    key: "M_pl_y_Rd",
    valueType: { type: "number" },
    name: "Design bending resistance about y-y",
    symbol: "M_{pl,y,Rd}",
    expression: "\\frac{W_{pl,y} \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.5", formulaRef: "(6.13)" },
    children: [
      { nodeId: "Wpl_y_mm3" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "k_y",
    type: "derived",
    key: "k_y",
    valueType: { type: "number" },
    name: "Axial reduction factor for y-y branch",
    symbol: "k_y",
    children: [
      { nodeId: "k_y_i", when: { eq: ["shape", { value: "I" }] } },
      {
        nodeId: "k_y_rhs_chs",
        when: {
          or: [
            { eq: ["shape", { value: "RHS" }] },
            { eq: ["shape", { value: "CHS" }] },
          ],
        },
      },
    ],
  },
  {
    id: "k_y_i",
    type: "derived",
    key: "k_y_i",
    valueType: { type: "number" },
    name: "I-section axial reduction factor for y-y",
    symbol: "k_{y,I}",
    expression:
      "n \\leq 0.5a_w \\Rightarrow 1,\\ \\text{else}\\ 1-\\left(\\frac{n-0.5a_w}{1-0.5a_w}\\right)^2",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.33)" },
    children: [{ nodeId: "n" }, { nodeId: "a_w" }],
  },
  {
    id: "k_y_rhs_chs",
    type: "derived",
    key: "k_y_rhs_chs",
    valueType: { type: "number" },
    name: "RHS/CHS axial reduction factor for y-y",
    symbol: "k_{y,RHS}",
    expression: "\\min\\left(1,\\dfrac{1-n}{1-0.5a_w}\\right)",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.35)" },
    children: [{ nodeId: "n" }, { nodeId: "a_w" }],
  },
  {
    id: "a_w",
    type: "derived",
    key: "a_w",
    valueType: { type: "number" },
    name: "Limited area ratio for y-y branch",
    symbol: "a_w",
    children: [
      { nodeId: "a_w_i", when: { eq: ["shape", { value: "I" }] } },
      { nodeId: "a_w_rhs", when: { eq: ["shape", { value: "RHS" }] } },
      { nodeId: "a_w_chs", when: { eq: ["shape", { value: "CHS" }] } },
    ],
  },
  {
    id: "a_w_i",
    type: "derived",
    key: "a_w_i",
    valueType: { type: "number" },
    name: "I-section area ratio for y-y branch",
    symbol: "a_{w,I}",
    expression: "\\min\\left(\\dfrac{A_mm2-2bt_f}{A_mm2},0.5\\right)",
    children: [{ nodeId: "A_mm2" }, { nodeId: "b_mm" }, { nodeId: "tf_mm" }],
  },
  {
    id: "a_w_rhs",
    type: "derived",
    key: "a_w_rhs",
    valueType: { type: "number" },
    name: "RHS section area ratio for y-y branch",
    symbol: "a_{w,RHS}",
    expression: "\\min\\left(\\dfrac{A_mm2-2bt}{A_mm2},0.5\\right)",
    children: [{ nodeId: "A_mm2" }, { nodeId: "b_mm" }, { nodeId: "t_mm" }],
  },
  {
    id: "a_w_chs",
    type: "derived",
    key: "a_w_chs",
    valueType: { type: "number" },
    name: "CHS section area ratio for y-y branch",
    symbol: "a_{w,CHS}",
    expression: "0.5",
    children: [],
  },
  {
    id: "n",
    type: "derived",
    key: "n",
    valueType: { type: "number" },
    name: "Axial force ratio",
    symbol: "n",
    expression: "\\frac{\\left|N_{Ed}\\right|}{N_{pl,Rd}}",
    children: [{ nodeId: "N_Ed" }, { nodeId: "N_pl_Rd" }],
  },
  {
    id: "N_Ed",
    type: "user-input",
    key: "N_Ed",
    valueType: { type: "number" },
    name: "Design axial force",
    symbol: "N_{Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "N_pl_Rd",
    type: "formula",
    key: "N_pl_Rd",
    valueType: { type: "number" },
    name: "Plastic resistance to normal force",
    symbol: "N_{pl,Rd}",
    expression: "\\frac{A_mm2 \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.4", formulaRef: "(6.10)" },
    children: [
      { nodeId: "A_mm2" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "utilization_class3",
    type: "derived",
    key: "utilization_class3",
    valueType: { type: "number" },
    name: "Class 3 stress utilization ratio",
    symbol: "u_3",
    expression: "\\sigma_{x,Ed}/(f_y/\\gamma_{M0})",
    children: [{ nodeId: "sigma_x_class3" }, { nodeId: "sigma_limit" }],
  },
  {
    id: "sigma_x_class3",
    type: "derived",
    key: "sigma_x_class3",
    valueType: { type: "number" },
    name: "Maximum longitudinal stress for class 3",
    symbol: "\\sigma_{x,Ed}",
    expression: "\\sigma_N+\\sigma_{M,y}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "sigma_N" }, { nodeId: "sigma_M_y" }],
  },
  {
    id: "sigma_N",
    type: "derived",
    key: "sigma_N",
    valueType: { type: "number" },
    name: "Axial stress contribution",
    symbol: "\\sigma_N",
    expression: "\\left|N_{Ed}\\right|/A_mm2",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "N_Ed" }, { nodeId: "A_mm2" }],
  },
  {
    id: "sigma_M_y",
    type: "derived",
    key: "sigma_M_y",
    valueType: { type: "number" },
    name: "y-y bending stress contribution",
    symbol: "\\sigma_{M,y}",
    expression: "\\left|M_{y,Ed}\\right|/W_{el,y}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "M_y_Ed" }, { nodeId: "Wel_y_mm3" }],
  },
  {
    id: "M_y_Ed",
    type: "user-input",
    key: "M_y_Ed",
    valueType: { type: "number" },
    name: "Design bending moment about y-y",
    symbol: "M_{y,Ed}",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "sigma_limit",
    type: "formula",
    key: "sigma_limit",
    valueType: { type: "number" },
    name: "Class 3 stress limit",
    symbol: "f_y/\\gamma_{M0}",
    expression: "\\frac{f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{MPa}",
    meta: { sectionRef: "6.2.9.2", formulaRef: "(6.42)" },
    children: [{ nodeId: "fy_MPa" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "section_class",
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    name: "Section class",
    symbol: "\\text{class}",
    children: [],
  },
  {
    id: "shape",
    type: "user-input",
    key: "shape",
    valueType: { type: "string", oneOf: ["I", "RHS", "CHS"] },
    name: "Section shape family",
    symbol: "\\text{shape}",
    children: [],
  },
  {
    id: "A_mm2",
    type: "user-input",
    key: "A_mm2",
    valueType: { type: "number" },
    name: "Cross-sectional area",
    symbol: "A_mm2",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "b_mm",
    type: "user-input",
    key: "b_mm",
    valueType: { type: "number" },
    name: "Section width",
    symbol: "b_mm",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tf_mm",
    type: "user-input",
    key: "tf_mm",
    valueType: { type: "number" },
    name: "Flange thickness",
    symbol: "t_f",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "t_mm",
    type: "user-input",
    key: "t_mm",
    valueType: { type: "number" },
    name: "Wall thickness",
    symbol: "t_mm",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "Wpl_y_mm3",
    type: "user-input",
    key: "Wpl_y_mm3",
    valueType: { type: "number" },
    name: "Plastic section modulus about y-y",
    symbol: "W_{pl,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wel_y_mm3",
    type: "user-input",
    key: "Wel_y_mm3",
    valueType: { type: "number" },
    name: "Elastic section modulus about y-y",
    symbol: "W_{el,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "fy_MPa",
    type: "user-input",
    key: "fy_MPa",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
