import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "bending_y_axial_check",
    type: "check",
    key: "bending_y_axial_check",
    valueType: { type: "number" },
    name: "Bending and axial resistance check about y-y",
    verificationExpression:
      "\\text{class 1/2: }\\frac{\\left|M_{y,Ed}\\right|}{M_{N,y,Rd}}\\leq1.0\\ ;\\ \\text{class 3: }\\frac{\\sigma_{x,Ed}}{f_y/\\gamma_{M0}}\\leq1.0",
    meta: { sectionRef: "6.2.9", verificationRef: "(6.31),(6.42)" },
    children: [
      {
        nodeId: "utilization_class12",
        when: {
          or: [{ eq: ["section_class", 1] }, { eq: ["section_class", 2] }],
        },
      },
      {
        nodeId: "utilization_class3",
        when: { eq: ["section_class", 3] },
      },
    ],
  },
  {
    id: "utilization_class12",
    type: "derived",
    key: "utilization_class12",
    valueType: { type: "number" },
    name: "Class 1/2 utilization ratio about y-y",
    expression: "\\left|M_{y,Ed}\\right|/M_{N,y,Rd}",
    children: [{ nodeId: "abs_M_y_Ed" }, { nodeId: "M_N_y_Rd" }],
  },
  {
    id: "M_N_y_Rd",
    type: "formula",
    key: "M_N_y_Rd",
    valueType: { type: "number" },
    name: "Reduced bending resistance about y-y under axial force",
    symbol: "M_{N,y,Rd}",
    expression: "M_{pl,y,Rd} \\cdot k_y",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.36)" },
    children: [{ nodeId: "M_pl_y_Rd" }, { nodeId: "k_y" }],
  },
  {
    id: "M_pl_y_Rd",
    type: "formula",
    key: "M_pl_y_Rd",
    valueType: { type: "number" },
    name: "Design bending resistance about y-y",
    symbol: "M_{pl,y,Rd}",
    expression: "\\frac{W_{pl,y} \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.5", formulaRef: "(6.13)" },
    children: [{ nodeId: "Wpl_y" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "k_y",
    type: "derived",
    key: "k_y",
    valueType: { type: "number" },
    name: "Axial reduction factor for y-y branch",
    expression:
      "n \\leq 0.5a_w ? 1 : \\min\\left(1,\\frac{1-n}{1-0.5a_w}\\right)",
    children: [
      { nodeId: "is_n_le_half_a_w" },
      { nodeId: "n" },
      { nodeId: "a_w" },
    ],
  },
  {
    id: "is_n_le_half_a_w",
    type: "derived",
    key: "is_n_le_half_a_w",
    valueType: { type: "number" },
    name: "Threshold indicator for n <= 0.5a_w",
    expression: "n \\leq 0.5a_w",
    children: [{ nodeId: "n" }, { nodeId: "a_w" }],
  },
  {
    id: "a_w",
    type: "derived",
    key: "a_w",
    valueType: { type: "number" },
    name: "Limited area ratio for y-y branch",
    expression: "\\min(a_w,0.5)",
    children: [
      { nodeId: "section_shape" },
      { nodeId: "a_w_i", when: { eq: ["section_shape", "I"] } },
      { nodeId: "a_w_rhs", when: { eq: ["section_shape", "RHS"] } },
      { nodeId: "a_w_chs", when: { eq: ["section_shape", "CHS"] } },
    ],
  },
  {
    id: "a_w_i",
    type: "derived",
    key: "a_w_i",
    valueType: { type: "number" },
    name: "I-section area ratio for y-y branch",
    expression: "(A-2b t_f)/A",
    children: [{ nodeId: "A" }, { nodeId: "b" }, { nodeId: "tf" }],
  },
  {
    id: "a_w_rhs",
    type: "derived",
    key: "a_w_rhs",
    valueType: { type: "number" },
    name: "RHS section area ratio for y-y branch",
    expression: "(A-2b t)/A",
    children: [{ nodeId: "A" }, { nodeId: "b" }, { nodeId: "t" }],
  },
  {
    id: "a_w_chs",
    type: "derived",
    key: "a_w_chs",
    valueType: { type: "number" },
    name: "CHS section area ratio for y-y branch",
    expression: "0.5",
    children: [{ nodeId: "section_shape" }],
  },
  {
    id: "n",
    type: "derived",
    key: "n",
    valueType: { type: "number" },
    name: "Axial force ratio",
    symbol: "n",
    expression: "\\frac{\\left|N_{Ed}\\right|}{N_{pl,Rd}}",
    children: [{ nodeId: "abs_N_Ed" }, { nodeId: "N_pl_Rd" }],
  },
  {
    id: "abs_N_Ed",
    type: "derived",
    key: "abs_N_Ed",
    valueType: { type: "number" },
    name: "Design axial force magnitude",
    expression: "\\left|N_{Ed}\\right|",
    unit: "\\mathrm{N}",
    children: [{ nodeId: "N_Ed" }],
  },
  {
    id: "N_Ed",
    type: "user-input",
    key: "N_Ed",
    valueType: { type: "number" },
    name: "Design axial force",
    symbol: "N_{Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "N_pl_Rd",
    type: "formula",
    key: "N_pl_Rd",
    valueType: { type: "number" },
    name: "Plastic resistance to normal force",
    symbol: "N_{pl,Rd}",
    expression: "\\frac{A \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.4", formulaRef: "(6.10)" },
    children: [{ nodeId: "A" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "utilization_class3",
    type: "derived",
    key: "utilization_class3",
    valueType: { type: "number" },
    name: "Class 3 stress utilization ratio",
    expression: "\\sigma_{x,Ed}/(f_y/\\gamma_{M0})",
    children: [{ nodeId: "sigma_x_class3" }, { nodeId: "sigma_limit" }],
  },
  {
    id: "sigma_x_class3",
    type: "derived",
    key: "sigma_x_class3",
    valueType: { type: "number" },
    name: "Maximum longitudinal stress for class 3",
    expression: "\\sigma_N+\\sigma_{M,y}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "sigma_N" }, { nodeId: "sigma_M_y" }],
  },
  {
    id: "sigma_N",
    type: "derived",
    key: "sigma_N",
    valueType: { type: "number" },
    name: "Axial stress contribution",
    expression: "\\left|N_{Ed}\\right|/A",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_N_Ed" }, { nodeId: "A" }],
  },
  {
    id: "sigma_M_y",
    type: "derived",
    key: "sigma_M_y",
    valueType: { type: "number" },
    name: "y-y bending stress contribution",
    expression: "\\left|M_{y,Ed}\\right|/W_{el,y}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_M_y_Ed" }, { nodeId: "Wel_y" }],
  },
  {
    id: "abs_M_y_Ed",
    type: "derived",
    key: "abs_M_y_Ed",
    valueType: { type: "number" },
    name: "Design bending moment magnitude about y-y",
    expression: "\\left|M_{y,Ed}\\right|",
    unit: "\\mathrm{N\\cdot mm}",
    children: [{ nodeId: "M_y_Ed" }],
  },
  {
    id: "M_y_Ed",
    type: "user-input",
    key: "M_y_Ed",
    valueType: { type: "number" },
    name: "Design bending moment about y-y",
    symbol: "M_{y,Ed}",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "sigma_limit",
    type: "formula",
    key: "sigma_limit",
    valueType: { type: "number" },
    name: "Class 3 stress limit",
    symbol: "f_y/\\gamma_{M0}",
    expression: "\\frac{f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{MPa}",
    meta: { sectionRef: "6.2.9.2", formulaRef: "(6.42)" },
    children: [{ nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "section_class",
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    name: "Section class",
    symbol: "\\text{class}",
    children: [],
  },
  {
    id: "section_shape",
    type: "user-input",
    key: "section_shape",
    valueType: { type: "string", literal: ["I", "RHS", "CHS"] },
    name: "Section shape family",
    symbol: "\\text{shape}",
    children: [],
  },
  {
    id: "A",
    type: "user-input",
    key: "A",
    valueType: { type: "number" },
    name: "Cross-sectional area",
    symbol: "A",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "b",
    type: "user-input",
    key: "b",
    valueType: { type: "number" },
    name: "Section width",
    symbol: "b",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tf",
    type: "user-input",
    key: "tf",
    valueType: { type: "number" },
    name: "Flange thickness",
    symbol: "t_f",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "t",
    type: "user-input",
    key: "t",
    valueType: { type: "number" },
    name: "Wall thickness",
    symbol: "t",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "Wpl_y",
    type: "user-input",
    key: "Wpl_y",
    valueType: { type: "number" },
    name: "Plastic section modulus about y-y",
    symbol: "W_{pl,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wel_y",
    type: "user-input",
    key: "Wel_y",
    valueType: { type: "number" },
    name: "Elastic section modulus about y-y",
    symbol: "W_{el,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "fy",
    type: "user-input",
    key: "fy",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
