import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    type: "user-input",
    key: "M_y_Ed_Nmm",
    valueType: { type: "number" },
    id: "M_y_Ed_Nmm",
    name: "Design bending moment about y-y",
    symbol: "M_{y,Ed}",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    type: "user-input",
    key: "Wpl_y_mm3",
    valueType: { type: "number" },
    id: "Wpl_y_mm3",
    name: "Plastic section modulus about y-y",
    symbol: "W_{pl,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    type: "user-input",
    key: "Wel_y_mm3",
    valueType: { type: "number" },
    id: "Wel_y_mm3",
    name: "Elastic section modulus about y-y",
    symbol: "W_{el,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    type: "derived",
    key: "W_y_res_mm3",
    valueType: { type: "number" },
    id: "W_y_res_mm3",
    name: "Class-dependent resistance modulus about y-y",
    symbol: "W_{y,res}",
    unit: "\\mathrm{mm^{3}}",
    children: [
      {
        nodeId: "Wpl_y_mm3",
        when: {
          or: [
            { eq: ["section_class", { value: 1 }] },
            { eq: ["section_class", { value: 2 }] },
          ],
        },
      },
      { nodeId: "Wel_y_mm3", when: { eq: ["section_class", { value: 3 }] } },
    ],
  },
  {
    type: "user-input",
    key: "fy_MPa",
    valueType: { type: "number" },
    id: "fy_MPa",
    name: "Yield strength",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    type: "user-input",
    key: "E_MPa",
    valueType: { type: "number" },
    id: "E_MPa",
    name: "Elastic modulus",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    type: "user-input",
    key: "G_MPa",
    valueType: { type: "number" },
    id: "G_MPa",
    name: "Shear modulus",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    type: "user-input",
    key: "Iz_mm4",
    valueType: { type: "number" },
    id: "Iz_mm4",
    name: "Minor-axis second moment of area",
    unit: "\\mathrm{mm^{4}}",
    children: [],
  },
  {
    type: "user-input",
    key: "It_mm4",
    valueType: { type: "number" },
    id: "It_mm4",
    name: "St. Venant torsion constant",
    unit: "\\mathrm{mm^{4}}",
    children: [],
  },
  {
    type: "user-input",
    key: "Iw_mm6",
    valueType: { type: "number" },
    id: "Iw_mm6",
    name: "Warping constant",
    unit: "\\mathrm{mm^{6}}",
    children: [],
  },
  {
    type: "user-input",
    key: "L_mm",
    valueType: { type: "number" },
    id: "L_mm",
    name: "Member length",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    type: "user-input",
    key: "k_LT",
    valueType: { type: "number" },
    id: "k_LT",
    name: "LT buckling length factor",
    children: [],
  },
  {
    type: "user-input",
    key: "psi_LT",
    valueType: { type: "number" },
    id: "psi_LT",
    name: "Moment ratio for LT shape selection",
    children: [],
  },
  {
    type: "user-input",
    key: "torsional_deformations",
    valueType: { type: "string" },
    id: "torsional_deformations",
    name: "Member susceptible to torsional deformations (yes/no)",
    children: [],
  },
  {
    type: "user-input",
    key: "coefficient_f_method",
    valueType: { type: "string" },
    id: "coefficient_f_method",
    name: "Method selector for coefficient f",
    children: [],
  },
  {
    type: "user-input",
    key: "buckling_curves_LT_policy",
    valueType: { type: "string" },
    id: "buckling_curves_LT_policy",
    name: "LT buckling curve policy selector",
    children: [],
  },
  {
    type: "user-input",
    key: "moment_shape_LT",
    valueType: { type: "string" },
    id: "moment_shape_LT",
    name: "Moment shape for LT segment",
    children: [],
  },
  {
    type: "user-input",
    key: "support_condition_LT",
    valueType: { type: "string" },
    id: "support_condition_LT",
    name: "Support condition for LT segment",
    children: [],
  },
  {
    type: "user-input",
    key: "load_application_LT",
    valueType: { type: "string" },
    id: "load_application_LT",
    name: "Load application for LT segment",
    children: [],
  },
  {
    type: "user-input",
    key: "section_shape",
    valueType: { type: "string", oneOf: ["I", "RHS", "CHS"] },
    id: "section_shape",
    name: "Section shape family (I, RHS, CHS)",
    children: [],
  },
  {
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    id: "section_class",
    name: "Section class (1, 2, 3, 4)",
    children: [],
  },
  {
    type: "user-input",
    key: "alpha_LT",
    valueType: { type: "number" },
    id: "alpha_LT",
    name: "LTB imperfection factor",
    symbol: "\\alpha_{LT}",
    children: [],
  },
  {
    type: "coefficient",
    key: "gamma_M1",
    valueType: { type: "number" },
    id: "gamma_M1",
    name: "Partial safety factor",
    symbol: "\\gamma_{M1}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
  {
    type: "coefficient",
    key: "lambda_LT_0",
    valueType: { type: "number" },
    id: "lambda_LT_0",
    name: "Plateau length of LTB curves",
    symbol: "\\bar{\\lambda}_{LT,0}",
    meta: { sectionRef: "6.3.2.3" },
    children: [],
  },
  {
    type: "coefficient",
    key: "beta_LT",
    valueType: { type: "number" },
    id: "beta_LT",
    name: "LTB curve parameter",
    symbol: "\\beta",
    meta: { sectionRef: "6.3.2.3" },
    children: [],
  },
  {
    type: "constant",
    key: "pi",
    valueType: { type: "number" },
    id: "pi",
    name: "Pi",
    symbol: "\\pi",
    children: [],
  },
  {
    type: "table",
    key: "k_c",
    valueType: { type: "number" },
    id: "k_c",
    name: "Moment distribution correction factor",
    symbol: "k_c",
    source: "EC3-6.6",
    meta: { sectionRef: "6.3.2.3", tableRef: "6.6" },
    children: [
      { nodeId: "moment_shape_LT" },
      { nodeId: "psi_LT" },
      { nodeId: "support_condition_LT" },
      { nodeId: "load_application_LT" },
    ],
  },
  {
    type: "derived",
    key: "C1",
    valueType: { type: "number" },
    id: "C1",
    name: "Moment gradient factor C1",
    expression: "\\frac{1}{k_c^2}",
    children: [{ nodeId: "k_c" }],
  },
  {
    type: "derived",
    key: "M_cr_Nmm",
    valueType: { type: "number" },
    id: "M_cr_Nmm",
    name: "Elastic critical moment for LTB (SN003b)",
    symbol: "M_{cr}",
    expression:
      "C_1 \\frac{\\pi^2 E_MPa I_z}{L_{cr,LT}^2}\\sqrt{\\frac{I_w}{I_z}+\\frac{L_{cr,LT}^2 G_MPa I_t}{\\pi^2 E_MPa I_z}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.3.2.2", paragraphRef: "(2)" },
    children: [
      { nodeId: "L_mm" },
      { nodeId: "k_LT" },
      { nodeId: "C1" },
      { nodeId: "pi" },
      { nodeId: "E_MPa" },
      { nodeId: "Iz_mm4" },
      { nodeId: "It_mm4" },
      { nodeId: "Iw_mm6" },
      { nodeId: "G_MPa" },
      { nodeId: "torsional_deformations" },
      { nodeId: "section_shape" },
    ],
  },
  {
    type: "derived",
    key: "lambda_bar_LT",
    valueType: { type: "number" },
    id: "lambda_bar_LT",
    name: "Non-dimensional slenderness for LTB",
    symbol: "\\bar{\\lambda}_{LT}",
    expression: "\\sqrt{\\frac{W_{y,res} f_y}{M_{cr}}}",
    children: [
      { nodeId: "W_y_res_mm3" },
      { nodeId: "fy_MPa" },
      { nodeId: "M_cr_Nmm" },
    ],
  },
  {
    type: "derived",
    key: "phi_LT",
    valueType: { type: "number" },
    id: "phi_LT",
    name: "LTB parameter",
    symbol: "\\Phi_{LT}",
    expression:
      "0.5(1 + \\alpha_{LT}(\\bar{\\lambda}_{LT} - \\bar{\\lambda}_{LT,0}) + \\beta \\bar{\\lambda}_{LT}^2)",
    children: [
      { nodeId: "alpha_LT" },
      { nodeId: "lambda_bar_LT" },
      { nodeId: "lambda_LT_0" },
      { nodeId: "beta_LT" },
    ],
  },
  {
    type: "derived",
    key: "chi_LT",
    valueType: { type: "number" },
    id: "chi_LT",
    name: "Capped LTB reduction factor",
    symbol: "\\chi_{LT}",
    expression: "\\min(1,\\min(\\chi_{LT,base}, 1/\\bar{\\lambda}_{LT}^2))",
    children: [
      { nodeId: "phi_LT" },
      { nodeId: "beta_LT" },
      { nodeId: "lambda_bar_LT" },
      { nodeId: "buckling_curves_LT_policy" },
    ],
  },
  {
    type: "derived",
    key: "f_LT",
    valueType: { type: "number" },
    id: "f_LT",
    name: "LT correction factor",
    symbol: "f",
    expression:
      "f = \\min\\left(1, 1 - 0.5(1-k_c)[1-2(\\bar{\\lambda}_{LT}-0.8)^2]\\right)",
    meta: { sectionRef: "6.3.2.3", paragraphRef: "(2)" },
    children: [{ nodeId: "lambda_bar_LT" }, { nodeId: "k_c" }],
  },
  {
    type: "formula",
    key: "chi_LT_mod",
    valueType: { type: "number" },
    id: "chi_LT_mod",
    name: "Modified LT reduction factor",
    symbol: "\\chi_{LT,mod}",
    expression: "\\min\\left(1,\\frac{\\chi_{LT}}{f}\\right)",
    meta: { sectionRef: "6.3.2.3", formulaRef: "(6.58)" },
    children: [{ nodeId: "chi_LT" }, { nodeId: "f_LT" }],
  },
  {
    type: "formula",
    key: "M_b_Rd_Nmm",
    valueType: { type: "number" },
    id: "M_b_Rd_Nmm",
    name: "LTB resistance",
    symbol: "M_{b_mm,Rd}",
    expression: "\\frac{\\chi_{LT,mod} W_{y,res} f_y}{\\gamma_{M1}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.3.2.1", formulaRef: "(6.55)" },
    children: [
      { nodeId: "chi_LT_mod" },
      { nodeId: "W_y_res_mm3" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M1" },
    ],
  },
  {
    type: "derived",
    key: "abs_M_y_Ed_Nmm",
    valueType: { type: "number" },
    id: "abs_M_y_Ed_Nmm",
    name: "Absolute design moment",
    expression: "\\left|M_{y,Ed}\\right|",
    children: [{ nodeId: "M_y_Ed_Nmm" }],
  },
  {
    type: "check",
    key: "ltb_check",
    valueType: { type: "number" },
    id: "ltb_check",
    name: "Lateral-torsional buckling check",
    verificationExpression: "\\frac{M_{y,Ed}}{M_{b_mm,Rd}} \\leq 1.0",
    meta: { sectionRef: "6.3.2.1", verificationRef: "(6.54)" },
    children: [{ nodeId: "abs_M_y_Ed_Nmm" }, { nodeId: "M_b_Rd_Nmm" }],
  },
]);

export type Nodes = typeof nodes;
