import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "bending_z_axial_shear_check",
    type: "check",
    key: "bending_z_axial_shear_check",
    valueType: { type: "number" },
    name: "Bending, axial-force, and shear resistance check about z-z",
    verificationExpression:
      "\\text{class 1/2: }\\frac{\\left|M_{z,Ed}\\right|}{M_{NV,z,Rd}}\\leq1.0\\ ;\\ \\text{class 3: }\\frac{\\sigma_{v,Ed}}{f_y/\\gamma_{M0}}\\leq1.0",
    meta: { sectionRef: "6.2.10", verificationRef: "(6.38),(6.42)" },
    children: [
      {
        nodeId: "utilization_class12",
        when: {
          or: [
            { eq: ["section_class", { value: 1 }] },
            { eq: ["section_class", { value: 2 }] },
          ],
        },
      },
      {
        nodeId: "utilization_class3",
        when: { eq: ["section_class", { value: 3 }] },
      },
    ],
  },
  {
    id: "utilization_class12",
    type: "derived",
    key: "utilization_class12",
    valueType: { type: "number" },
    name: "Class 1/2 utilization ratio about z-z",
    expression: "\\left|M_{z,Ed}\\right|/M_{NV,z,Rd}",
    children: [{ nodeId: "abs_M_z_Ed_Nmm" }, { nodeId: "M_NV_z_Rd_Nmm" }],
  },
  {
    id: "M_NV_z_Rd_Nmm",
    type: "formula",
    key: "M_NV_z_Rd_Nmm",
    valueType: { type: "number" },
    name: "Reduced bending resistance about z-z under axial force and shear",
    symbol: "M_{NV,z,Rd}",
    expression: "M_{z,V,Rd} \\cdot k_z",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.10", formulaRef: "(6.38)" },
    children: [{ nodeId: "M_z_V_Rd_Nmm" }, { nodeId: "k_z" }],
  },
  {
    id: "M_z_V_Rd_Nmm",
    type: "formula",
    key: "M_z_V_Rd_Nmm",
    valueType: { type: "number" },
    name: "Reduced bending resistance about z-z under shear",
    symbol: "M_{z,V,Rd}",
    expression: "\\frac{W_{pl,z,eff} \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.8", formulaRef: "(6.30)" },
    children: [
      { nodeId: "Wpl_z_eff_mm3" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "Wpl_z_eff_mm3",
    type: "derived",
    key: "Wpl_z_eff_mm3",
    valueType: { type: "number" },
    name: "Effective plastic section modulus about z-z under shear",
    expression: "W_{pl,z} - \\rho_y (W_{pl,z} - W_{pl,z,web})",
    unit: "\\mathrm{mm^{3}}",
    children: [
      { nodeId: "Wpl_z_mm3" },
      { nodeId: "rho_y" },
      { nodeId: "Wpl_z_web_mm3" },
    ],
  },
  {
    id: "Wpl_z_web_mm3",
    type: "derived",
    key: "Wpl_z_web_mm3",
    valueType: { type: "number" },
    name: "Web contribution to plastic section modulus about z-z",
    expression: "A_{v,z} t_w / 4",
    unit: "\\mathrm{mm^{3}}",
    children: [{ nodeId: "Av_z_mm2" }, { nodeId: "tw_mm" }],
  },
  {
    id: "k_z",
    type: "derived",
    key: "k_z",
    valueType: { type: "number" },
    name: "Axial reduction factor for z-z branch",
    children: [
      { nodeId: "k_z_i", when: { eq: ["section_shape", { value: "I" }] } },
      {
        nodeId: "k_z_rhs_chs",
        when: {
          or: [
            { eq: ["section_shape", { value: "RHS" }] },
            { eq: ["section_shape", { value: "CHS" }] },
          ],
        },
      },
    ],
  },
  {
    id: "k_z_i",
    type: "derived",
    key: "k_z_i",
    valueType: { type: "number" },
    name: "I-section axial reduction factor for z-z",
    expression:
      "n \\leq a_f \\Rightarrow 1,\\ \\text{else}\\ 1-\\left(\\frac{n-a_f}{1-a_f}\\right)^2",
    children: [{ nodeId: "n" }, { nodeId: "a_f" }],
  },
  {
    id: "k_z_rhs_chs",
    type: "derived",
    key: "k_z_rhs_chs",
    valueType: { type: "number" },
    name: "RHS/CHS axial reduction factor for z-z",
    expression: "\\min\\left(1,\\frac{1-n}{1-0.5a_f}\\right)",
    children: [{ nodeId: "n" }, { nodeId: "a_f" }],
  },
  {
    id: "a_f",
    type: "derived",
    key: "a_f",
    valueType: { type: "number" },
    name: "Limited reduction parameter for z-z branch",
    children: [
      { nodeId: "a_f_i", when: { eq: ["section_shape", { value: "I" }] } },
      { nodeId: "a_f_rhs", when: { eq: ["section_shape", { value: "RHS" }] } },
      { nodeId: "a_f_chs", when: { eq: ["section_shape", { value: "CHS" }] } },
    ],
  },
  {
    id: "a_f_i",
    type: "derived",
    key: "a_f_i",
    valueType: { type: "number" },
    name: "I-section reduction parameter for z-z branch",
    expression: "(A_mm2-2b t_f)/A_mm2",
    children: [{ nodeId: "A_mm2" }, { nodeId: "b_mm" }, { nodeId: "tf_mm" }],
  },
  {
    id: "a_f_rhs",
    type: "derived",
    key: "a_f_rhs",
    valueType: { type: "number" },
    name: "RHS section reduction parameter for z-z branch",
    expression: "(A_mm2-2ht)/A_mm2",
    children: [{ nodeId: "A_mm2" }, { nodeId: "h_mm" }, { nodeId: "t_mm" }],
  },
  {
    id: "a_f_chs",
    type: "derived",
    key: "a_f_chs",
    valueType: { type: "number" },
    name: "CHS section reduction parameter for z-z branch",
    expression: "0.5",
    children: [],
  },
  {
    id: "n",
    type: "derived",
    key: "n",
    valueType: { type: "number" },
    name: "Axial force ratio",
    symbol: "n",
    expression: "\\frac{\\left|N_{Ed}\\right|}{N_{pl,Rd}}",
    children: [{ nodeId: "abs_N_Ed_N" }, { nodeId: "N_pl_Rd_N" }],
  },
  {
    id: "N_pl_Rd_N",
    type: "formula",
    key: "N_pl_Rd_N",
    valueType: { type: "number" },
    name: "Plastic resistance to normal force",
    symbol: "N_{pl,Rd}",
    expression: "\\frac{A_mm2 \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.4", formulaRef: "(6.10)" },
    children: [
      { nodeId: "A_mm2" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "rho_y",
    type: "derived",
    key: "rho_y",
    valueType: { type: "number" },
    name: "Shear reduction factor about y-y",
    expression:
      "\\left(\\frac{2\\left|V_{y,Ed}\\right|}{V_{pl,y,Rd}} - 1\\right)^2 \\text{ for } \\frac{\\left|V_{y,Ed}\\right|}{V_{pl,y,Rd}} > 0.5, \\text{ else } 0",
    symbol: "\\rho_y",
    children: [{ nodeId: "abs_V_y_Ed_N" }, { nodeId: "V_pl_y_Rd_N" }],
  },
  {
    id: "V_pl_y_Rd_N",
    type: "formula",
    key: "V_pl_y_Rd_N",
    valueType: { type: "number" },
    name: "Plastic shear resistance about y-y",
    symbol: "V_{pl,y,Rd}",
    expression: "\\dfrac{A_{v,y} \\cdot f_y}{\\sqrt{3}\\,\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.6", formulaRef: "(6.18)" },
    children: [
      { nodeId: "Av_y_mm2" },
      { nodeId: "fy_MPa" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "utilization_class3",
    type: "derived",
    key: "utilization_class3",
    valueType: { type: "number" },
    name: "Class 3 Von Mises utilization ratio",
    expression: "\\sigma_{v,Ed}/(f_y/\\gamma_{M0})",
    children: [{ nodeId: "sigma_v_class3_MPa" }, { nodeId: "sigma_limit_MPa" }],
  },
  {
    id: "sigma_v_class3_MPa",
    type: "derived",
    key: "sigma_v_class3_MPa",
    valueType: { type: "number" },
    name: "Equivalent Von Mises stress for class 3",
    expression: "\\sqrt{\\sigma_x^2+3\\tau_y_MPa^2}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "sigma_x_class3_MPa" }, { nodeId: "tau_y_MPa" }],
  },
  {
    id: "sigma_x_class3_MPa",
    type: "derived",
    key: "sigma_x_class3_MPa",
    valueType: { type: "number" },
    name: "Longitudinal normal stress for class 3",
    expression: "\\sigma_N_MPa+\\sigma_{M,z}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "sigma_N_MPa" }, { nodeId: "sigma_M_z_MPa" }],
  },
  {
    id: "sigma_N_MPa",
    type: "derived",
    key: "sigma_N_MPa",
    valueType: { type: "number" },
    name: "Axial stress contribution",
    expression: "\\left|N_{Ed}\\right|/A_mm2",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_N_Ed_N" }, { nodeId: "A_mm2" }],
  },
  {
    id: "sigma_M_z_MPa",
    type: "derived",
    key: "sigma_M_z_MPa",
    valueType: { type: "number" },
    name: "Bending stress contribution about z-z",
    expression: "\\left|M_{z,Ed}\\right|/W_{el,z}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_M_z_Ed_Nmm" }, { nodeId: "Wel_z_mm3" }],
  },
  {
    id: "tau_y_MPa",
    type: "derived",
    key: "tau_y_MPa",
    valueType: { type: "number" },
    name: "Average shear stress from V_y",
    expression: "\\left|V_{y,Ed}\\right|/A_{v,y}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_V_y_Ed_N" }, { nodeId: "Av_y_mm2" }],
  },
  {
    id: "sigma_limit_MPa",
    type: "formula",
    key: "sigma_limit_MPa",
    valueType: { type: "number" },
    name: "Class 3 stress limit",
    symbol: "f_y/\\gamma_{M0}",
    expression: "\\frac{f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{MPa}",
    meta: { sectionRef: "6.2.10", formulaRef: "(6.42)" },
    children: [{ nodeId: "fy_MPa" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "abs_M_z_Ed_Nmm",
    type: "derived",
    key: "abs_M_z_Ed_Nmm",
    valueType: { type: "number" },
    name: "Design bending moment magnitude about z-z",
    expression: "\\left|M_{z,Ed}\\right|",
    unit: "\\mathrm{N\\cdot mm}",
    children: [{ nodeId: "M_z_Ed_Nmm" }],
  },
  {
    id: "abs_N_Ed_N",
    type: "derived",
    key: "abs_N_Ed_N",
    valueType: { type: "number" },
    name: "Design axial force magnitude",
    expression: "\\left|N_{Ed}\\right|",
    unit: "\\mathrm{N}",
    children: [{ nodeId: "N_Ed_N" }],
  },
  {
    id: "abs_V_y_Ed_N",
    type: "derived",
    key: "abs_V_y_Ed_N",
    valueType: { type: "number" },
    name: "Design shear force magnitude about y-y",
    expression: "\\left|V_{y,Ed}\\right|",
    unit: "\\mathrm{N}",
    children: [{ nodeId: "V_y_Ed_N" }],
  },
  {
    id: "M_z_Ed_Nmm",
    type: "user-input",
    key: "M_z_Ed_Nmm",
    valueType: { type: "number" },
    name: "Design bending moment about z-z",
    symbol: "M_{z,Ed}",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "N_Ed_N",
    type: "user-input",
    key: "N_Ed_N",
    valueType: { type: "number" },
    name: "Design axial force",
    symbol: "N_{Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "V_y_Ed_N",
    type: "user-input",
    key: "V_y_Ed_N",
    valueType: { type: "number" },
    name: "Design shear force about y-y",
    symbol: "V_{y,Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "section_shape",
    type: "user-input",
    key: "section_shape",
    valueType: { type: "string", oneOf: ["I", "RHS", "CHS"] },
    name: "Section shape family",
    symbol: "\\text{shape}",
    children: [],
  },
  {
    id: "section_class",
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    name: "Section class",
    symbol: "\\text{class}",
    children: [],
  },
  {
    id: "A_mm2",
    type: "user-input",
    key: "A_mm2",
    valueType: { type: "number" },
    name: "Cross-sectional area",
    symbol: "A_mm2",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "b_mm",
    type: "user-input",
    key: "b_mm",
    valueType: { type: "number" },
    name: "Section width",
    symbol: "b_mm",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "h_mm",
    type: "user-input",
    key: "h_mm",
    valueType: { type: "number" },
    name: "Section depth",
    symbol: "h_mm",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tf_mm",
    type: "user-input",
    key: "tf_mm",
    valueType: { type: "number" },
    name: "Flange thickness",
    symbol: "t_f",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "t_mm",
    type: "user-input",
    key: "t_mm",
    valueType: { type: "number" },
    name: "Wall thickness",
    symbol: "t_mm",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "Wel_z_mm3",
    type: "user-input",
    key: "Wel_z_mm3",
    valueType: { type: "number" },
    name: "Elastic section modulus about z-z",
    symbol: "W_{el,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wpl_z_mm3",
    type: "user-input",
    key: "Wpl_z_mm3",
    valueType: { type: "number" },
    name: "Plastic section modulus about z-z",
    symbol: "W_{pl,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Av_y_mm2",
    type: "user-input",
    key: "Av_y_mm2",
    valueType: { type: "number" },
    name: "Shear area about y-y",
    symbol: "A_{v,y}",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "Av_z_mm2",
    type: "user-input",
    key: "Av_z_mm2",
    valueType: { type: "number" },
    name: "Shear area about z-z",
    symbol: "A_{v,z}",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "tw_mm",
    type: "user-input",
    key: "tw_mm",
    valueType: { type: "number" },
    name: "Web or wall thickness",
    symbol: "t_w",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "fy_MPa",
    type: "user-input",
    key: "fy_MPa",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
