import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "biaxial_axial_check",
    type: "check",
    key: "biaxial_axial_check",
    valueType: { type: "number" },
    name: "Biaxial bending and axial force interaction check",
    verificationExpression:
      "\\text{class 1/2: }\\left(\\frac{|M_{y,Ed}|}{M_{N,y,Rd}}\\right)^\\alpha + \\left(\\frac{|M_{z,Ed}|}{M_{N,z,Rd}}\\right)^\\beta\\leq1.0\\ ;\\ \\text{class 3: }\\frac{\\sigma_{x,Ed}}{f_y/\\gamma_{M0}}\\leq1.0",
    meta: { sectionRef: "6.2.9", verificationRef: "(6.41),(6.42)" },
    children: [
      {
        nodeId: "utilization_class12",
        when: {
          or: [{ eq: ["section_class", { value: 1 }] }, { eq: ["section_class", { value: 2 }] }],
        },
      },
      {
        nodeId: "utilization_class3",
        when: { eq: ["section_class", { value: 3 }] },
      },
    ],
  },
  {
    id: "utilization_y",
    type: "derived",
    key: "utilization_y",
    valueType: { type: "number" },
    name: "Moment ratio about y-y",
    expression: "|M_y_Ed|/M_N_y_Rd",
    children: [{ nodeId: "abs_M_y_Ed" }, { nodeId: "M_N_y_Rd" }],
  },
  {
    id: "abs_M_y_Ed",
    type: "derived",
    key: "abs_M_y_Ed",
    valueType: { type: "number" },
    name: "Design bending moment magnitude about y-y",
    expression: "\\left|M_{y,Ed}\\right|",
    unit: "\\mathrm{N\\cdot mm}",
    children: [{ nodeId: "M_y_Ed" }],
  },
  {
    id: "M_y_Ed",
    type: "user-input",
    key: "M_y_Ed",
    valueType: { type: "number" },
    name: "Design bending moment about y-y",
    symbol: "M_{y,Ed}",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "M_N_y_Rd",
    type: "formula",
    key: "M_N_y_Rd",
    valueType: { type: "number" },
    name: "Reduced bending resistance about y-y under axial force",
    symbol: "M_{N,y,Rd}",
    expression: "M_{pl,y,Rd}*k_y",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.36)" },
    children: [{ nodeId: "M_pl_y_Rd" }, { nodeId: "k_y" }],
  },
  {
    id: "M_pl_y_Rd",
    type: "formula",
    key: "M_pl_y_Rd",
    valueType: { type: "number" },
    name: "Design bending resistance about y-y",
    symbol: "M_{pl,y,Rd}",
    expression: "\\frac{W_{y,res} \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.5", formulaRef: "(6.13)" },
    children: [{ nodeId: "W_y_res" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "W_y_res",
    type: "derived",
    key: "W_y_res",
    valueType: { type: "number" },
    name: "Class-dependent resistance modulus about y-y",
    symbol: "W_{y,res}",
    unit: "\\mathrm{mm^{3}}",
    children: [
      {
        nodeId: "W_y_res_class12",
        when: {
          or: [{ eq: ["section_class", { value: 1 }] }, { eq: ["section_class", { value: 2 }] }],
        },
      },
      {
        nodeId: "W_y_res_class3",
        when: { eq: ["section_class", { value: 3 }] },
      },
    ],
  },
  {
    id: "section_class",
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    name: "Section class",
    symbol: "\\text{class}",
    children: [],
  },
  {
    id: "W_y_res_class12",
    type: "derived",
    key: "W_y_res_class12",
    valueType: { type: "number" },
    name: "Class 1/2 resistance modulus about y-y",
    expression: "W_{pl,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [{ nodeId: "Wpl_y" }],
  },
  {
    id: "W_y_res_class3",
    type: "derived",
    key: "W_y_res_class3",
    valueType: { type: "number" },
    name: "Class 3 resistance modulus about y-y",
    expression: "W_{el,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [{ nodeId: "Wel_y" }],
  },
  {
    id: "Wpl_y",
    type: "user-input",
    key: "Wpl_y",
    valueType: { type: "number" },
    name: "Plastic section modulus about y-y",
    symbol: "W_{pl,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wel_y",
    type: "user-input",
    key: "Wel_y",
    valueType: { type: "number" },
    name: "Elastic section modulus about y-y",
    symbol: "W_{el,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "k_y",
    type: "derived",
    key: "k_y",
    valueType: { type: "number" },
    name: "Axial reduction factor about y-y",
    children: [
      { nodeId: "k_y_i", when: { eq: ["section_shape", { value: "I" }] } },
      {
        nodeId: "k_y_rhs_chs",
        when: {
          or: [
            { eq: ["section_shape", { value: "RHS" }] },
            { eq: ["section_shape", { value: "CHS" }] },
          ],
        },
      },
    ],
  },
  {
    id: "k_y_i",
    type: "derived",
    key: "k_y_i",
    valueType: { type: "number" },
    name: "I-section axial reduction factor for y-y",
    symbol: "k_{y,I}",
    expression:
      "n \\leq 0.5a_w \\Rightarrow 1,\\ \\text{else}\\ 1-\\left(\\frac{n-0.5a_w}{1-0.5a_w}\\right)^2",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.33)" },
    children: [{ nodeId: "n" }, { nodeId: "a_w" }],
  },
  {
    id: "k_y_rhs_chs",
    type: "derived",
    key: "k_y_rhs_chs",
    valueType: { type: "number" },
    name: "RHS/CHS axial reduction factor for y-y",
    symbol: "k_{y,RHS}",
    expression: "\\min\\left(1,\\dfrac{1-n}{1-0.5a_w}\\right)",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.35)" },
    children: [{ nodeId: "n" }, { nodeId: "a_w" }],
  },
  {
    id: "a_w",
    type: "derived",
    key: "a_w",
    valueType: { type: "number" },
    name: "Limited web ratio for y-y branch",
    children: [
      { nodeId: "a_w_i", when: { eq: ["section_shape", { value: "I" }] } },
      { nodeId: "a_w_rhs", when: { eq: ["section_shape", { value: "RHS" }] } },
      { nodeId: "a_w_chs", when: { eq: ["section_shape", { value: "CHS" }] } },
    ],
  },
  {
    id: "a_w_i",
    type: "derived",
    key: "a_w_i",
    valueType: { type: "number" },
    name: "I-section y-y raw reduction ratio",
    expression: "(A-2b t_f)/A",
    children: [{ nodeId: "A" }, { nodeId: "b" }, { nodeId: "tf" }],
  },
  {
    id: "a_w_rhs",
    type: "derived",
    key: "a_w_rhs",
    valueType: { type: "number" },
    name: "RHS section y-y raw reduction ratio",
    expression: "(A-2b t)/A",
    children: [{ nodeId: "A" }, { nodeId: "b" }, { nodeId: "t" }],
  },
  {
    id: "a_w_chs",
    type: "derived",
    key: "a_w_chs",
    valueType: { type: "number" },
    name: "CHS section y-y raw reduction ratio",
    expression: "0.5",
    children: [],
  },
  {
    id: "n",
    type: "derived",
    key: "n",
    valueType: { type: "number" },
    name: "Axial force ratio",
    symbol: "n",
    expression: "\\frac{\\left|N_{Ed}\\right|}{N_{pl,Rd}}",
    children: [{ nodeId: "N_c_Ed" }, { nodeId: "N_pl_Rd" }],
  },
  {
    id: "N_c_Ed",
    type: "derived",
    key: "N_c_Ed",
    valueType: { type: "number" },
    name: "Design axial force magnitude",
    expression: "\\left|N_{Ed}\\right|",
    unit: "\\mathrm{N}",
    children: [{ nodeId: "N_Ed" }],
  },
  {
    id: "abs_N_Ed",
    type: "derived",
    key: "abs_N_Ed",
    valueType: { type: "number" },
    name: "Design axial force magnitude",
    expression: "\\left|N_{Ed}\\right|",
    unit: "\\mathrm{N}",
    children: [{ nodeId: "N_Ed" }],
  },
  {
    id: "N_Ed",
    type: "user-input",
    key: "N_Ed",
    valueType: { type: "number" },
    name: "Design axial force",
    symbol: "N_{Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "N_pl_Rd",
    type: "formula",
    key: "N_pl_Rd",
    valueType: { type: "number" },
    name: "Plastic resistance to normal force",
    symbol: "N_{pl,Rd}",
    expression: "\\frac{A \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.4", formulaRef: "(6.10)" },
    children: [{ nodeId: "A" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "A",
    type: "user-input",
    key: "A",
    valueType: { type: "number" },
    name: "Cross-sectional area",
    symbol: "A",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "section_shape",
    type: "user-input",
    key: "section_shape",
    valueType: { type: "string", oneOf: ["I", "RHS", "CHS"] },
    name: "Section shape family",
    symbol: "\\text{shape}",
    children: [],
  },
  {
    id: "b",
    type: "user-input",
    key: "b",
    valueType: { type: "number" },
    name: "Section width",
    symbol: "b",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "h",
    type: "user-input",
    key: "h",
    valueType: { type: "number" },
    name: "Section depth",
    symbol: "h",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "tf",
    type: "user-input",
    key: "tf",
    valueType: { type: "number" },
    name: "Flange thickness",
    symbol: "t_f",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "t",
    type: "user-input",
    key: "t",
    valueType: { type: "number" },
    name: "Wall thickness",
    symbol: "t",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "utilization_class12",
    type: "derived",
    key: "utilization_class12",
    valueType: { type: "number" },
    name: "Class 1/2 utilization ratio for biaxial interaction",
    expression: "utilization_y^alpha_biax+utilization_z^beta_biax",
    children: [
      { nodeId: "utilization_y" },
      { nodeId: "alpha_biax" },
      { nodeId: "utilization_z" },
      { nodeId: "beta_biax" },
    ],
  },
  {
    id: "utilization_z",
    type: "derived",
    key: "utilization_z",
    valueType: { type: "number" },
    name: "Moment ratio about z-z",
    expression: "|M_z_Ed|/M_N_z_Rd",
    children: [{ nodeId: "abs_M_z_Ed" }, { nodeId: "M_N_z_Rd" }],
  },
  {
    id: "abs_M_z_Ed",
    type: "derived",
    key: "abs_M_z_Ed",
    valueType: { type: "number" },
    name: "Design bending moment magnitude about z-z",
    expression: "\\left|M_{z,Ed}\\right|",
    unit: "\\mathrm{N\\cdot mm}",
    children: [{ nodeId: "M_z_Ed" }],
  },
  {
    id: "M_z_Ed",
    type: "user-input",
    key: "M_z_Ed",
    valueType: { type: "number" },
    name: "Design bending moment about z-z",
    symbol: "M_{z,Ed}",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "M_N_z_Rd",
    type: "formula",
    key: "M_N_z_Rd",
    valueType: { type: "number" },
    name: "Reduced bending resistance about z-z under axial force",
    symbol: "M_{N,z,Rd}",
    expression: "M_{pl,z,Rd}*k_z",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.9.1", formulaRef: "(6.38)" },
    children: [{ nodeId: "M_pl_z_Rd" }, { nodeId: "k_z" }],
  },
  {
    id: "M_pl_z_Rd",
    type: "formula",
    key: "M_pl_z_Rd",
    valueType: { type: "number" },
    name: "Design bending resistance about z-z",
    symbol: "M_{pl,z,Rd}",
    expression: "\\frac{W_{z,res} \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.5", formulaRef: "(6.13)" },
    children: [{ nodeId: "W_z_res" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "W_z_res",
    type: "derived",
    key: "W_z_res",
    valueType: { type: "number" },
    name: "Class-dependent resistance modulus about z-z",
    symbol: "W_{z,res}",
    unit: "\\mathrm{mm^{3}}",
    children: [
      {
        nodeId: "W_z_res_class12",
        when: {
          or: [{ eq: ["section_class", { value: 1 }] }, { eq: ["section_class", { value: 2 }] }],
        },
      },
      {
        nodeId: "W_z_res_class3",
        when: { eq: ["section_class", { value: 3 }] },
      },
    ],
  },
  {
    id: "W_z_res_class12",
    type: "derived",
    key: "W_z_res_class12",
    valueType: { type: "number" },
    name: "Class 1/2 resistance modulus about z-z",
    expression: "W_{pl,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [{ nodeId: "Wpl_z" }],
  },
  {
    id: "W_z_res_class3",
    type: "derived",
    key: "W_z_res_class3",
    valueType: { type: "number" },
    name: "Class 3 resistance modulus about z-z",
    expression: "W_{el,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [{ nodeId: "Wel_z" }],
  },
  {
    id: "Wpl_z",
    type: "user-input",
    key: "Wpl_z",
    valueType: { type: "number" },
    name: "Plastic section modulus about z-z",
    symbol: "W_{pl,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wel_z",
    type: "user-input",
    key: "Wel_z",
    valueType: { type: "number" },
    name: "Elastic section modulus about z-z",
    symbol: "W_{el,z}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "k_z",
    type: "derived",
    key: "k_z",
    valueType: { type: "number" },
    name: "Axial reduction factor about z-z",
    children: [
      { nodeId: "k_z_i", when: { eq: ["section_shape", { value: "I" }] } },
      {
        nodeId: "k_z_rhs_chs",
        when: {
          or: [
            { eq: ["section_shape", { value: "RHS" }] },
            { eq: ["section_shape", { value: "CHS" }] },
          ],
        },
      },
    ],
  },
  {
    id: "k_z_i",
    type: "derived",
    key: "k_z_i",
    valueType: { type: "number" },
    name: "I-section axial reduction factor for z-z",
    expression: "n \\leq a_f \\Rightarrow 1,\\ \\text{else}\\ 1-\\left(\\frac{n-a_f}{1-a_f}\\right)^2",
    children: [{ nodeId: "n" }, { nodeId: "a_f" }],
  },
  {
    id: "k_z_rhs_chs",
    type: "derived",
    key: "k_z_rhs_chs",
    valueType: { type: "number" },
    name: "RHS/CHS axial reduction factor for z-z",
    expression: "\\min\\left(1,\\frac{1-n}{1-0.5a_f}\\right)",
    children: [{ nodeId: "n" }, { nodeId: "a_f" }],
  },
  {
    id: "a_f",
    type: "derived",
    key: "a_f",
    valueType: { type: "number" },
    name: "Limited reduction parameter for z-z branch",
    children: [
      { nodeId: "a_f_i", when: { eq: ["section_shape", { value: "I" }] } },
      { nodeId: "a_f_rhs", when: { eq: ["section_shape", { value: "RHS" }] } },
      { nodeId: "a_f_chs", when: { eq: ["section_shape", { value: "CHS" }] } },
    ],
  },
  {
    id: "a_f_i",
    type: "derived",
    key: "a_f_i",
    valueType: { type: "number" },
    name: "I-section z-z raw reduction ratio",
    expression: "(A-2b t_f)/A",
    children: [{ nodeId: "A" }, { nodeId: "b" }, { nodeId: "tf" }],
  },
  {
    id: "a_f_rhs",
    type: "derived",
    key: "a_f_rhs",
    valueType: { type: "number" },
    name: "RHS section z-z raw reduction ratio",
    expression: "(A-2ht)/A",
    children: [{ nodeId: "A" }, { nodeId: "h" }, { nodeId: "t" }],
  },
  {
    id: "a_f_chs",
    type: "derived",
    key: "a_f_chs",
    valueType: { type: "number" },
    name: "CHS section z-z raw reduction ratio",
    expression: "0.5",
    children: [],
  },
  {
    id: "alpha_biax",
    type: "derived",
    key: "alpha_biax",
    valueType: { type: "number" },
    name: "Biaxial interaction exponent alpha",
    symbol: "\\alpha",
    children: [
      {
        nodeId: "alpha_biax_i",
        when: { eq: ["section_shape", { value: "I" }] },
      },
      {
        nodeId: "alpha_biax_rhs",
        when: { eq: ["section_shape", { value: "RHS" }] },
      },
      {
        nodeId: "alpha_biax_chs",
        when: { eq: ["section_shape", { value: "CHS" }] },
      },
    ],
  },
  {
    id: "alpha_biax_i",
    type: "derived",
    key: "alpha_biax_i",
    valueType: { type: "number" },
    name: "I-section alpha exponent",
    symbol: "\\alpha_I",
    expression: "2",
    children: [],
  },
  {
    id: "alpha_biax_rhs",
    type: "derived",
    key: "alpha_biax_rhs",
    valueType: { type: "number" },
    name: "RHS-section alpha exponent",
    symbol: "\\alpha_{RHS}",
    expression: "rhs_exp",
    children: [{ nodeId: "rhs_exp" }],
  },
  {
    id: "alpha_biax_chs",
    type: "derived",
    key: "alpha_biax_chs",
    valueType: { type: "number" },
    name: "CHS alpha exponent",
    symbol: "\\alpha_{CHS}",
    expression: "2",
    children: [],
  },
  {
    id: "beta_biax",
    type: "derived",
    key: "beta_biax",
    valueType: { type: "number" },
    name: "Biaxial interaction exponent beta",
    symbol: "\\beta",
    children: [
      {
        nodeId: "beta_biax_i",
        when: { eq: ["section_shape", { value: "I" }] },
      },
      {
        nodeId: "beta_biax_rhs",
        when: { eq: ["section_shape", { value: "RHS" }] },
      },
      {
        nodeId: "beta_biax_chs",
        when: { eq: ["section_shape", { value: "CHS" }] },
      },
    ],
  },
  {
    id: "beta_biax_i",
    type: "derived",
    key: "beta_biax_i",
    valueType: { type: "number" },
    name: "I-section beta exponent",
    symbol: "\\beta_I",
    expression: "max(1,5n)",
    children: [{ nodeId: "n" }],
  },
  {
    id: "beta_biax_rhs",
    type: "derived",
    key: "beta_biax_rhs",
    valueType: { type: "number" },
    name: "RHS-section beta exponent",
    symbol: "\\beta_{RHS}",
    expression: "rhs_exp",
    children: [{ nodeId: "rhs_exp" }],
  },
  {
    id: "beta_biax_chs",
    type: "derived",
    key: "beta_biax_chs",
    valueType: { type: "number" },
    name: "CHS beta exponent",
    symbol: "\\beta_{CHS}",
    expression: "2",
    children: [],
  },
  {
    id: "rhs_exp",
    type: "derived",
    key: "rhs_exp",
    valueType: { type: "number" },
    name: "RHS exponent with cap",
    expression: "1-1.13*n^2 <= 0 ? 6 : min(1.66/(1-1.13*n^2),6)",
    children: [{ nodeId: "n" }],
  },
  {
    id: "sigma_N",
    type: "derived",
    key: "sigma_N",
    valueType: { type: "number" },
    name: "Axial stress contribution",
    expression: "\\left|N_{Ed}\\right|/A",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_N_Ed" }, { nodeId: "A" }],
  },
  {
    id: "sigma_M_y",
    type: "derived",
    key: "sigma_M_y",
    valueType: { type: "number" },
    name: "y-y bending stress contribution",
    expression: "\\left|M_{y,Ed}\\right|/W_{el,y}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_M_y_Ed" }, { nodeId: "Wel_y" }],
  },
  {
    id: "sigma_M_z",
    type: "derived",
    key: "sigma_M_z",
    valueType: { type: "number" },
    name: "z-z bending stress contribution",
    expression: "\\left|M_{z,Ed}\\right|/W_{el,z}",
    unit: "\\mathrm{MPa}",
    children: [{ nodeId: "abs_M_z_Ed" }, { nodeId: "Wel_z" }],
  },
  {
    id: "sigma_x_class3",
    type: "derived",
    key: "sigma_x_class3",
    valueType: { type: "number" },
    name: "Maximum longitudinal stress for class 3",
    expression: "\\sigma_N+\\sigma_{M,y}+\\sigma_{M,z}",
    unit: "\\mathrm{MPa}",
    children: [
      { nodeId: "sigma_N" },
      { nodeId: "sigma_M_y" },
      { nodeId: "sigma_M_z" },
    ],
  },
  {
    id: "sigma_limit",
    type: "formula",
    key: "sigma_limit",
    valueType: { type: "number" },
    name: "Class 3 stress limit",
    symbol: "f_y/\\gamma_{M0}",
    expression: "\\frac{f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{MPa}",
    meta: { sectionRef: "6.2.9.2", formulaRef: "(6.42)" },
    children: [{ nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "utilization_class3",
    type: "derived",
    key: "utilization_class3",
    valueType: { type: "number" },
    name: "Class 3 stress utilization ratio",
    expression: "\\sigma_{x,Ed}/(f_y/\\gamma_{M0})",
    children: [{ nodeId: "sigma_x_class3" }, { nodeId: "sigma_limit" }],
  },
  {
    id: "fy",
    type: "user-input",
    key: "fy",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
