import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "bending_y_shear_check",
    type: "check",
    key: "bending_y_shear_check",
    valueType: { type: "number" },
    name: "Bending and shear resistance check about y-y",
    verificationExpression:
      "\\frac{\\left|M_{y,Ed}\\right|}{M_{y,V,Rd}} \\leq 1.0",
    meta: { sectionRef: "6.2.8", verificationRef: "(6.29)" },
    children: [{ nodeId: "abs_M_y_Ed" }, { nodeId: "M_y_V_Rd" }],
  },
  {
    id: "abs_M_y_Ed",
    type: "derived",
    key: "abs_M_y_Ed",
    valueType: { type: "number" },
    name: "Design bending moment magnitude about y-y",
    expression: "\\left|M_{y,Ed}\\right|",
    unit: "\\mathrm{N\\cdot mm}",
    children: [{ nodeId: "M_y_Ed" }],
  },
  {
    id: "M_y_Ed",
    type: "user-input",
    key: "M_y_Ed",
    valueType: { type: "number" },
    name: "Design bending moment about y-y",
    symbol: "M_{y,Ed}",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "M_y_V_Rd",
    type: "formula",
    key: "M_y_V_Rd",
    valueType: { type: "number" },
    name: "Reduced bending resistance about y-y under shear",
    symbol: "M_{y,V,Rd}",
    expression:
      "\\frac{\\left(W_{y,res} - \\rho \\dfrac{A_{v,z}^2}{4t_w}\\right) \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.8", formulaRef: "(6.30)" },
    children: [{ nodeId: "W_y_eff" }, { nodeId: "fy" }, { nodeId: "gamma_M0" }],
  },
  {
    id: "W_y_eff",
    type: "derived",
    key: "W_y_eff",
    valueType: { type: "number" },
    name: "Effective resistance modulus about y-y under shear",
    expression: "W_{y,res} - \\rho\\dfrac{A_{v,z}^2}{4t_w}",
    unit: "\\mathrm{mm^{3}}",
    children: [
      { nodeId: "section_shape" },
      {
        nodeId: "W_y_eff_i",
        when: { eq: ["section_shape", "I"] },
      },
      {
        nodeId: "W_y_eff_rhs",
        when: { eq: ["section_shape", "RHS"] },
      },
      {
        nodeId: "W_y_eff_chs",
        when: { eq: ["section_shape", "CHS"] },
      },
    ],
  },
  {
    id: "W_y_eff_i",
    type: "derived",
    key: "W_y_eff_i",
    valueType: { type: "number" },
    name: "I-section effective resistance modulus about y-y under shear",
    expression: "W_{y,res} - \\rho\\dfrac{A_{v,z}^2}{4t_w}",
    unit: "\\mathrm{mm^{3}}",
    children: [
      { nodeId: "W_y_res" },
      { nodeId: "rho_z" },
      { nodeId: "Av_z" },
      { nodeId: "tw" },
    ],
  },
  {
    id: "W_y_eff_rhs",
    type: "derived",
    key: "W_y_eff_rhs",
    valueType: { type: "number" },
    name: "RHS section effective resistance modulus about y-y under shear",
    expression: "W_{y,res}(1-\\rho)",
    unit: "\\mathrm{mm^{3}}",
    children: [{ nodeId: "W_y_res" }, { nodeId: "rho_z" }],
  },
  {
    id: "W_y_eff_chs",
    type: "derived",
    key: "W_y_eff_chs",
    valueType: { type: "number" },
    name: "CHS section effective resistance modulus about y-y under shear",
    expression: "W_{y,res}(1-\\rho)",
    unit: "\\mathrm{mm^{3}}",
    children: [{ nodeId: "W_y_res" }, { nodeId: "rho_z" }],
  },
  {
    id: "W_y_res",
    type: "derived",
    key: "W_y_res",
    valueType: { type: "number" },
    name: "Class-dependent resistance modulus about y-y",
    expression: "\\text{class 1/2 ? }W_{pl,y}:W_{el,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [
      { nodeId: "section_class" },
      {
        nodeId: "W_y_res_class12",
        when: {
          or: [{ eq: ["section_class", 1] }, { eq: ["section_class", 2] }],
        },
      },
      {
        nodeId: "W_y_res_class3",
        when: { eq: ["section_class", 3] },
      },
    ],
  },
  {
    id: "W_y_res_class12",
    type: "derived",
    key: "W_y_res_class12",
    valueType: { type: "number" },
    name: "Class 1/2 resistance modulus about y-y",
    expression: "W_{pl,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [{ nodeId: "Wpl_y" }],
  },
  {
    id: "W_y_res_class3",
    type: "derived",
    key: "W_y_res_class3",
    valueType: { type: "number" },
    name: "Class 3 resistance modulus about y-y",
    expression: "W_{el,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [{ nodeId: "Wel_y" }],
  },
  {
    id: "section_class",
    type: "user-input",
    key: "section_class",
    valueType: { type: "number" },
    name: "Section class",
    symbol: "\\text{class}",
    children: [],
  },
  {
    id: "section_shape",
    type: "user-input",
    key: "section_shape",
    valueType: { type: "string", literal: ["I", "RHS", "CHS"] },
    name: "Section shape family",
    symbol: "\\text{shape}",
    children: [],
  },
  {
    id: "Wpl_y",
    type: "user-input",
    key: "Wpl_y",
    valueType: { type: "number" },
    name: "Plastic section modulus about y-y",
    symbol: "W_{pl,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wel_y",
    type: "user-input",
    key: "Wel_y",
    valueType: { type: "number" },
    name: "Elastic section modulus about y-y",
    symbol: "W_{el,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "rho_z",
    type: "derived",
    key: "rho_z",
    valueType: { type: "number" },
    name: "Shear reduction factor",
    expression: "\\text{branch-selected }\\rho_z",
    symbol: "\\rho",
    children: [
      { nodeId: "shear_utilization_z" },
      {
        nodeId: "rho_z_1",
        when: { lte: ["shear_utilization_z", 0.5] },
      },
      {
        nodeId: "rho_z_2",
        when: { gt: ["shear_utilization_z", 0.5] },
      },
    ],
  },
  {
    id: "rho_z_1",
    type: "derived",
    key: "rho_z_1",
    valueType: { type: "number" },
    name: "Shear reduction factor for low-shear branch",
    expression: "0",
    children: [{ nodeId: "shear_utilization_z" }],
  },
  {
    id: "rho_z_2",
    type: "derived",
    key: "rho_z_2",
    valueType: { type: "number" },
    name: "Shear reduction factor for high-shear branch",
    expression: "\\left(2u_z - 1\\right)^2",
    children: [{ nodeId: "shear_utilization_z" }],
  },
  {
    id: "abs_V_z_Ed",
    type: "derived",
    key: "abs_V_z_Ed",
    valueType: { type: "number" },
    name: "Design shear force magnitude about z-z",
    expression: "\\left|V_{z,Ed}\\right|",
    unit: "\\mathrm{N}",
    children: [{ nodeId: "V_z_Ed" }],
  },
  {
    id: "V_z_Ed",
    type: "user-input",
    key: "V_z_Ed",
    valueType: { type: "number" },
    name: "Design shear force about z-z",
    symbol: "V_{z,Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "V_pl_z_Rd",
    type: "formula",
    key: "V_pl_z_Rd",
    valueType: { type: "number" },
    name: "Plastic shear resistance about z-z",
    symbol: "V_{pl,z,Rd}",
    expression: "\\dfrac{A_{v,z} \\cdot f_y}{\\sqrt{3}\\,\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.6", formulaRef: "(6.18)" },
    children: [
      { nodeId: "Av_z" },
      { nodeId: "fy" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "shear_utilization_z",
    type: "derived",
    key: "shear_utilization_z",
    valueType: { type: "number" },
    name: "Shear utilization about z-z",
    expression: "\\left|V_{z,Ed}\\right| / V_{pl,z,Rd}",
    children: [{ nodeId: "abs_V_z_Ed" }, { nodeId: "V_pl_z_Rd" }],
  },
  {
    id: "Av_z",
    type: "user-input",
    key: "Av_z",
    valueType: { type: "number" },
    name: "Shear area about z-z",
    symbol: "A_{v,z}",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "tw",
    type: "user-input",
    key: "tw",
    valueType: { type: "number" },
    name: "Web thickness",
    symbol: "t_w",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "fy",
    type: "user-input",
    key: "fy",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
