import { defineNodes } from "@ndg/ndg-core";

export const nodes = defineNodes([
  {
    id: "bending_y_shear_check",
    type: "check",
    key: "bending_y_shear_check",
    valueType: { type: "number" },
    name: "Bending and shear resistance check about y-y",
    verificationExpression:
      "\\frac{\\left|M_{y,Ed}\\right|}{M_{y,V,Rd}} \\leq 1.0",
    meta: { sectionRef: "6.2.8", verificationRef: "(6.29)" },
    children: [{ nodeId: "M_y_Ed" }, { nodeId: "M_y_V_Rd" }],
  },
  {
    id: "M_y_Ed",
    type: "user-input",
    key: "M_y_Ed",
    valueType: { type: "number" },
    name: "Design bending moment about y-y",
    symbol: "M_{y,Ed}",
    unit: "\\mathrm{N\\cdot mm}",
    children: [],
  },
  {
    id: "M_y_V_Rd",
    type: "derived",
    key: "M_y_V_Rd",
    valueType: { type: "number" },
    name: "Reduced bending resistance about y-y under shear",
    symbol: "M_{y,V,Rd}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.8", formulaRef: "(6.30)" },
    children: [
      {
        nodeId: "M_y_V_Rd_i",
        when: { eq: ["section_shape", { value: "I" }] },
      },
      {
        nodeId: "M_y_V_Rd_rhs_chs",
        when: {
          or: [
            { eq: ["section_shape", { value: "RHS" }] },
            { eq: ["section_shape", { value: "CHS" }] },
          ],
        },
      },
    ],
  },
  {
    id: "M_y_V_Rd_i",
    type: "formula",
    key: "M_y_V_Rd_i",
    valueType: { type: "number" },
    name: "I-section reduced bending resistance about y-y under shear",
    symbol: "M_{y,V,Rd,i}",
    expression:
      "\\frac{\\left(W_{y,res} - \\rho \\dfrac{A_{v,z}^2}{4t_w}\\right) \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.8", formulaRef: "(6.30)" },
    children: [
      { nodeId: "W_y_res" },
      { nodeId: "rho_z" },
      { nodeId: "Av_z" },
      { nodeId: "tw" },
      { nodeId: "fy" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "M_y_V_Rd_rhs_chs",
    type: "derived",
    key: "M_y_V_Rd_rhs_chs",
    valueType: { type: "number" },
    name: "RHS/CHS reduced bending resistance about y-y under shear",
    symbol: "M_{y,V,Rd,RHS/CHS}",
    expression:
      "\\frac{\\left(W_{y,res}(1-\\rho)\\right) \\cdot f_y}{\\gamma_{M0}}",
    unit: "\\mathrm{N\\cdot mm}",
    meta: { sectionRef: "6.2.8", paragraphRef: "(3)" },
    children: [
      { nodeId: "W_y_res" },
      { nodeId: "rho_z" },
      { nodeId: "fy" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "W_y_res",
    type: "derived",
    key: "W_y_res",
    valueType: { type: "number" },
    name: "Class-dependent resistance modulus about y-y",
    symbol: "W_{y,res}",
    unit: "\\mathrm{mm^{3}}",
    children: [
      {
        nodeId: "Wpl_y",
        when: {
          or: [{ eq: ["section_class", { value: 1 }] }, { eq: ["section_class", { value: 2 }] }],
        },
      },
      {
        nodeId: "Wel_y",
        when: { eq: ["section_class", { value: 3 }] },
      },
    ],
  },
  {
    id: "Wpl_y",
    type: "user-input",
    key: "Wpl_y",
    valueType: { type: "number" },
    name: "Plastic section modulus about y-y",
    symbol: "W_{pl,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "Wel_y",
    type: "user-input",
    key: "Wel_y",
    valueType: { type: "number" },
    name: "Elastic section modulus about y-y",
    symbol: "W_{el,y}",
    unit: "\\mathrm{mm^{3}}",
    children: [],
  },
  {
    id: "rho_z",
    type: "derived",
    key: "rho_z",
    valueType: { type: "number" },
    name: "Shear reduction factor",
    symbol: "\\rho",
    children: [
      {
        nodeId: "rho_z_1",
        when: { lte: ["u_z", { value: 0.5 }] },
      },
      {
        nodeId: "rho_z_2",
        when: { gt: ["u_z", { value: 0.5 }] },
      },
    ],
  },
  {
    id: "rho_z_1",
    type: "derived",
    key: "rho_z_1",
    valueType: { type: "number" },
    name: "Shear reduction factor for low-shear branch",
    symbol: "\\rho_{z,1}",
    expression: "0",
    children: [],
  },
  {
    id: "rho_z_2",
    type: "derived",
    key: "rho_z_2",
    valueType: { type: "number" },
    name: "Shear reduction factor for high-shear branch",
    symbol: "\\rho_{z,2}",
    expression: "\\left(2u_z - 1\\right)^2",
    children: [{ nodeId: "u_z" }],
  },
  {
    id: "V_z_Ed",
    type: "user-input",
    key: "V_z_Ed",
    valueType: { type: "number" },
    name: "Design shear force about z-z",
    symbol: "V_{z,Ed}",
    unit: "\\mathrm{N}",
    children: [],
  },
  {
    id: "V_pl_z_Rd",
    type: "formula",
    key: "V_pl_z_Rd",
    valueType: { type: "number" },
    name: "Plastic shear resistance about z-z",
    symbol: "V_{pl,z,Rd}",
    expression: "\\dfrac{A_{v,z} \\cdot f_y}{\\sqrt{3}\\,\\gamma_{M0}}",
    unit: "\\mathrm{N}",
    meta: { sectionRef: "6.2.6", formulaRef: "(6.18)" },
    children: [
      { nodeId: "Av_z" },
      { nodeId: "fy" },
      { nodeId: "gamma_M0" },
    ],
  },
  {
    id: "u_z",
    type: "derived",
    key: "u_z",
    valueType: { type: "number" },
    name: "Shear utilization about z-z",
    symbol: "u_z",
    expression: "\\left|V_{z,Ed}\\right| / V_{pl,z,Rd}",
    children: [{ nodeId: "V_z_Ed" }, { nodeId: "V_pl_z_Rd" }],
  },
  {
    id: "Av_z",
    type: "user-input",
    key: "Av_z",
    valueType: { type: "number" },
    name: "Shear area about z-z",
    symbol: "A_{v,z}",
    unit: "\\mathrm{mm^{2}}",
    children: [],
  },
  {
    id: "tw",
    type: "user-input",
    key: "tw",
    valueType: { type: "number" },
    name: "Web thickness",
    symbol: "t_w",
    unit: "\\mathrm{mm}",
    children: [],
  },
  {
    id: "fy",
    type: "user-input",
    key: "fy",
    valueType: { type: "number" },
    name: "Yield strength",
    symbol: "f_y",
    unit: "\\mathrm{MPa}",
    children: [],
  },
  {
    id: "gamma_M0",
    type: "coefficient",
    key: "gamma_M0",
    valueType: { type: "number" },
    name: "Partial safety factor",
    symbol: "\\gamma_{M0}",
    meta: { sectionRef: "6.1" },
    children: [],
  },
]);

export type Nodes = typeof nodes;
